### ISSUE TITLE
Stripe Connect

### ISSUE THREAD

**Issue by andrelopez** [enupal/stripe#1]
### Description

Consider how to add an integration with Stripe Connect
####  Docs
https://stripe.com/docs/connect

**Comment by aladrach** [comment]
Is this still being considered?

**Comment by andrelopez** [comment]
@aladrach Currently doing research about this feature

**Comment by aladrach** [comment]
@andrelopez I can provide sample code where I have it working if that was help! It wasn’t particularly difficult I just want to be able to run updates as they’re released without re-merging my code.

**Comment by andrelopez** [comment]
@aladrach Sounds great, looking forward to it

**Comment by stevenjwright** [comment]
This would be a great addition. +1 from me on this

**Comment by aladrach** [comment]
Sorry, forgot to follow up here. 

https://github.com/aladrach/enupal-stripe-connect/blob/master/Checkout.php

Most of the magic is happening around line 267.

I added fields to the form admin to input the Stripe ID of the connected account, along with the desired platform fee, which are referenced in that section.

**Comment by andrelopez** [comment]
We're glad to announce that we just released Stripe Payments v3.0.0 with initial support for Stripe Connect, find more info in our docs [here](https://docs.enupal.com/stripe-payments/connect/overview.html)
