### ISSUE TITLE
Wrong Order Total when using more than 1 currency in separate forms

### ISSUE THREAD

**Issue by swinyx** [enupal/stripe#10]
### Description

It looks like the Order total is only calculated ( maybe hardcoded) in USD,
However when creating payment forms with other currencies, the total is not estimate in USD accordingly by converting the value from the form currency to USD.

Could it be possible to filter the total based on each currency ? then maybe have an option to estimate all transactions from different currencies converted to USD?

### Steps to reproduce

1. Create 2 forms (1 in USD, 1 in another currency)
2. Make more than 1 payments in each
3. Go to the order total page to see the payments
4. The Total revenue will not be accurate

### Additional info

- Craft version: Craft Solo 3.0.26.1
- PHP version: 7.2.9
- Database driver & version: MySQL 5.6.41
- Plugin version: 1.5.5

**Comment by andrelopez** [comment]
I'm on it! thanks

**Comment by swinyx** [comment]
Thank you, is it something that could be available soon?

**Comment by andrelopez** [comment]
Hi @swinyx 

We just released Stripe Payments v1.6.0 where we added a currency filter to the Chart. Please check all the release notes [here](https://github.com/enupal/stripe/blob/master/CHANGELOG.md#160---20181128) 

Please remember to backup your database before the upgrade and let us know how it goes.

We're still working in adding a default currency for the 'All' option.

Best
