### ISSUE TITLE
Error messages on required fields do not show up in safari

### ISSUE THREAD

**Issue by shantamg** [enupal/stripe#100]
### Description
The tooltips that are designed to pop up when a form is submitted without a required field being filled out do not work on safari on Mac OS and iOS. They seem to pop up for a split second and then disappear.

**Comment by andrelopez** [comment]
Hi, we just release Stripe Payments v2.7.0 with a fix to this issue. Please let us know if that works.

Thanks for reporting.

**Comment by shantamg** [comment]
Hi there.
Unfortunately, after updating the plugin I'm still seeing the same behavior. The tooltips which display the error message do not show up on iOS or Safari.
