### ISSUE TITLE
Errors not displaying, getting exceptions instead

### ISSUE THREAD

**Issue by sm-md-lg** [enupal/stripe#101]
### Description
When using a test card (`4000000000000002`) that causes a `card_declined` code it is not trapped using the [example error trapping code](https://docs.enupal.com/stripe-payments/templating/display-errors.html) in the documentation.

What I'm trying to do is have the page reload with the error message as part of it so the user can know what happened, otherwise a default "system error" is all they see.

I'm pretty sure it's me that's the problem but the documentation for this doesn't make sense to me.

### Steps to reproduce
Using this twig code:
```twig
{% set stripe = craft.enupalstripe.paymentForms({'handle': 'participantPayment'}).one() %}

{% if stripe is defined and stripe.getErrors() | length %}
  {% for errors in stripe.getErrors() %}
    <ul class="errors">
      {% for error in errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endfor %}
{% endif %}

{% set payment_options = {amount: 100.00, calculateFinalAmount: false} %}
{{stripe.paymentForm(payment_options)}}
```

When a payment is attempted with a invalid card an exception happens.
```
Stripe\Exception\CardException
Your card was declined.
```
![2020-06-03_17-01](https://user-images.githubusercontent.com/59664862/83700574-0a17fb80-a5bc-11ea-980a-cb4cceb35c41.png)

The twig code above is different than the example but I tried it that way as well and the same thing happened.  

### Additional info
- Craft version: 3.4.16
- PHP version: 7.2.24-0ubuntu0.18.04.6
- Database driver & version: mysqlnd 5.0.12-dev
- Plugin version: 2.6.1

**Comment by andrelopez** [comment]
Thanks for reporting, we'll fix this asap.

**Comment by andrelopez** [comment]
Hi, we just release Stripe Payments v2.7.0 with a fix to this issue. Please let us know if that works.

In this case, the next variable (payment form handle) will be available on your template if there are any errors: `participantPayment` so please update your template to the following block code:

```twig

{% if participantPayment is defined and participantPayment.getErrors() | length %}
  {% for errors in participantPayment.getErrors() %}
    <ul class="errors">
      {% for error in errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endfor %}
{% endif %}

{% set payment_options = {amount: 100.00, calculateFinalAmount: false} %}
{% set stripe = craft.enupalstripe.paymentForms({'handle': 'participantPayment'}).one() %}

{{stripe.paymentForm(payment_options)}}
```

**Comment by sm-md-lg** [comment]
Thanks! Its all good now.
