### ISSUE TITLE
Subscription Grants not working

### ISSUE THREAD

**Issue by idawgik** [enupal/stripe#105]
### Description
So I'm trying to get Subscription Grants working, however running into some problems.

It looks like it's a side effect of this issue: https://github.com/enupal/stripe/issues/44

Looking into the code, the Subscription Grants are looking for the `customer.subscription.created` event from the webhook, but that is sent before the `checkout.session.completed` event, so there's no order to attach the event to and process the grants.

I can manually resend the `customer.subscription.created` event through the Stripe dashboard, and then everything works.

Cancelling a subscription does work since the `customer.subscription.deleted` is received and mapped properly.

I have the webhook configured for All Events currently.

How do we get this working? It's built in functionality for the plugin, not trying to do anything custom. I don't see anything in the documentation around needing to do anything extra to get this working.

### Steps to reproduce

1. Configure Subscription Grant
2. Create Subscription
3. See grant was not processed and user is not added to groups

### Additional info

- Craft version: 3.4.23
- Plugin version: 2.7.0

**Comment by andrelopez** [comment]
@idawgik Sorry for the troubles, we'll fix this issue asap.

Thanks for reporting

**Comment by andrelopez** [comment]
Hi @idawgik We just released Stripe Payments v2.7.1 with a fix to this issue.

Best,

**Comment by idawgik** [comment]
Worked great. Thank you!
