### ISSUE TITLE
Possible to return payment type (Visa, Mastercard, Paypal, etc) in Admin email notification?

### ISSUE THREAD

**Issue by justinholtweb** [enupal/stripe#106]
### Description
We are using a custom template for order admin email notifications but wanted to see if there is a way to return and display the actual payment type (Visa, Mastercard, Paypal, etc) in that template. We are already using order.getPaymentMethod() and order.getPaymentType() in the template, but I don't see another order method to get this information.

### Additional info

- Craft version: 3.4.23
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.30
- Plugin version: 2.7.0

**Comment by andrelopez** [comment]
Hi @justinholtweb Please try the following example:

```twig

{% set stripeCustomer = craft.enupalStripe.getStripeCustomer(order.email) %}  
    
    {% set currentCard = 'No card' %}
    {# Check first for default payment method #}
    {% set paymentMethodId = stripeCustomer.invoice_settings.default_payment_method ?? null  %}

    {% if paymentMethodId %}
        
        {% set paymentMethod = craft.enupalStripe.getPaymentMethod(paymentMethodId) %}

        {% if paymentMethod.card is defined %}
            {% set currentCard = paymentMethod.card.brand ~ " ending in " ~ paymentMethod.card.last4 %}
        {% endif %}

    {% else %}

        {% set currentCard = stripeCustomer.default_source.brand ~ " ending in " ~ stripeCustomer.default_source.last4 %}

    {% endif %}

    <h1>Current Card:<h2> <code> {{currentCard}}</code>
```

Please let me know if you have any questions. The full example is taken from the update card docs (https://docs.enupal.com/stripe-payments/templating/update-card-info.html)

**Comment by justinholtweb** [comment]
Thanks @andrelopez I tested with this in the admin email template we are using and it did not render the card type name or the last 4 unfortunately. May just call this one as a no-go for now. 

Thanks for checking!
