### ISSUE TITLE
Payment details empty in Stripe

### ISSUE THREAD

**Issue by Coysh** [enupal/stripe#107]
### Description
I've got the form working to send payments through to Stripe - but the Description field in Stripe is empty.

You can see the empty description in the attached screenshot.
![image](https://user-images.githubusercontent.com/5764356/84512869-84cdce80-acc0-11ea-8e69-2bc30a8dc8ea.png)

### Additional info

- Craft version: 3.4.0
- PHP version: 7.4
- Database driver & version:
- Plugin version:2.7.1
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @Coysh We just released Stripe Payments v2.7.2 with a fix to this issue. Thanks for reporting

Best

**Comment by Coysh** [comment]
@andrelopez thanks, however if I'm using line items - the description gets reset to `Order from <email address>`.
Is there anyway to set the description if you#re using `removeDefaultItem: true`?

`{% set options = {
	amount: amt,
	calculateFinalAmount: false,
	removeDefaultItem: true,
	lineItems: lineItems,
} %}`
