### ISSUE TITLE
No error if custom email template not found

### ISSUE THREAD

**Issue by sm-md-lg** [enupal/stripe#108]
### Description
When using a custom email template for customer notifications, an error is **not** thrown if the custom template is not found.  It appears to automatically use the default template.

This may not be a bug but a decision you've made, if so ignore this report.  My feelings though is that an error should be thrown so the issue can be diagnosed easier (in my case a misspelled path).

### Additional info

- Craft version: 3.4.16
- PHP version: 7.2.24-0ubuntu0.18.04.6
- Database driver & version: mysqlnd 5.0.12-dev
- Plugin version: 2.7.0
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: SCA: not enabled, Stripe Checkout not enabled.

**Comment by andrelopez** [comment]
This is a UI issue, we'll add support for suggesting templates field. Thanks

**Comment by andrelopez** [comment]
Hi @sm-md-lg  We just released Stripe Payments v2.7.2 with a fix to this issue (we added the autosuggest field that will prevent this kind of issue, but we default to the default template if the template overrides does not exist). Thanks for reporting

Best
