### ISSUE TITLE
Exception when enter key is hit

### ISSUE THREAD

**Issue by sm-md-lg** [enupal/stripe#109]
### Description

When editing the email field or credit card field, if enter is hit, an exception is thrown (but clicking the submit button works properly). 

#### Form
![Screen Shot 2020-06-12 at 11 02 59 AM](https://user-images.githubusercontent.com/59664862/84533297-b6cd3980-ac9c-11ea-91bd-a116cc795b56.png)

#### Error
```
HTTP 404 – Not Found – yii\web\NotFoundHttpException
Unable to process the Payment
```
![Screen Shot 2020-06-12 at 11 04 01 AM](https://user-images.githubusercontent.com/59664862/84533342-cfd5ea80-ac9c-11ea-8cd0-b9a5da377f40.png)

### Additional info

- Craft version: 3.4.16
- PHP version: 7.2.24-0ubuntu0.18.04.6
- Database driver & version: mysqlnd 5.0.12-dev
- Plugin version: 2.7.0
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: SCA: not enabled, Stripe Checkout not enabled.

**Comment by andrelopez** [comment]
Hi @sm-md-lg We just released Stripe Payments v2.7.2 with a fix to this issue. Thanks for reporting

Best
