### ISSUE TITLE
Subscription Limit

### ISSUE THREAD

**Issue by bymayo** [enupal/stripe#110]
Is there a limit on the amount of subscriptions/plans that appear in the drop down when creating a payment form?

We've created numerous plans, but only a set amount appear.

**Comment by andrelopez** [comment]
Hi @bymayo Could you please go to Stripe Payments -> Settings -> Defaults and disabled 'Retrieve plans with a nickname' we'll disable this option by default on the next release.

**Comment by bymayo** [comment]
@andrelopez This fixes the issue!

So is this because our client didn't set a name for the plan?
