### ISSUE TITLE
Syncing Stripe orders fails

### ISSUE THREAD

**Issue by Coysh** [enupal/stripe#112]
### Description
Trying to Sync Orders from Stripe fails with the error:
`2020-06-23 17:23:09 [-][-][-][error][enupal\stripe\jobs\SyncOneTimePayments::execute] Sync process failed: Could not determine which URL to request: Stripe\Customer instance has invalid ID: `

Settings as below
![image](https://user-images.githubusercontent.com/5764356/85429366-888e0a80-b576-11ea-8a10-830d7708a490.png)

**Comment by andrelopez** [comment]
Hi @Coysh We just released Stripe Payments v3.0.0 with a fix to this issue. Thanks for reporting!
