### ISSUE TITLE
Coupon code applying when SCA is enabled + Subscriptions

### ISSUE THREAD

**Issue by studiountitled** [enupal/stripe#113]
### Description

When using a coupon code on a multiple subscription option webform, the 'check coupon' button shows successful and the total is updated, however when the customer proceeds to stripe the discounted amount is not being charged, instead the full amount is

This only happens when SCA is enabled – when disabled it functions as expected

### Steps to reproduce

1. See an example form here: https://www.womanbyabbyrose.com.au/test-form
2. Choose any plan and enter code: 'testtest'

### Additional info

- Craft version: Craft Pro 3.4.26
- PHP version: 7.0
- Database driver & version: MySQL 5.7.28
- Plugin version:  2.7.2
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @studiountitled thanks for reaching out. Coupons on [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html#stripe-checkout-features) are only available for one-time payments, however, Stripe is currently working to have this feature in their Stripe Checkout coming soon. I'll let you know when we add support to this feature

**Comment by andrelopez** [comment]
Hi @studiountitled This feature is available since v3.0.0, here is the full example https://docs.enupal.com/stripe-payments/coupons/subscription-coupons.html
