### ISSUE TITLE
[FR] Stripe Direct Debits

### ISSUE THREAD

**Issue by Coysh** [enupal/stripe#119]
### Description
Not sure how complicated this would be, but it's based on Stripe Checkout - so in theory not difficult?
https://stripe.com/gb/payments/bacs-debit

**Comment by andrelopez** [comment]
Hi @Coysh Yes, we're currently working on adding support to Stripe Connect, if you want us to prioritize this ticket please reach us to support@enupal.com if you already have BACS enabled on your Stripe Account it will help.

**Comment by andrelopez** [comment]
Hi @Coysh we just released Stripe Payments v3.2.1 with support to Bacs Direct Debit. Remember to enable [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and enable Stripe Checkout on your payment forms

**Comment by Coysh** [comment]
@andrelopez - I was under the impression Stripe Checkout didn't support BACS Direct Debit yet: [https://stripe.com/docs/payments/payment-methods/bacs-debit#connect](https://stripe.com/docs/payments/payment-methods/bacs-debit#connect)

Is this outdated information on Stripe's website?

**Comment by andrelopez** [comment]
Hi @Coysh Yes it's outdated. They added support to BACS Direct Debit a few weeks ago to the new Stripe Checkout. However only accounts opened in the UK have this payment method. Please let me know how it goes.

**Comment by gazlawn22** [comment]
Do you have any idea when subscriptions would be supported by BACS Direct debit in the UK?

**Comment by domstubbs** [comment]
I’m trying to figure out Direct Debit subscriptions for a client at the moment and this issue gave me a little hope, but when I contacted Stripe earlier they confirmed it’s not supported yet:

> Bacs is not available for subscriptions on Checkout at the moment. However, Bacs is available for subscriptions created through Billing.
> 
> I wish I had better news, but we currently do not have an ETA for Bacs being supported for Subscriptions mode in Checkout. There is a small bit of good news though, I have  checked my internal notes and I can confirm it is being actively worked on.This is in high demand so it is a priority of ours and you should expect to see it available in the near future. 

Despite this I thought I’d attempt a DD subscription with a trial install of this plugin to see what happens, and sure enough this error was returned by the API when I submitted my test form:

> "The payment method `bacs_debit` cannot be used in `subscription` mode.”

This [support doc](https://stripe.com/docs/billing/subscriptions/bacs-debit) is the best/only setup guide I’ve found so far. It looks as though this plugin could take care of some of those API calls but I’m not clear on how much additional dev would be required. Even more confusingly, that guide does suggest you can use Checkout for at least some of the flow.

If anyone out there has personal experience with auto-renewing DDs through Stripe via Craft I’d be very interested to hear how they went about it…

**Comment by andrelopez** [comment]
@domstubbs Sorry the support doc link (https://stripe.com/docs/billing/subscriptions/bacs-debit) does not show much information on my end, could you please double-check? do you mean this link https://stripe.com/docs/payments/bacs-debit/save-bank-details ?

It looks like the support for subscriptions is going to available soon.

**Comment by domstubbs** [comment]
That is the right link – it includes the requirements for setting up the DD as well as initiating a subscription, whereas the second link just covers the DD setup process. Unless Stripe’s geolocating the doc pages for some reason.

Can you clarify what level of DD support the plugin has? I tried a one-off DD payment this morning and Stripe returned the error:

> The payment method `bacs_debit` requires `payment_intent_data[setup_future_usage]` to be set to `off_session`.

I assume that for DDs we need a two-step workflow, first to save/setup the DD, then a second to start a subscription.

To save the DD we need a call to `/checkout/sessions` with `mode: setup` and `payment_method_types: [bacs_debit]`. Having had a quick search through the source for the repo the only [equivalent API call](https://github.com/enupal/stripe/blob/5f80bd7ad8725db8bdd861052d6525c61fe9160e/src/services/Checkout.php#L447) I can see is hard-coded to send `payment_method_types: [card]`.
