### ISSUE TITLE
Form fields tab is empty

### ISSUE THREAD

**Issue by studiosyntax** [enupal/stripe#12]
### Description
When I edit a new Payment form, the Form Fields tab is empty.
This causes an error when trying to view a form on the front-end;

`Calling unknown method: enupal\stripe\elements\PaymentForm::enupalStripeBasicFields()`

### Steps to reproduce

1. Edit a Payment Form
2. Click on Form Fields Tab
3. See nothing
4. No profit

### Additional info

- Craft version: 3.0.32
- PHP version: 7.1
- Database driver & version: MySQL
- Plugin version: 1.5.10

**Comment by andrelopez** [comment]
Hi @shoored,

Thanks for reaching out. I have updated to Craft 3.0.32 but I'm unable to recreate this error.

It looks like something went wrong during the upgrade and the Stripe Payments fields attached to the layout was deleted somehow. Could you please share your database via email? support@enupal.com

Best,

**Comment by andrelopez** [comment]
Hi @studiosyntax any update about this issue?

**Comment by studiosyntax** [comment]
Hi @andrelopez - so sorry for the late reply! Things got hectic. When I uninstalled and then reinstalled the plugin, everything seemed in order!

I can't wait to try the new features. Thanks for all your work on this 👍

**Comment by andrelopez** [comment]
@studiosyntax Glad that you got that solved.
