### ISSUE TITLE
A server error occurred, fresh install, no orders.

### ISSUE THREAD

**Issue by shornuk** [enupal/stripe#120]
### Description

Just installed to test this out. After installing and going to Stripe Payments > Orders I get a flash message with `A server error occurred.` - Once orders are made this disappears.

Any ideas on why or where to start debugging?

### Additional info

- Craft version: 3.4.29.1
- PHP version: 7.2.24
- Plugin version: 2.7.2
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by andrelopez** [comment]
Hi @shornuk I was able to recreate this issue and a fix will be added on the next release. Thanks for reporting

**Comment by shornuk** [comment]
Awesome 👍

**Comment by andrelopez** [comment]
Hi @shornuk  we just released Stripe Payments v3.0.0 with a fix to this issue. Thanks for reporting.
