### ISSUE TITLE
Postgres Error Database Exception – yii\db\Exception

### ISSUE THREAD

**Issue by theskyfloor** [enupal/stripe#122]
### Description

Error on PGsql when not in test mode:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type boolean: ""
The SQL being executed was: SELECT *
FROM "enupalstripe_customers"
WHERE ("email"='email@email.com') AND ("testMode"='')

Test mode is blank but needs to equal 0 or Postgres throws an error.

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugin version:
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by andrelopez** [comment]
Hi @theskyfloor  we just released Stripe Payments v3.0.0 with a fix to this issue. Thanks for reporting!

**Comment by theskyfloor** [comment]
Thanks Andre!
