### ISSUE TITLE
Please add the Stripe API keys in the plugin settings for LIVE mode?!

### ISSUE THREAD

**Issue by sunscreem** [enupal/stripe#125]
### Description

I've just upgraded to v3 and pushed to production and now I'm getting that error on my payment page.

The back end can see the keys loaded correctly:

![image](https://user-images.githubusercontent.com/7523595/90165109-183e8100-dd90-11ea-8f06-1bf0c35c79c4.png)

### Steps to reproduce

1. Add keys via config.

### Additional info

- Craft version:  Craft Pro 3.5.3
- PHP version: 7.2.33
- Database driver & version: MySQL 5.7.31
- Plugin version:3.0.0
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Y

**Comment by sunscreem** [comment]
Never mind. 

The keys in the docs have different names to the keys in my .env.

**Comment by Slgoetz** [comment]
@sunscreem how did you update to Stripe API v3 - looking to do this but cant seem to find it in the docs.
