### ISSUE TITLE
Can't save settings on v3.0

### ISSUE THREAD

**Issue by sunscreem** [enupal/stripe#126]
### Description

Two separate installs same problem. Working locally - dev mode on.

![image](https://user-images.githubusercontent.com/7523595/90185682-f7d1ef00-ddae-11ea-80e5-800cb487c66e.png)

### Steps to reproduce

1. Got to setting
2. Hit save

### Additional info

Craft version: Craft Pro 3.5.3
PHP version: 7.2.33
Database driver & version: MySQL 5.7.31
Plugin version:3.0.0
Is SCA and Stripe Checkout enabled?: Y

**Comment by sunscreem** [comment]
Definitely not my error this time lol

**Comment by sunscreem** [comment]
@andrelopez The only setting I need to change here is the SCA. Can I do this from the config as a workaround?

**Comment by andrelopez** [comment]
Hi @sunscreem could you please send me a zip file of your logs `storage/logs` after recreate the error? We'll fix the issue right away. Please send it to support@enupal.com

**Comment by sunscreem** [comment]
Thanks - done. :)

**Comment by andrelopez** [comment]
Hi @sunscreem We just released Stripe Payments v3.0.1 with a fix to this error. Thank you for reporting.

**Comment by sunscreem** [comment]
@andrelopez confirmed working fine :)
