### ISSUE TITLE
Coupons error with "Unable to process the Payment"

### ISSUE THREAD

**Issue by bymayo** [enupal/stripe#127]
We're getting an error when submitting a coupon code:

![Screenshot 2020-08-17 at 10 35 10](https://user-images.githubusercontent.com/522877/90384152-094e1c00-e079-11ea-8a7f-880dcfd4ca8c.png)

This happens when we input a coupon code and click "Check code". If we don't apply a code and continue to payment it works fine.

Can I just double check that the code we're entering in the coupon code box is the one under `Stripe Payments > Coupons > ID Column`?

We're passing the amount and quantity to the form, and we're also using SCA and I've added the config option in:

```
{{ craft.enupalstripe.paymentForm(
    messageService.paymentForm.one().handle,
    {
        'amount': messageService.priceSale|length ? messageService.priceSale : messageService.price,
        'quantity': 1,
        'allowPromotionCodes': true
    }
) }}
```

I upgraded to 3.0.1 but it was not working on 2.7.2

### Additional info

- Craft version: 3.4.29
- PHP version: 7.1
- Database driver & version: MySQL 5.7
- Plugin version: 3.0.1
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes / Yes

**Comment by andrelopez** [comment]
Hi @bymayo `allowPromotionCodes` is only available for subscriptions (stripe says that one-time payments will support coupons soon), if you're processing one-time payments you need to use our [coupons workflow](https://docs.enupal.com/stripe-payments/coupons/overview.html):

```
{{ craft.enupalstripe.paymentForm(
    messageService.paymentForm.one().handle,
    {
        'amount': messageService.priceSale|length ? messageService.priceSale : messageService.price,
        'quantity': 1,
        'coupon' : {
           'enabled' : true,
           'label' : 'Apply to this coupon',
           'successMessage': '{name} applied',
           'errorMessage': 'Invalid Coupon',
           'displayTotal': true,
           'totalAmountLabel': 'Total',
           'removeCouponLabel': 'Remove Coupon',
           'checkCouponLabel': 'Check Coupon'
        }
    }
) }}
```

Please let me know if that could work

**Comment by bymayo** [comment]
@andrelopez This seems to make the coupon code work better! But then it never takes me to Stripe and I get this error appear in console:

```
POST https://website.com/message/enupal/stripe/create-checkout-session 500
```

Just ot be clear, are you saying Coupons don't work for one-time payments? But they do for subscriptions? If this is the case, the above error is happening for one-time payments, but the original issue with the `Unable to process payment` error still appears for subscription payments

**Comment by andrelopez** [comment]
@bymayo Thanks, it looks like a bug from our part. I'll take a look

**Comment by lesaff** [comment]
@andrelopez Any update on this issue? I am experiencing the same error. Thanks

**Comment by andrelopez** [comment]
@bymayo

The following example will work for coupons only for One-Time payments (When SCA is enabled or disabled)

```twig
{{ craft.enupalstripe.paymentForm(
    messageService.paymentForm.one().handle,
    {
        'amount': messageService.priceSale|length ? messageService.priceSale : messageService.price,
        'quantity': 1,
        'coupon' : {
           'enabled' : true,
           'label' : 'Apply to this coupon',
           'successMessage': '{name} applied',
           'errorMessage': 'Invalid Coupon',
           'displayTotal': true,
           'totalAmountLabel': 'Total',
           'removeCouponLabel': 'Remove Coupon',
           'checkCouponLabel': 'Check Coupon'
        }
    }
) }}
```

The following example will work for coupons only for when SCA is enabled and for subscriptions or recurring payments ([docs](https://docs.enupal.com/stripe-payments/coupons/subscription-coupons.html))

```twig
{{ craft.enupalstripe.paymentForm(
    messageService.paymentForm.one().handle,
    {
        'amount': messageService.priceSale|length ? messageService.priceSale : messageService.price,
        'quantity': 1,
        'allowPromotionCodes' : true
    }
) }}
```

Please let me know if that works

**Comment by bymayo** [comment]
@andrelopez Just following up on this. 

I've tried to get this working again, but I'm still hitting the same issue I originally had. I've updated to 3.2.2 also.

**Comment by andrelopez** [comment]
Hi @bymayo Did you check our latest docs? https://docs.enupal.com/stripe-payments/coupons/overview.html#coupons-on-the-new-stripe-checkout
Now coupons can be enabled when you're editing your Payment Forms in the CP. On the new Stripe Checkout, you shouldn't see coupons input on the front-end. Could you please confirm that?

**Comment by bymayo** [comment]
@andrelopez Doh. I did read that, but totally missed the bit about enabling it per form. Enabled this now and it works a treat on Stripes side! Thanks
