### ISSUE TITLE
Sync orders starts queue job but doesn't change

### ISSUE THREAD

**Issue by sunscreem** [enupal/stripe#128]
### Description

After upgrading to v3 (I had a few issues - probably my issues) I've got no past orders showing.

I've hit sync and the queued job starts, but doesn't seem to do anything

![image](https://user-images.githubusercontent.com/7523595/90628497-a1810800-e215-11ea-9127-4a456b199853.png)

### Steps to reproduce

1. Sync Orders (One time orders)

### Additional info

- Craft version: Craft Pro 3.5.4
- PHP version: 7.2.33
- Database driver & version: MySQL 5.7.31
- Plugin version:3.0.1
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Y

**Comment by andrelopez** [comment]
@sunscreem Sorry I was unable to recreate this issue. Did you get any error? could you please recreate the issue and send back to us a zip file of the following folder to support@enupal.com?
`storage/logs`

**Comment by sunscreem** [comment]
Hey @andrelopez I just went in to reproduce the problem and all the orders are there. I've done a couple of craft updates this week and deployed a few times, so I suspect whatever was 'stuck' has fixed itself now.

Sorry for the messing around. I never thought to go back and check it until you tagged me.
