### ISSUE TITLE
How to register new subscriber as a user?

### ISSUE THREAD

**Issue by lesaff** [enupal/stripe#132]
### Description
I want to register a new subscriber as a user and grant him/her access to a certain group. I cannot find anything on the documentation.

Thx

**Comment by andrelopez** [comment]
Hi @lesaff you have two options here:

1.- The user is registered before presenting the payment form, here is a brief sign up [craft form](https://craftcms.com/docs/3.x/dev/examples/user-registration-form.html)

Then when the user is logged in, you can use the subscription grant feature [here](https://docs.enupal.com/stripe-payments/stripe-payment-forms/subscription-grants.html), to grant the user group automatically 

2.- Register the user via custom plugin listening to the `afterOrderComplete` [event](https://docs.enupal.com/stripe-payments/plugin-development/events.html#afterordercomplete) you can get the email via `$order->email` 
(exampe taken from [here](https://craftcms.stackexchange.com/a/28360/4798))
```php
use craft\elements\User;


$user = new User();
$user->pending = true;
$user->username = $order->email;
$user->email = $order->email;
$user->passwordResetRequired = false;
$user->validate(null, false);
Craft::$app->getElements()->saveElement($user, false);
Craft::$app->getUsers()->sendActivationEmail($user);
```

and then you can assing the user like the following example:

```php
// assing the user groups IDs here
$newGroups = [1];
Craft::$app->getUsers()->assignUserToGroups($user->id, $newGroups);
```

please let me know how it goes

**Comment by lesaff** [comment]
@andrelopez Thank you so much for your help. I used your option 2 and it works and I was able to register a new subscriber.

Cheers!

**Comment by idawgik** [comment]
@lesaff were you able to get the order/subscription to be associated to the newly created user? If so, how?

**Comment by lesaff** [comment]
@idawgik 

Here's I did it.

Make sure to include this in your custom module/pluging
```
use craft\elements\User;
use enupal\stripe\events\OrderCompleteEvent;
use enupal\stripe\events\WebhookEvent;
use enupal\stripe\services\Orders;
use enupal\stripe\Stripe;
```

And then, place this code in your module `init()`

In this case, I assign user to group based on given subscription nickname. You can change it accordingly.

```
// Register new subscriber
Event::on(
    Orders::class, 
    Orders::EVENT_AFTER_ORDER_COMPLETE, 
    function (OrderCompleteEvent $e) {

        $order = $e->order;
        $user = new User();

        $user->pending = true;
        $user->username = $order->email;
        $user->email = $order->email;
        $user->passwordResetRequired = false;
        $user->validate(null, false);
        Craft::$app->getElements()->saveElement($user, false);
        Craft::$app->getUsers()->sendActivationEmail($user);

        $sub = $order->getSubscription();

        // assign the user groups IDs here
        switch($sub->nickName) {
            case 'Monthly Subscription':
                $newGroups = [1];
                break;
            case 'Quarterly Subscription':
                $newGroups = [2];
                break;
            case 'Annual Subscription':
                $newGroups = [3];
                break;
        }
        Craft::$app->getUsers()->assignUserToGroups($user->id, $newGroups);
    }
);
```
