### ISSUE TITLE
Exception error on Customer Portal form POST

### ISSUE THREAD

**Issue by lesaff** [enupal/stripe#133]
### Description
I am adding a customer portal button per https://docs.enupal.com/stripe-payments/templating/update-billing.html

Getting an exception error on submit.

```
HTTP 400 – Bad Request – yii\web\BadRequestHttpException
Post request required
1. in /Users/rudy/Sites/resourcemaven/vendor/craftcms/cms/src/web/Controller.phpat line 348
339340341342343344345346347348349350351352353354355356357 
    /**
     * Throws a 400 error if this isn’t a POST request
     *
     * @throws BadRequestHttpException if the request is not a post request
     */
    public function requirePostRequest()
    {
        if (!$this->request->getIsPost()) {
            throw new BadRequestHttpException('Post request required');
        }
    }
 
    /**
     * Throws a 400 error if the request doesn't accept JSON.
     *
     * @throws BadRequestHttpException if the request doesn't accept JSON
     */
    public function requireAcceptsJson()
2. in /Users/rudy/Sites/resourcemaven/vendor/enupal/stripe/src/controllers/StripeController.php at line 149– craft\web\Controller::requirePostRequest()
143144145146147148149150151152153154155     * @return \yii\web\Response|null
     * @throws \yii\web\BadRequestHttpException
     * @throws \yii\base\Exception
     */
    public function actionCreateCustomerPortal()
    {
        $this->requirePostRequest();
        $request = Craft::$app->getRequest();
        $returnUrl = $request->getBodyParam('returnUrl') ?? UrlHelper::siteUrl('/');
        $user = Craft::$app->getUser()->getIdentity();
 
        if (is_null($user)) {
            return $this->redirectToPostedUrl();
3. enupal\stripe\controllers\StripeController::actionCreateCustomerPortal()
4. in /Users/rudy/Sites/resourcemaven/vendor/yiisoft/yii2/base/InlineAction.php at line 57– call_user_func_array([enupal\stripe\controllers\StripeController, 'actionCreateCustomerPortal'], [])
5. in /Users/rudy/Sites/resourcemaven/vendor/yiisoft/yii2/base/Controller.php at line 180– yii\base\InlineAction::runWithParams([])
6. in /Users/rudy/Sites/resourcemaven/vendor/craftcms/cms/src/web/Controller.php at line 181– yii\base\Controller::runAction('create-customer-portal', [])
175176177178179180181182183184185186187    /**
     * @inheritdoc
     */
    public function runAction($id, $params = [])
    {
        try {
            return parent::runAction($id, $params);
        } catch (\Throwable $e) {
            if ($this->request->getAcceptsJson()) {
                Craft::$app->getErrorHandler()->logException($e);
                if (!YII_DEBUG && !$e instanceof UserException) {
                    $message = Craft::t('app', 'A server error occurred.');
                } else {

```
### Steps to reproduce

1. https://docs.enupal.com/stripe-payments/templating/update-billing.html
2. Click button

### Additional info

- Craft version: Craft Pro 3.5.7
- PHP version: 7.4.9
- Database driver & version: MySQL 5.5.5
- Plugin version: 3.0.2
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: yes

**Comment by lesaff** [comment]
Sorry to bug you @andrelopez , any luck with this? Thx

**Comment by andrelopez** [comment]
@lesaff This sounds like a cache issue that is preventing to generate valid CSRF tokens from this line
`{{ csrfInput() }}`

Could you please check in your templates if your customer portal form is inside any `{% cache %}` tag?

**Comment by lesaff** [comment]
@andrelopez I am not using any caching method at this point. The site is still run locally during development.

I took the code directly from your example and add classes and change the redirect URL
```
<form method="POST" action="/enupal-stripe/customer-portal">
    {{ csrfInput() }}
    <input type="hidden" name="returnUrl" value="{{ siteUrl('/my-subscriptions') }}">
    <input type="submit" class="px-4 py-2 text-white rounded bg-brand-red hover:bg-brand-red-dark" value="Manage Subscription">
</form>
```

**Comment by andrelopez** [comment]
@lesaff Could you please try the following example?


```
<form method="post" accept-charset="UTF-8">
    {{ csrfInput() }}
    <input type="hidden" name="action" value="enupal-stripe/stripe/create-customer-portal">
    <input type="hidden" name="returnUrl" value="{{ siteUrl('/my-subscriptions') }}">
    <input type="submit" class="px-4 py-2 text-white rounded bg-brand-red hover:bg-brand-red-dark" value="Manage Subscription">
</form>
```

**Comment by lesaff** [comment]
OK, it's not throwing any exception anymore.

See below

![Screen Shot 2020-09-04 at 12 12 06 PM](https://user-images.githubusercontent.com/1151181/92255135-43585400-eea8-11ea-8457-ec2eb88f976e.png)

**Comment by lesaff** [comment]
One problem, it did not open the Stripe Customer Portal, just refreshed the current page with status 304.

**Comment by andrelopez** [comment]
@lesaff Could you please check that the logged-in user already has an order?

**Comment by lesaff** [comment]
Yes, the logged-in user already has an order (set as new). I checked the order and compared it to the Stripe console. This is still in the Stripe test mode by the way. I tried setting the order to processed and it still does not open the Customer Portal.

**Comment by andrelopez** [comment]
@lesaff Could you please manually check `enupalstripe_customers` table in your db and check if the email of the logged-in user is there?

Could you please contact us via email to support@enupal.com ? we may need to schedule a quick call to share screens and start debugging as I'm still unable to recreate this issue.

**Comment by lesaff** [comment]
@andrelopez Update on this: I just deployed my site to a staging server with a public URL and it works fine. Looks like Stripe Customer Portal does not work on local development, even though I use stripe-cli as my webhook target.

You can close this and perhaps add a note to your documentation in case other people encountered the same issue.

Thanks again for such a powerful and easy to use plugin. Cheers!

**Comment by andrelopez** [comment]
@lesaff thanks for reporting. I'll add this to the docs.

Thank you!
