### ISSUE TITLE
Update to 3.1.0. from 3.0.2 Seems to need Craft Commerce installed?

### ISSUE THREAD

**Issue by wooge** [enupal/stripe#138]
### Description
After attempting to upgrade to 3.1.0 from 3.0.2 the upgrade fails with this error:
`
A fatal error has occurred:

Status: Internal Server Error

Response: <pre>Exception &#039;Error&#039; with message &#039;Class &#039;craft\commerce\elements\Product&#039; not found&#039;

in /srv/www/mysite.com/vendor/enupal/stripe/src/Stripe.php:121

Stack trace:
#0 /srv/www/mysite.com/vendor/yiisoft/yii2/base/BaseObject.php(109): enupal\stripe\Stripe-&gt;init()
#1 /srv/www/mysite.com/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject-&gt;__construct()
#2 /srv/www/mysite.com/vendor/craftcms/cms/src/base/Plugin.php(115): yii\base\Module-&gt;__construct()
#3 [internal function]: craft\base\Plugin-&gt;__construct()
#4 /srv/www/mysite.com/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass-&gt;newInstanceArgs()
#5 /srv/www/mysite.com/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container-&gt;build()
#6 /srv/www/mysite.com/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container-&gt;get()
#7 /srv/www/mysite.com/vendor/craftcms/cms/src/services/Plugins.php(908): yii\BaseYii::createObject()
#8 /srv/www/mysite.com/vendor/craftcms/cms/src/services/Plugins.php(227): craft\services\Plugins-&gt;createPlugin()
#9 /srv/www/mysite.com/vendor/craftcms/cms/src/base/ApplicationTrait.php(1416): craft\services\Plugins-&gt;loadPlugins()
#10 /srv/www/mysite.com/vendor/craftcms/cms/src/web/Application.php(104): craft\web\Application-&gt;_postInit()
#11 /srv/www/mysite.com/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application-&gt;init()
#12 /srv/www/mysite.com/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject-&gt;__construct()
#13 /srv/www/mysite.com/vendor/craftcms/cms/src/web/Application.php(92): yii\base\Application-&gt;__construct()
#14 [internal function]: craft\web\Application-&gt;__construct()
#15 /srv/www/mysite.com/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass-&gt;newInstanceArgs()
#16 /srv/www/mysite.com/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container-&gt;build()
#17 /srv/www/mysite.com/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container-&gt;get()
#18 /srv/www/mysite.com/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject()
#19 /srv/www/mysite.com/vendor/craftcms/cms/bootstrap/web.php(51): require(&#039;/srv/www/osog.d...&#039;)
#20 /srv/www/mysite.com/web/index.php(21): require(&#039;/srv/www/osog.d...&#039;)
#21 {main}</pre>`

... and the site reports the following error when trying to access it:
`
Class 'craft\commerce\elements\Product' not found
in /srv/www/mysite.com/vendor/enupal/stripe/src/Stripe.phpat line 121 ......
`

Rolling back to previous version restores the site.

- Craft version: Craft Pro 3.5.9 
- PHP version: 7.4.9
- Database driver & version: MySQL 5.7.31
- Plugin version: 3.1.0 / 3.0.2
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes.
- Stripe Commerce is NOT installed.

**Comment by andrelopez** [comment]
I'll fix this issue in a few minutes. Thanks for reporting

**Comment by andrelopez** [comment]
Hi @wooge We just released Stripe Payments v3.1.1 with a fix to this issue. Thanks again for reporting

**Comment by wooge** [comment]
Confirmed fixed! — thanks for the super fast fix!
