### ISSUE TITLE
Adding quantity for reoccurring payments

### ISSUE THREAD

**Issue by matanlevkowich** [enupal/stripe#14]
### Description
Is there a way to add quantities for reoccurring payment plans?
I am trying to enable my customers to choose how many plans they want to subscribe to and pay X amount per plan. I have set it up properly on the Stripe dashboard but can't seem to find how it will work with the plugin...

### Additional info

- Craft version: Craft Pro 3.0.12
- PHP version: 7.0.32
- Database driver & version: MySQL 5.7.24
- Plugin version: 1.5.7

**Comment by andrelopez** [comment]
Hi @matanlevkowich 

We just released Stripe Payments v1.6.0 where we added support to tiered plans. Please check all the release notes [here](https://github.com/enupal/stripe/blob/master/CHANGELOG.md#160---20181128)

Please remember to backup your database before the upgrade and let us know how it goes.

We're still working in the docs, but you need to pass the quantity in the `paymentForm` tag:

```twig
{{ craft.enupalstripe.paymentForm('formHandle', {quantity: 20}) }}
```

Please let us know how it goes.

Best
