### ISSUE TITLE
Coupons w/multiple payment forms on same page issues

### ISSUE THREAD

**Issue by siebird** [enupal/stripe#140]
I've been able to get multiple payment forms on the same page without issue by passing a few unique variables and using my own custom templates. However, once I introduce coupons to each form I run into the javascript issues with how the plugin targets those buttons to prevent the form from submitting. 

Is it possible to change how the JS is targeting the coupon and form? Right now it's by id, however, if I have multiple payment forms on the same page using the same form id it breaks.

**Comment by siebird** [comment]
I think an easy fix could be passing a unique id to override the `paymentForm.id`. That way the JS can stay as it and each payment form on a page is unique.

**Comment by andrelopez** [comment]
Hi @siebird we just released Stripe Payments v3.2.1 with support for coupons. This feature is only available for the new Stripe Checkout, more info here https://docs.enupal.com/stripe-payments/coupons/overview.html
