### ISSUE TITLE
Can't install (3.1.3)

### ISSUE THREAD

**Issue by angieherrera** [enupal/stripe#141]
Not sure if this is the right place for this issue, but here goes.

In Craft (v3.5.11.1), went to the Plugin Store, and hit the Try button. When it's done updating composer, I don't see it in the side navigation but do see it at the bottom of the Plugins list showing as "Not installed". So I click on the cog/dropdown and click on Install and all I get is a red notice at the top saying "Couldn't install plugin."

Not sure what is going on. I did try installing a trial of two other plugins (one of which was Enupal Snapshot) to see if they would work. They did.

**Comment by andrelopez** [comment]
Hi @angieherrera Could you please recreate the error and send back to us a zip file of the following folder to support@enupal.com ?

`storage/logs`

**Comment by angieherrera** [comment]
Sent over the logs several days ago, but I ended up figuring this out – had existing data in the database. Deleted it and it installed properly!

**Comment by andrelopez** [comment]
@angieherrera I really sorry I just checked and for some reason, your email went to spam. Thanks for getting back to us and I'm glad that the issue is solved. Please let me know if you have any other questions
