### ISSUE TITLE
Subscription Plans clearing

### ISSUE THREAD

**Issue by alexjcollins** [enupal/stripe#151]
### Description
We're running into a possible issue where the subscription plans keep clearing.
We noticed this behaviour after assigning plans to our payment forms. Once we had saved and returned to view, sometimes the plan values would be reset to `Select Plan...` with nothing in the dropdown.

Is there something that we need to change in order to stop this happening or does it appear to be an issue?
Note: It doesn't seem to be consistent, sometimes it's fine, other times it does it almost every time you save the form.

[Shot video demonstrating the behaviour](https://cln.sh/r4mrbx)

### Steps to reproduce

1. Refresh Plans in Subscription Plans
2. Visit a payment form and observe the plan showing in the dropdown
3. Save the payment form
4. Review payment form and observe the plans being empty in the Plan dropdown

### Additional info

- Craft version: Craft Pro 3.5.15.1
- PHP version: 7.3.23
- Database driver & version: MySQL 5.5.5
- Plugin version: 3.2.2
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @alexjcollins 
I am unable to recreate this issue so I may need more info to start debugging.

- Do you have the `useProjectConfigFile` setting enabled on your config/general.php file?

- Could you please recreate the issue and send back to us a zip file of the following folder? storage/logs

- Are you able to share your database with us?

Could you please follow up via email? support@enupal.com

**Comment by alexjcollins** [comment]
@andrelopez Thanks for the reply. I've had a play around with this again on production, and it _seems_ to have sorted itself out. I'll close the issue and if it comes back I'll sort you out with all the information you need.
