### ISSUE TITLE
Subscription payments using Stripe Elements

### ISSUE THREAD

**Issue by williamhibberd** [enupal/stripe#153]
### Description

Payments via a SCA Card Stipe Elements form, set up for subscriptions get processed as a One-Time payment and not a subscription.

### Steps to reproduce

1.  <img width="1072" alt="Screenshot 2020-11-25 at 16 57 45" src="https://user-images.githubusercontent.com/1289356/100258781-5aef2800-2f3f-11eb-99ef-e4f4a7545e4b.png">

### Additional info

- Craft version: 3.5.16
- PHP version: 7.3.23
- Database driver & version: MySQL 8.0.22
- Plugin version: 3.2.2
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by williamhibberd** [comment]
Closing this... Turning SCA off makes Stripe Elements work with subscriptions.
I need to learn to read text written in red!

Maybe the docs should include a note saying that with SCA subscriptions only work with Stripe Checkout.

**Comment by williamhibberd** [comment]
Upon further reading, my issue was caused because my subscription has Tiers.
[https://docs.enupal.com/stripe-payments/getting-started/sca.html#stripe-checkout-features](url)

**Comment by andrelopez** [comment]
thanks @williamhibberd we hope to add support for SCA to the card element soon.
