### ISSUE TITLE
Export CSV missing City

### ISSUE THREAD

**Issue by bleepsandblops** [enupal/stripe#155]
### Description
The export data is missing both cities, billing and shipping.
https://github.com/enupal/stripe/blob/f761673604afd776cd853a669ca46a89344e14c7/src/services/Reports.php

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugin version:
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by andrelopez** [comment]
Hi @bleepsandblops We just released Stripe Payments v3.2.3 with a fix to this issue. Thanks for reporting!
