### ISSUE TITLE
Multiple Vendors with Single Set of Products

### ISSUE THREAD

**Issue by idawgik** [enupal/stripe#159]
This is more a pre-sales/howto question.

I have a possible project which would have multiple vendors but only one set of products with Craft Commerce. 

Is it possible with the vendor/stripe connect integration to tell which vendor an order should be applied to when only using one set of products? We would prefer not to have to duplicate each of the products every time a new vendor is added. Customers would only be ordering from one vendor at a time.

Or if you have multiple vendors assigned to a product, does it just payout to ALL linked vendors on an order.

Thank you for your help.

**Comment by andrelopez** [comment]
Hi @idawgik , sorry for the late reply. Yes if you have multiple vendors attached to a product it will pay to all the vendors attached to the product.
