### ISSUE TITLE
Line items and entry id's

### ISSUE THREAD

**Issue by mark-chief** [enupal/stripe#160]
### Description
Not a bug, just looking for some assistance to get me going please. I have a couple of questions so I have split it out.

**Question 1:**
I am attempting to add line items to a one time payment form. Each line item is an entry. 
How can I build the below array from an entry for loop so i can pass it to the options like so: 
`{% set options = { lineItems : lineItems} %}`

I appreciate it's more of a twig templating query but ANY pointers would help me and be much appreciated.
```
lineItems : [
{
name : 'Entry 1',
description : 'entry id 1 here',
amount : 18500,
currency : 'gbp',
quantity : 1,
},
{
name : 'Entry 2',
description : 'entry id 2 here',
amount : 18500,
currency : 'gbp',
quantity : 1,
}   
] 
```

**Question 2:**
The reason for above is that I need to be able to pass the entry id's back to craft so I can use them to fetch the entries they have just paid for. If I can send a comma separated list of entry id's that would be fine as I could split it out.

When testing with the manually created line items like above, they go through to Stripe, but I am unable to see them in the Craft CP Orders section. See below.

<img width="992" alt="Screenshot 2021-01-10 at 12 51 37" src="https://user-images.githubusercontent.com/18699249/104123338-9785b000-5342-11eb-8130-b1cda24e517c.png">

Thanks again, any direction or help would be appreciated. I'm nearly there with this.

If you would suggest doing this a better way, I am open to suggestions. I just need the entry Id's available in their order and so I can say, hey you've paid for Entries x,y,z in the template.

- Craft version: 2.5.17.1
- Plugin version: 3.2.3
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: YES

**Comment by andrelopez** [comment]
Hi @mark-chief 

Please edit your payment form to add a hidden field that outputs a variable let's call it `entries` (please choose the name that you want)

![Hidden Field](https://enupal.com/assets/docs/hidden-field-stripe-payments.png)

Then on your template create the `entries` variable with the separate comma ids and pass it to Stripe Payments

```twig
{# ADD THE ENTY IDS HERE #}
{% set entries = '1,2,3' %}
{% do craft.enupalStripe.addVariables({ entries: entries }) %}

{% set lineItems = [
        {
            name : 'Entry 1',
            description : 'entry id 1 here',
            amount : 18500,
            currency : 'gbp',
            quantity : 1,
        },
        {
            name : 'Entry 2',
            description : 'entry id 2 here',
            amount : 18500,
            currency : 'gbp',
            quantity : 1,
        }
    ]
%}
{% set options = { lineItems : lineItems} %}
{{ craft.enupalstripe.paymentForm('handle', options) }}
```

Please let me know if that works.

**Comment by mark-chief** [comment]
Hello Andre thanks for your help. So far that works.

Could you please help with the below? Hopefulyl you can see what i am trying to achieve:

```
{% set options = {
lineItems : [
        {% for entry in entries %}
            {
            name : '{{ entry.title }}',
            description : {{ entry.desc }}',
            amount : 18500,
            currency : 'gbp',
            quantity : 1,
            }
        {% endfor %}
] 
} %}
```

Thanks!

**Comment by andrelopez** [comment]
@mark-chief here you go:

```twig
{% set lineItems = [] %}

{% for entry in entries %}
        {% set lineItems = lineItems|merge([{
            name : entry.title,
            description : entry. desc,
            amount : 18500,
            currency : 'eur',
            quantity : 1
        }]) %}
 {% endfor %}

{% set options = {
 lineItems: lineItems
} %}

{{ craft.enupalstripe.paymentForm('handle', options) }}
```

Please let me know how it goes

**Comment by mark-chief** [comment]
Hey Andre, thats fantastic, thank you very much for your help.

Should the Line items be visible in the Craft CP? I cant see them.

**Comment by mark-chief** [comment]
Hi @andrelopez, Appreciate this may be outside of the support of the plugin, but am looking for some assistance please?

I pass multiple entry id's to a payment form field e.g: `5637,6859,4563`. I want to update a custom field in those entries when order is complete, so i am attempting to make a module (first time)

```
use enupal\stripe\services\Orders;
use enupal\stripe\events\OrderCompleteEvent;
use enupal\stripe\Stripe;
use craft\base\Plugin;
use Craft;

class YourPlugin extends Plugin
{
    public function init()
    {
        ...
        ...
         Event::on(Orders::class, Orders::EVENT_AFTER_ORDER_COMPLETE, function(OrderCompleteEvent $e) {
             $order = $e->order;
            $fields= $order->getFormFields();
            $entryIds = $fields['handle'] ?? null;  // e.g. 3390,3435
           //get the entries from $entryIds and update a custom field -> save
         });
        ...
        ...        
     }
}  
```

Thanks

How can I update those entries?

**Comment by mark-chief** [comment]
@andrelopez This is how I got it working and for anyone else that comes across this. 

Please suggest or optimise it if you feel it could be better:

```        Event::on(Orders::class, Orders::EVENT_AFTER_ORDER_COMPLETE, function(OrderCompleteEvent $e) {
	        
			$order = $e->order;
			$fields= $order->getFormFields();
			$entryIds = explode(',', $fields['Entry_IDs_internal_use']);
			$entries = Entry::find()->id($entryIds)->all();
			foreach ($entries as $entry) {
				$entry->setFieldValue('entryStatus', 'paid');
				Craft::$app->elements->saveElement($entry);
			}
             
         });
```

**Comment by andrelopez** [comment]
@mark-chief Onward! thanks for sharing!
