### ISSUE TITLE
Customer Portal Error

### ISSUE THREAD

**Issue by mark-chief** [enupal/stripe#161]
### Description
Using the below example from the docs, I am getting "HTTP 400 – Bad Request – yii\web\BadRequestHttpException" - "Post request required".

```
{% if currentUser %}
    <form method="POST" action="/enupal-stripe/customer-portal">
        {{ csrfInput() }}
        <input type="hidden" name="returnUrl" value="{{ siteUrl('/account') }}">
        <button type="submit">Manage billing</button>
    </form>
{% endif %}
```

- Production domain with SSL
- Test Mode enabled / tried also with live - same result
- User has 1 completed order. Can see this order in Stripe and Craft CP
- No caching enabled on the page

Thanks!!!!

### Additional info

- Craft version: 3.5.17
- Plugin version: 3.2.3
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: YES

**Comment by andrelopez** [comment]
Hi @mark-chief could you please try the following code:

```twig
{% if currentUser %}
    <form method="POST">
        {{ csrfInput() }}
        {{ actionInput('enupal-stripe/customer-portal) }}
        <input type="hidden" name="returnUrl" value="{{ siteUrl('/account') }}">
        <button type="submit">Manage billing</button>
    </form>
{% endif %}
```
Please let me know how it goes

**Comment by mark-chief** [comment]
I am now getting this:

Page not found.
↵
Caused by: Invalid Route – yii\base\InvalidRouteException
Unable to resolve the request "enupal-stripe/customer-portal".

**Comment by andrelopez** [comment]
Could you please try 

```twig

{% if currentUser %}
    <form method="POST">
        {{ csrfInput() }}
        {{ actionInput('enupal-stripe/stripe/create-customer-portal') }}
        <input type="hidden" name="returnUrl" value="{{ siteUrl('/account') }}">
        <button type="submit">Manage billing</button>
    </form>
{% endif %}
```

**Comment by mark-chief** [comment]
Hi @andrelopez , that seems to reload the page only.

**Comment by andrelopez** [comment]
Hi @mark-chief could you please confirm that you're logged in as a user that has made a purchase?

**Comment by mark-chief** [comment]
@andrelopez yes the user is logged in. See screenshot.
![Screenshot 2021-01-13 at 09 39 35](https://user-images.githubusercontent.com/18699249/104434615-54fee600-5583-11eb-85a9-59be1bc44c27.png)
Thanks

**Comment by andrelopez** [comment]
Hi @mark-chief we had a user with the same issue as you, could you please read this thread? https://github.com/enupal/stripe/issues/133

Are you on local development? what is your site URL?

**Comment by mark-chief** [comment]
Hi @andrelopez, yes I have seen that thread already. 

It is on a production domain, not local development. Stripe is in test mode, but have also tried in live mode with no success.

**Comment by mark-chief** [comment]
@andrelopez Hi, it is working with your suggested `{{ actionInput('enupal-stripe/stripe/create-customer-portal') }}`, the problem was I had not completed the terms and conditions field in the Stripe control panel!! Apologies I should have spotted that.

However, the billing history is empty, even though I can see lots of orders from my tests in the payment section. Do you know it it will show one time orders?

![Screenshot 2021-01-14 at 08 05 34](https://user-images.githubusercontent.com/18699249/104561420-4970f500-563f-11eb-80f4-fddf4a620f62.png)

**Comment by andrelopez** [comment]
@mark-chief Great! I'll add that to the docs. Sorry, the View billing history feature is only for subscriptions

**Comment by mark-chief** [comment]
@andrelopez Does your PDF plugin support PDF invoices for One Time Orders?

**Comment by andrelopez** [comment]
@mark-chief Yes it is. Here is the docs link: https://docs.enupal.com/stripe-payments/orders/order-pdf.html#install-enupal-snapshot Please let me know if you have any questions
