### ISSUE TITLE
XSS Vulnerability in dependency

### ISSUE THREAD

**Issue by fantasticmachine** [enupal/stripe#162]
I've received a report (via Craft Report) that phpoffice/phpspreadsheet (1.15.0) contains a potential XSS vulnerability.

Looking at the repo for that project it appears to have been resolved and merged https://github.com/PHPOffice/PhpSpreadsheet/pull/1719

Can the dependency version be bumped to use the fixed version?

**Comment by andrelopez** [comment]
Hi @fantasticmachine thanks for reporting this issue. We just released Stripe Payments v3.3.0 with a fix to this issue.
