### ISSUE TITLE
Old jquery.min.js file included in vendor/js - can this can be deleted?

### ISSUE THREAD

**Issue by kerrig** [enupal/stripe#166]
### Description
Client ran a security scan and found this file:
_we have to resolve this security issue: "The detected version of jQuery (version v1.11.1) is out of date and no longer receiving patches."_

Is it possible to get this file removed from the repo if my assumption is correct that it's no longer needed?
https://github.com/enupal/stripe/blob/master/src/resources/vendor/js/jquery.min.js

**Comment by andrelopez** [comment]
Hi @kerrig we just released Stripe Payments v3.3.1 with a fix to this issue.
