### ISSUE TITLE
You may only specify one of these parameters: submit_type, subscription_data.

### ISSUE THREAD

**Issue by Coysh** [enupal/stripe#167]
### Description
Getting an error on the lates update to 3.3.0
`2021-02-13 15:54:57 [-][1][-][error][Stripe\Exception\InvalidRequestException] (Status 400) (Request req_VivIWv5epWXIHl) You may only specify one of these parameters: submit_type, subscription_data.`

### Additional info

- Craft version: Latest
- PHP version: 7 .4
- Database driver & version: mySQL
- Plugin version: 3.3.0
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: YES

**Comment by Coysh** [comment]
Hi @andrelopez this is still an issue for me. I'm not committing to purchase this yet, as can't demo to client

**Comment by andrelopez** [comment]
@Coysh sorry the slow response. Could you please send us a screenshot of your payment form setup on your CP to try to recreate this issue? Please send the info to support@enupal.com

**Comment by Coysh** [comment]
@andrelopez - sent via email. Nothing massively different from default settings in the payment form though.

**Comment by andrelopez** [comment]
@Coysh We just released Stripe Payments v3.3.2 with a fix to this issue. Sorry for the slow response
