### ISSUE TITLE
Subscription Grants remove users from existing groups

### ISSUE THREAD

**Issue by steverowling** [enupal/stripe#169]
### Description

Create a Subscription Grant to add a subscriber to a new group, e.g. 'subscribers'.

When the user successfully purchases a subscription, they are added to the 'subscribers' group, but they are also removed from any other user groups that they previously belonged to.

Since Craft allows for users to belong to multiple user groups and user group permissions are additive, I think this behaviour is a bug.

### Steps to reproduce

1. Follow the instructions to create a Subscription Grant to assign the subscriber to a 'subscribers' user group: https://docs.enupal.com/stripe-payments/stripe-payment-forms/subscription-grants.html
2. Assign a user to a generic 'member' user group
3. The user then purchases a subscription
4. Following the successful purchase, the user is now only in the 'subscribers' user group and has lost their membership of the 'members' user group.

### Additional info

- Craft version: Craft CMS 3.5.17.1
- PHP version: 7.1.33
- Database driver & version: MySQL 5.7.32
- Plugin version: 3.2.3
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by andrelopez** [comment]
Hi @steverowling We just released Stripe Payments v3.3.1 with a fix to this issue. Thanks for reporting!
