### ISSUE TITLE
removeDefaultItem not working

### ISSUE THREAD

**Issue by beckbailey** [enupal/stripe#174]
### Description

removeDefaultItem setting not working on line items

### Steps to reproduce

Despite following the documentation and setting this to true, the default plan is still passed to the Stripe Checkout form.

<img width="696" alt="Screenshot_26" src="https://user-images.githubusercontent.com/1824287/109220061-765c1000-7786-11eb-810f-176a94e1027e.png">
<img width="595" alt="Screenshot_27" src="https://user-images.githubusercontent.com/1824287/109220085-7d831e00-7786-11eb-8ec0-187f8a835237.png">

### Additional info

Craft 3.5.12.1
PHP 7.0.30
MySQL 5.6.17
Stripe Payments 3.2.3
SCA & Stripe Checkout ENABLED

**Comment by andrelopez** [comment]
Hi @beckbailey I was unable to recreate this issue, could you please try again with the latest version?

```twig
{% set options = {
                    removeDefaultItem: true,
                    lineItems : [
                        {
                            name : 'T-shirt',
                            description : 'Comfortable cotton t-shirt',
                            amount : 1500,
                            currency : 'usd',
                            quantity : 2,
                        },
                        {
                            name : 'Hidden fee :)',
                            description : 'There is always a fee',
                            amount : 100,
                            currency : 'usd',
                            quantity : 1,
                        }
                    ]
                }
                %}
                {{ craft.enupalStripe.paymentForm('paymentForm1', options) }}
```
