### ISSUE TITLE
Error after payment form submission

### ISSUE THREAD

**Issue by bfjare** [enupal/stripe#185]
Worked this down to this basic template for testing

```
<html>
	<head>
		<title>Test</title>
	</head>
	<body>
		{{ craft.enupalstripe.paymentForm('socialEquityConfStudent') }}
	</body>
</html>
```

Getting the following error after submission. The submission is successful but it throws this error.

<img width="1481" alt="Screen Shot 2021-04-28 at 1 00 36 PM" src="https://user-images.githubusercontent.com/11744681/116458317-be98bc80-a821-11eb-8d4a-106918421465.png">

If I refresh the page it loads correctly.

CRAFT CMS: 3.6.12
Stripe Payments: 3.3.3

**Comment by andrelopez** [comment]
Hi @bfjare  Could you please let us know if you have SCA enabled and Stripe Checkout?

**Comment by bfjare** [comment]
I do not have SCA enabled  stripe checkout is enabled

**Comment by bfjare** [comment]
If I turn on SCA the payment works but its not saved to the database

**Comment by andrelopez** [comment]
Hi @bfjare After enable [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) if you want to test locally (as the webhook URL needs to be accessible via internet) please install the [Stripe CLI](https://stripe.com/docs/stripe-cli) to redirect the webhook calls required to your local webiste

Please run the following two commands, replace `your-local-website` with your local URL

```
stripe login
stripe listen --forward-to http://your-local-website/enupal/stripe-payments
```
And then test to process a payment again, you will see that webhooks will be redirected to your website and the order will be saved in the database. Let me know how it goes

**Comment by bfjare** [comment]
Thank you Andre I will do this today.  Will I need to do this on production as well?

**Comment by andrelopez** [comment]
@bfjare No, the stripe cli is only for local development. However, you need to make sure to read the SCA instructions [here](https://docs.enupal.com/stripe-payments/getting-started/sca.html#enable-the-new-stripe-checkout) and when you're ready to deploy on production you need to make sure to add the webhook URL on your Stripe dashboard and enable our recommended events, all the info [here](https://docs.enupal.com/stripe-payments/stripe-payment-forms/webhook.html) please let me know how it goes

**Comment by bfjare** [comment]
Issue resolved with having the webhook for production saved in the wrong place on stripe
