### ISSUE TITLE
Logging broken? If not, what are logging best practices?

### ISSUE THREAD

**Issue by zackspear** [enupal/stripe#189]
### Description

Perhaps I'm missing something but I've been having a tough go with logging when using this plugin locally and on my staging server in preparation to soon go live.

I use a custom Craft module to watch order events and modify order meta fields based on the response of a HTTP request I send to an outside server with order details.

I've had this module in place for a few years now watching Craft Commerce orders and have always been able to log using the built in Craft methods without any issues.

When attempting to log with Craft's built in logging methods and or PHP's `error_log` within [Stripe Payment's events](https://docs.enupal.com/stripe-payments/plugin-development/events.html#afterordercomplete) they don't show up anywhere that I can find.
```
Craft::trace()
Craft::info()
Craft::warning()
Craft::error()
```

I check the Yii Debug console. Checked `storage/logs`. But don't see anything.

I've resorted to using https://github.com/putyourlightson/craft-log-to-file which has been helpful but it seems to only log when everything goes good. If there's errors with any Stripe Payments event they seem to be swallowed and aren't logged anywhere that I can find.

While I was successfully able to refactor my custom module to handle Stripe Payment orders I'm concerned about being able to trace back potential order errors once we go live.

We're expanding our payment options from what we have with Craft Commerce to include Alipay to easily allow our Chinese users to buy our product. So being able to trace errors for potential errors from Chinese users will be crucial as communication will be much more difficult. So we must be able to rely on logs.

### Steps to reproduce

```php
Event::on(
  Orders::class,
  Orders::EVENT_AFTER_ORDER_COMPLETE,
  function(OrderCompleteEvent $e) {
      $order = $e->order;
      Craft::trace($order, __METHOD__);
  }
);
```

### Additional info
- PHP version 7.4.16
- MySQL 5.5.5
- Craft Pro 3.6.12
- Plugin version:
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: yes

**Comment by andrelopez** [comment]
@zackspear interested issue, I'll take look and back to you soon

**Comment by andrelopez** [comment]
Hi @zackspear  I was able to use all the logging methods. Please feel free to share your thoughts on this, closing this one for now
