### ISSUE TITLE
Spam orders showing as successful

### ISSUE THREAD

**Issue by siebird** [enupal/stripe#191]
Hey, Andre. 

I just DM'd you a video in Discord showing you what is going on. It seems to have been a one time targeted attack as it as of now.

**Comment by andrelopez** [comment]
Hi @siebird followed up via discord

**Comment by thijskaspers** [comment]
Hi @andrelopez, can you remember what was causing this? We are currently having the same issue. We have 1000 spam orders with 1 cent value that are marked as 'payment successful' in the CP.

**Comment by andrelopez** [comment]
Hi @thijskaspers We recommend enabling `liveWebhookSigningSecret` on your config settings [docs here](https://docs.enupal.com/stripe-payments/getting-started/saving-your-stripe-api-keys.html#saving-the-stripe-api-keys-via-config-file)
 
 More info here https://stripe.com/docs/webhooks/signatures)

**Comment by thijskaspers** [comment]
> Hi @thijskaspers We recommend enabling `liveWebhookSigningSecret` on your config settings [docs here](https://docs.enupal.com/stripe-payments/getting-started/saving-your-stripe-api-keys.html#saving-the-stripe-api-keys-via-config-file)
> 
> More info here https://stripe.com/docs/webhooks#secure-webhook

Thanks for the reply Andre. We actually have the `liveWebhookSigningSecret` enabled in our config file. Do we need to do something after that to validate the secret somewhere, or should the plugin do this?

**Comment by thijskaspers** [comment]
I'm wondering by the way if the "Refund" button is secure? What if someone is able to do fake payments, and gets access to the CMS somehow and clicks on Refund... will Stripe wire them money they haven't paid? The spam payments we received are $25.000+ so they managed to update the price as well. Just asking to be sure, worst case scenario, but better safe than sorry.
