### ISSUE TITLE
Sync Subs Order Date Range Broken?

### ISSUE THREAD

**Issue by theskyfloor** [enupal/stripe#193]
### Description

I can't seem to get the sync for subs to work based on date range. Is there a minimum required API version? Besides that sync is still working great!

### Steps to reproduce

1. Try to sync
2. Stripe error logs report invalid date param.

### Additional info

- Craft version: All up to date
- PHP version: 7.4
- Database driver & version:
- Plugin version: All up to date
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by theskyfloor** [comment]
Wanted to update that the range is broken but the sync still worked beautifully and processed many old records in batches with no errors!

**Comment by andrelopez** [comment]
Hi @theskyfloor We just released Stripe Payments v3.3.6 with a fix to this issue. Please update your plugin and let us know how it goes.

**Comment by theskyfloor** [comment]
Thanks!
