### ISSUE TITLE
Add ability to adjust the commission on the fly

### ISSUE THREAD

**Issue by codyjames** [enupal/stripe#195]
### Description
We're not able to do a percentage-based commission for our vendors. Instead, it'll be a mix of a flat fee + a percentage. So, I either need an event to hook into to adjust the commission amount, or I need to be able to disable this event (https://github.com/enupal/stripe/blob/04b5874b316f92d212cdeffaf141e2a38af7a05b/src/Stripe.php#L108) so that I can create the commission myself.

**Comment by codyjames** [comment]
Also, I see that commissions are currently related to items rather than an order. I'm wondering how we'd go about making sure the Vendor gets the shipping amount transferred to them. Or, does the plugin already handle that?

**Comment by codyjames** [comment]
@andrelopez Do you think this is something y'all would add sometime soonish? No worries if not, I just need to pick a direction soon if this isn't something y'all will add.

**Comment by andrelopez** [comment]
Hi @codyjames We just released Stripe Payments v3.3.5 with support to the [beforeProcessTransfer](https://docs.enupal.com/stripe-payments/plugin-development/events.html#afterprocesswebhook) event so you can adjust the `$commission->totalPrice` as needed. Please let me know if that could work.
