### ISSUE TITLE
Random duplicate orders

### ISSUE THREAD

**Issue by bfjare** [enupal/stripe#196]
We recently ran the sync command a few days ago to grab some orders that were missing with an earlier issue. Now random duplicate orders are appearing in the control panel.  We are checking back in stripe and the customer only has one payment but now in the control panel, they have several duplicates over different days.  Not sure what's causing this or even how to debug it.

**Comment by bfjare** [comment]
<img width="1840" alt="Screen Shot 2021-06-10 at 10 14 53 AM" src="https://user-images.githubusercontent.com/11744681/121560417-b7de9700-c9d4-11eb-9247-2b15080553c8.png">

**Comment by bfjare** [comment]
<img width="1212" alt="Screen Shot 2021-06-10 at 10 16 57 AM" src="https://user-images.githubusercontent.com/11744681/121560688-fffdb980-c9d4-11eb-8c88-fa3874ab0944.png">
For example this is one user that has only one order in stripe

**Comment by zackspear** [comment]
This is an issue for our integration as well. Was even reported back in March…https://github.com/enupal/stripe/issues/180
And there's been no visible movement on it in months. No bueno.

**Comment by andrelopez** [comment]
Hi @zackspear could you please give me more info about your issues? is this happening on One-Time or Subscriptions sync?
is the Stripe ID the same on duplicated orders?

I have pinned this issue to high priority

**Comment by andrelopez** [comment]
Hi @bfjare We just released Stripe Payments 3.3.10 with a fix to this issue. Please let us know how it goes

**Comment by zackspear** [comment]
@andrelopez, thanks for taking time on this. Unfortunately after updating to `3.3.10` I'm still seeing duplicates.

All our orders are one-time orders. Stripe IDs are the same for the duplicates. I'm not running a manual sync. These duplicates are happening automatically.

Please let me know if I need provide more information.

**Comment by andrelopez** [comment]
@zackspear could you please follow up via support@enupal.com?

**Comment by bfjare** [comment]
Did you find anything on this?

**Comment by zackspear** [comment]
@bfjare, I corresponded with Andre a little bit via email last week. After providing limited permissions to only Stripe Payments in our Craft dashboard so he could take a look at our duplicates I've yet to hear back. So hopefully bug fixes are under active development.

**Comment by bfjare** [comment]
thanks @zackspear

**Comment by andrelopez** [comment]
Hi @bfjare @zackspear Thanks for following up, we just released Stripe Payments v3.3.11 with a fix to this issue. Please let me know how it goes after the update
