### ISSUE TITLE
404 - Unable to process the Payment

### ISSUE THREAD

**Issue by iwe-hi** [enupal/stripe#197]
### Description
An Error 404 occurs on submit. 

![image](https://user-images.githubusercontent.com/78907655/122949332-dbfa8a80-d37b-11eb-8c13-cecff52b75b2.png)

The form data of the request: 
![image](https://user-images.githubusercontent.com/78907655/122950084-78249180-d37c-11eb-8ba6-e78fafbf1f94.png)

It doesn't matter where the from is integrated, the result is the same. It gets integrated like this: 
{{ craft.enupalStripe.paymentForm("translate") }}

The markup:
![image](https://user-images.githubusercontent.com/78907655/122950774-04cf4f80-d37d-11eb-86a8-99cb575e09f6.png)

It seems neither Jquery or the css files are getting loaded. The form looks like this in the frontend: 
![image](https://user-images.githubusercontent.com/78907655/122951963-f897c200-d37d-11eb-8bb5-5500e0e21d9d.png)

### Steps to reproduce

1. Create a New Payment Form
2. Include it in a template
3. Click on Submit

### Additional info

- Craft version: 3.6.17
- PHP version: 7.3.24
- Database driver & version: mysql, 5.7.32
- Plugin version: 3.3.3
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Both are enabled

**Comment by andrelopez** [comment]
Hi @iwe-hi Yes this looks like an issue with Javascript, on Chrome, could you please click Settings -> More tools -> Developer tools and click on the `console` tab and refresh the page, if there is any errors could you please take a screenshot and paste it here?

**Comment by iwe-hi** [comment]
Hey @andrelopez Here are the sceenshots on page load:
![image](https://user-images.githubusercontent.com/78907655/123045524-50284300-d3fb-11eb-8757-ad6d5f816d5b.png)

And on submit:
![image](https://user-images.githubusercontent.com/78907655/123045594-6209e600-d3fb-11eb-8bed-e616b17c296c.png)

Thank you for your help!

**Comment by andrelopez** [comment]
@iwe-hi thanks for following up. What about the network tab, could you please send a screenshot after you refresh the page?

**Comment by iwe-hi** [comment]
![image](https://user-images.githubusercontent.com/78907655/123046647-a34ec580-d3fc-11eb-9e5b-3dd16c8718da.png)

**Comment by siebird** [comment]
We're getting the same issue with `3.3.3`

**Comment by clarknelson** [comment]
Any success dealing with this issue?

**Comment by andrelopez** [comment]
@iwe-hi  Sorry, I am unable to recreate this issue. Could you please try to disable `Load JQuery` and `Load CSS` settings under Settings -> Defaults ?


@clarknelson is this error happening on a clean installation?

**Comment by iwe-hi** [comment]
Closed - we're using a php API to make payments.
