### ISSUE TITLE
craft.enupalstripe.paymentForms.all()

### ISSUE THREAD

**Issue by bfjare** [enupal/stripe#199]
I have two forms in the control panel but this code renders the "Impossible to invoke a method ("all") on a null variable." error

{% for stripeForm in craft.enupalstripe.paymentForms.all() %}
	{{ stripeForm.paymentForm() }}
{% endfor %}

**Comment by andrelopez** [comment]
Hi @bfjare  Could you please try the following code?

```twig
{% for stripeForm in craft.enupalstripe.paymentForms().all() %}
    {{ stripeForm.paymentForm() }}
{% endfor %}
```
