### ISSUE TITLE
Display both billing and shipping address when Stripe Checkout is disabled

### ISSUE THREAD

**Issue by intoeetive** [enupal/stripe#20]
### Description
If Stripe Checkout is not enabled for the form, only one set of address fields shows up, even though I have both Shipping and Billing selected. I need to have both addresses, and don't use Stripe popup.

Notify

- [ ] [373017217](https://app.drift.com/inboxes/63412/conversations/373017217)

### Additional info

- Craft version: 3.0.35
- Plugin version: 1.6.8

**Comment by andrelopez** [comment]
Thanks @intoeetive I have pinned this issue

**Comment by andrelopez** [comment]
Hi @intoeetive 

We just released Stripe Payments v1.8.0 and added support to display both addresses for when using Stripe Elements.

Best,
