### ISSUE TITLE
Front End Vendor Forms Auto Disabled

### ISSUE THREAD

**Issue by bfjare** [enupal/stripe#200]
Whenever a vendor creates a front-end connected form it's always disabled even if I add one of the following inputs to the form.

<input type="text" name="fields[enabled]" value="true">

**Comment by andrelopez** [comment]
Hi @bfjare Do you enable `Skip admin review` when editing the vendor on the CP?

**Comment by bfjare** [comment]
I have not

**Comment by andrelopez** [comment]
@bfjare no problem :) closing the ticket, let me know if you have any other issues
