### ISSUE TITLE
Can't upload or edit Payment Form

### ISSUE THREAD

**Issue by jomotion11** [enupal/stripe#207]
Having trouble with payment form. It won't let me create new or edit forms. I get the error "Payment Form not found" or "Key "0" does not exist as the array is empty", which is odd because a form does exist.

### Additional info

- Craft CMS 3.6.7:
- PHP version 7.3:
- Plugin version 3.3.5:

**Comment by andrelopez** [comment]
Hi @jomotion11 could you please recreate the issue and send back to us a zip file of the following folder? storage/logs

Please send the file to support@enupal.com

**Comment by shifuma** [comment]
I'm also getting this. Works fine locally, but on my staging site I'm getting `Key "0" does not exist as the array is empty.` when I create a new form. Going back to All Forms shows it was actually created, but trying to edit gives the same error.

**Comment by shifuma** [comment]
Very odd by after setting the staging environment to `production` (and thus disabling `allowAdminChanges` I no longer get the error.

**Comment by andrelopez** [comment]
Possible related to https://github.com/enupal/stripe/issues/356 moving discussion to that ticket
