### ISSUE TITLE
Support for Stripe coupon codes

### ISSUE THREAD

**Issue by intoeetive** [enupal/stripe#21]
I have submitted `couponCode` field together with form using coupon as set up in Stripe. 
However it does not seem like the coupon came though.

Unless I'm doing something wrong, please accept using Stripe coupons as feature request

**Comment by andrelopez** [comment]
We already have this feature on our list and will be added very soon!

**Comment by theskyfloor** [comment]
Any update on this functionality?

**Comment by andrelopez** [comment]
Added on v1.9.0
