### ISSUE TITLE
Multiple products

### ISSUE THREAD

**Issue by mark-chief** [enupal/stripe#210]
### Description
Hello. Is it possible to have multiple products on one page but pay through a single payment. 

E.g:

Product 1:
number of tickets qty 1-9 £215 each
-select qty-

Product 2: 
Table of ten £2150
-select qty-

Customer can select different qty of either products above and pay through one form. 

Do I need a payment form for each product?

thanks, any help would be appreciated. 

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugin version:
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by andrelopez** [comment]
Hi @mark-chief Yes, if you're using [Stripe Checkout](https://docs.enupal.com/stripe-payments/getting-started/sca.html#enable-the-new-stripe-checkout) you can use the `lineItems` key via `options`, you can imagine like a two step checkout page, and imagine this will be the final checkout page, you need to pass the items information previously collected (it could be via GET params or Session variables)  More info [here](https://docs.enupal.com/stripe-payments/templating/paymentform.html#custom-line-items)

`notice that the amounts should be on cents`

```twig
{% set options = {
        removeDefaultItem: true,    
        lineItems : [
            {
                name : 'T-shirt',
                description : 'Comfortable cotton t-shirt',
                amount : 1500,
                currency : 'usd',
                quantity : 2,
            },
            {
                name : 'Hidden fee :)',
                description : 'There is always a fee',
                amount : 100,
                currency : 'usd',
                quantity : 1,
            }   
        ] 
    } 
%}
{{ craft.enupalStripe.paymentForm('handle', options) }}
```




![Screenshot 2021-08-11 at 7 38 50 pm](https://user-images.githubusercontent.com/875476/129084681-10b8df35-e5a3-4bdf-9016-4fd7521dca29.png)
