### ISSUE TITLE
Error "Template not found: pay-fees/enupal/stripe/create-checkout-session" when SCA enabled - SCA

### ISSUE THREAD

**Issue by hassanmah** [enupal/stripe#213]
### Description
Hi,

I get this JS error when I try to submit the form with SCA. I followed all the steps, including setting up the Webhook. No custom template is use.

### Steps to reproduce

1. Submit form, nothing happens and response is 404 and the above error message.

### Additional info

- Craft version: 3.7.11
- PHP version: 7.3
- Database driver & version: SQL
- Plugin version: 3.3.5
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
@hassanmah could you please refresh the page and send me the source code generated by the browser to support@enupal.com ?

**Comment by hassanmah** [comment]
@andrelopez sent both source file, also you can test the form at https://www.chigwell-school.org/pay-fees/

**Comment by andrelopez** [comment]
Hi @hassanmah We just released Stripe Payments v3.3.6 with a fix to this issue. Please update your plugin and let us know how it goes.

**Comment by hassanmah** [comment]
Hi @andrelopez I'm still getting the same issue with this here https://www.chigwell-school.org/pay-fees/ with SCA switched on.

I've had to switch it off for now

**Comment by hassanmah** [comment]
We can also set up a new form on a new page https://www.chigwell-school.org/fee-payment/ and now getting same error but different url 

<img width="833" alt="image" src="https://user-images.githubusercontent.com/3025707/132819086-b37325ba-566a-4b6d-a64c-7ebdcbb37a42.png">

**Comment by andrelopez** [comment]
@hassanmah The issue is related to the last  `/` at the end of the URL. Could you please test with https://www.chigwell-school.org/fee-payment

**Comment by hassanmah** [comment]
@andrelopez That worked

Thanks

PS. I've emailed you regarding a point.

**Comment by MattWilcox** [comment]
We are seeing this error also, using 3.3.6 on Craft 3.7.12

We get the error regardless of whether the product URL has a slash at the end or not.
