### ISSUE TITLE
No option to pay with Google pay and Apple pay even though it says it's possible in plugin documentation

### ISSUE THREAD

**Issue by dbrown199747** [enupal/stripe#216]
### Description
We downloaded this plugin as it was one of the only stripe plugins for craft that supports Google pay and Apple pay. After downloading, we've noticed there is no setting or option to enable this in the CMS?

I expect it must be something i've missed. Please could you explain to me what I need to do?

### Steps to reproduce

1. 
2.

### Additional info

- Craft version: Craft Solo 3.7.11
- PHP version: 7.4.12
- Database driver & version: MySQL 5.7.32
- Plugin version: 3.3.5
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @dbrown199747 No additional configuration is required to use Google pay and Apple pay with Stripe Checkout. 

**_To test Google Pay:_**
- You need to previously save a card on your browser (Chrome)

**_To test Apple Pay:_**
- You need to previously save a card on your browser (Safari)

Please let me know if that works
