### ISSUE TITLE
When SCA is enabled, this is not working.

### ISSUE THREAD

**Issue by MattWilcox** [enupal/stripe#217]
### Description

There's a closed Issue with the exact problem, but this issue is still happening. We have had to disable SCA in order to get a clients website to take payments again.

https://github.com/enupal/stripe/issues/213

Calling code:

```
{% set options = {
	amount: vatAmount,
	quantity: 1,
	calculateFinalAmount: false,
	itemName : entry.title,
	itemDescription : entry.sku,
	checkoutCancelUrl: entry.url
} %}
{% do craft.enupalStripe.addVariables({ entry: entry }) %}

{{ craft.enupalstripe.paymentForm('productForm1', options) }}
```

URL on which the form is, and where we are when the "buy" button is clicked:
http://mcs19.website.local/products/emc-field-strength-solutions/safety-monitors/fieldsense-2-0

The log in the Console when clicking that button (which does nothing at all as far as the user is concerned):
`http://mcs19.website.local/products/emc-field-strength-solutions/safety-monitors/enupal/stripe/create-checkout-session 400 (Bad Request)`

### Additional info

- Craft version: 3.7.12
- PHP version: 7.2
- Plugin version: 3.3.6
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
@MattWilcox Could you please roll back to Stripe Payments v3.3.5 and check if you have the same error? I want to confirm if this bug was introduced on v3.3.6

**Comment by gazlawn22** [comment]
I've had this issue, it was after doing a few updates in a row, but had rolled back to v3.3.5, and get the same error with the bad request.

PHP: 7.4.13
Craft: 3.7.13
Plugin: 3.3.6
SCA Enabled (broken with yes)

**Comment by MattWilcox** [comment]
@andrelopez - Rolled back on my local machine and re-tested, the bug remains.

![mcs-bug](https://user-images.githubusercontent.com/814039/134878454-bf56c872-8171-46aa-9805-37c94b3e608c.jpg)

**Comment by MattWilcox** [comment]
To anyone else having this issue:

Check if you are running Snaptcha to protect your forms, and if so be sure to add the snaptcha.php config file and populate it with:

`'excludeControllerActions' => ['enupal-stripe/checkout/create-session']`

and maybe even add `'logRejected' => true,` so you can tell when rejections are happening.

So that it's not attempting to block the Stripe JS thinking it's spam.

Thanks for your time and patience with this @andrelopez !

**Comment by iamkeir** [comment]
Just for anyone finding this in future, you may need more exclusions to make Enupal Stripe work:
```
enupal-stripe/checkout/create-session
enupal-stripe/stripe/save-order
enupal/stripe-payments
enupal-stripe/webhook/stripe
enupal-stripe/stripe/cancel-subscription
enupal-stripe/update-billing-info
```

Ref:
https://github.com/enupal/stripe/issues/241
https://github.com/enupal/stripe/issues/225
https://github.com/putyourlightson/craft-snaptcha/issues/23
