### ISSUE TITLE
Where do you specify Stripe webhook's signing secret?

### ISSUE THREAD

**Issue by lesaff** [enupal/stripe#218]
### Description
I checked and double-checked your documentation and couldn't find any info on where to store Stripe's webhook signing secret. Did I miss something obvious here?

### Additional info

- Craft version: 3.7.13
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.x
- Plugin version: 3.3.6
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: yes

**Comment by lesaff** [comment]
@andrelopez I keep getting failed webhook attempt error from Stripe. Any help would be appreciated. Thx.

**Comment by andrelopez** [comment]
Hi @lesaff Thanks for raise this, I'll add support to webhook's signing secret shortly

**Comment by andrelopez** [comment]
Hi @lesaff We just released Stripe Payments v3.3.7 with support for [webhook's signing secret](https://docs.enupal.com/stripe-payments/getting-started/saving-your-stripe-api-keys.html#saving-the-stripe-api-keys-via-config-file)

If you want to test locally please follow the instructions here to use the [Stripe Cli](https://docs.enupal.com/stripe-payments/stripe-payment-forms/webhook.html#test-webhooks-locally)
