### ISSUE TITLE
Pay now button when using SCA doesn't work in Internet Explorer

### ISSUE THREAD

**Issue by dbrown199747** [enupal/stripe#219]
### Description
Pay now button takes user to a 404 page when clicked on.  This only happens in IE, and is fine in all other browsers.

### Steps to reproduce

1. Create stripe form
2. Make sure SCA is turned on (not tested without)
3. When you click on the button that is supposed to take you to 'checkout.stripe.com' to complete the payment, instead you get taken to a 404 page. Is this because it's not supported in IE, or is this an error with the plugin?

Many thanks!

### Additional info

- Craft version: Craft Solo 3.7.13
- PHP version: 7.3.30
- Database driver & version: MySQL 5.5.5
- Plugin version: 3.3.6
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by dbrown199747** [comment]
Hi,

I believe it was IE 11 :)

Many thanks,
Dan

**Comment by andrelopez** [comment]
Hi @dbrown199747 on Stripe Payments Pro you can use the new [`checkout` twig tag](https://docs.enupal.com/stripe-payments/pro/checkout.html) this will generate a link to checkout and should on IE 11.
