### ISSUE TITLE
Subscription form not submitting to Stripe checkout. Console errors showing

### ISSUE THREAD

**Issue by danfathom** [enupal/stripe#225]
### Description

We are having issues with your stripe plugin, where we have got multiple people doing some testing, and quite a few people are getting an issue where the pay now button get's stuck and doesn't go to the stripe checkout. I've added a screenshot of this below, along with the console errors being received. Hopefully this is helpful.

![Screenshot 2021-11-12 at 16 07 56](https://user-images.githubusercontent.com/92588022/141502312-68c7e2c8-b6cc-49dc-8203-696f8a6efdc0.png)

This only happens for us when doing a subscription. We have some variables that define the amount and return URLS. I will post below our subscription settings and options in twig below:

![Screen Shot 2021-11-12 at 16 42 52](https://user-images.githubusercontent.com/92588022/141503024-5d3a9fe1-72b8-4ccf-9a46-ec61f1187b77.png)

{% set type = craft.app.request.getParam('type') %}
{% set amount = craft.app.request.getParam('amount') %}
{% set options = {
            amount: amount,
            calculateFinalAmount: false,
            itemName : "The Seafarers' Charity",
            checkoutSuccessUrl: siteUrl ~ 'donate?submission=successful&ordernumber={number}&form=' ~ type,
            checkoutCancelUrl: siteUrl ~ 'donate?submission=failed'
          } %}
{{ craft.enupalstripe.paymentForm('monthlyDonation', options) }}

As mentioned, for some people it's working perfect, and others it's not working. 

Please let me know if you have any suggestions as to how we can fix this. Unfortunately it has prevented the site going live for the time being until it gets resolved.

### Additional info

- Craft version: Craft Solo 3.7.18.2
- PHP version: 7.4.25
- Database driver & version: MySQL 5.5.5
- Plugin version: 3.3.8
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @danfathom thanks for reaching out. Could you please check all the related templates where you have `{{ craft.enupalstripe.paymentForm('monthlyDonation', options) }}` and make sure that is not inside `{%cache%}` ?

**Comment by danfathom** [comment]
Hi,

Thanks for getting back to me.

There's no caching anywhere on the site. I've just double checked and no cache tags are used anywhere.

Many thanks,
Dan

**Comment by andrelopez** [comment]
Hi @danfathom By any chance you have installed the Snaptcha plugin? if so could you please disable the Snaptcha plugin and try again? I am currently investigating issues caused by that plugin,

**Comment by danfathom** [comment]
Hi,

We don't have Snaptcha installed on the site. We have the following plugins installed:

- Cloner (1.2.2)
- Feed Me (4.4.0)
- Freeform Pro (3.11.12)
- MobileDetect (1.0.2)
- Redactor (2.8.8)
- Redirect Manager (1.1.1)
- Section + Product Type (1.0.5)
- Stripe Payments (3.3.8)
- Super Table (2.6.8)
- Typed Link Field (1.0.25)
- XML Sitemap (1.3.2)

Hope this helps.

Many thanks,
Dan

**Comment by andrelopez** [comment]
Hi @danfathom thanks for following up. Could you please recreate the issue and send back to us a zip file of the following folder?

storage/logs

Please send the file to support@enupal.com

**Comment by danfathom** [comment]
Hi,

No problem, I will attach below a log of it not working for us.

[logs.zip](https://github.com/enupal/stripe/files/7588198/logs.zip)

Many thanks,
Dan

**Comment by danfathom** [comment]
Hi, did you look into the logs and try to resolve this issue? Unfortunately we still have the project on hold until we can get this sorted.

Thanks,
Dan

**Comment by andrelopez** [comment]
Hi @danfathom could you please try to temporally disable `enableCsrfProtection` on your `config/general.php` file and try again? just wanted to confirm that is an error related to the CSRF token

Please temporally add the following to your general.php file:
```php
'enableCsrfProtection' => false
```

**Comment by danfathom** [comment]
I have added that to the config file and it seems to now be working for us.

We haven't got everyone in to test it today, but for the people that have tested it have all reported back saying it's now working. I will get some more of the team testing on Monday, but could well be the issue as it's now working for some people who it didn't previously work for.

Many thanks,
Dan
