### ISSUE TITLE
Keys not retrieved and partially editable in staging / prod

### ISSUE THREAD

**Issue by romainpoirier** [enupal/stripe#229]
### Description
I can access to `/admin/enupal-stripe/settings/general` in staging and prod while `'allowAdminChanges' => $isDev` in both env. I get an `Internal Server Error Server Error` on save. This page should not be shown in a non-editable env.

Furthermore, my env variables config keys are not retrieved from dev to staging and prod on deploy. It's the literal value that is saved, not the value of the variable.

I can't edit the _Live Publishable Key_ and _Live Secret Key_ values in staging / prod because of `allowAdminChanges` setting. 
As the Stripe key is not retrieved, there's a `A server error occurred `error from the Stripe JS button when a payment is triggered.

My settings are set as following the docs:
```
// Dev environment settings
'dev' => [
	'devMode' => true,
	'stripePayments' => [
		'testPublishableKey' => getenv('STRIPE_TEST_PUBLISHABLE_KEY'),
		'testSecretKey' => getenv('STRIPE_TEST_SECRET_KEY'),
		'testMode' => 1
	]
],

// Staging environment settings
'staging' => [
	'stripePayments' => [
		'livePublishableKey' => getenv('STRIPE_STAG_PUBLISHABLE_KEY'),
		'liveSecretKey' => getenv('STRIPE_STAG_SECRET_KEY'),
		'testMode' => 0
	]
],

// Production environment settings
'production' => [
	'stripePayments' => [
		'livePublishableKey' => getenv('STRIPE_PROD_PUBLISHABLE_KEY'),
		'liveSecretKey' => getenv('STRIPE_PROD_SECRET_KEY'),
		'testMode' => 0
	]
],
```

Related issue: [#94 ](https://github.com/enupal/stripe/issues/94)

### Additional info

- Craft version: 3.7.21
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7.23
- Plugin version: 3.3.9
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @romainpoirier either if you have `allowAdminChanges` disabled the stripe keys should be loaded.

Could you please confirm if you can see the green check (Test Publishable Key was successfully loaded from config file) on Stripe Payments -> Settings ->  General?

Could you please recreate the error that you're getting when triggering the payment form on the front-end and send back to us a zip file of the following folder? storage/logs 

Please send the file to support@enupal.com

**Comment by romainpoirier** [comment]
> Hi @romainpoirier either if you have allowAdminChanges disabled the stripe keys should be loaded.
Right, but you should disable the ability to edit this setting if allowAdminChanges is disabled. Currently, we can still try to edit it, and then get the `Internal Server Error Server Error`, which is inappropriate.

> Could you please confirm if you can see the green check (Test Publishable Key was successfully loaded from config file) on Stripe Payments -> Settings -> General?

I'm not sure about which green check you're talking about. Here is a screenshot:
![stripe-settings](https://user-images.githubusercontent.com/4634192/144085435-973fe60c-5f2a-45c0-b725-28400ee39491.png)

> Could you please recreate the error that you're getting when triggering the payment form

It is a JS error, the Stripe redirect just not happened after clicking on the check-out button. I think you can get this error whenever you fill in anything wrong in the `Live Publishable Key` and/or `Live Secret Key` field.

**Comment by andrelopez** [comment]
Hi @romainpoirier  could you please share with us the following file? config/general.php ?

Please send the file or the content to support@enupal.com

**Comment by romainpoirier** [comment]
Done ✅

**Comment by andrelopez** [comment]
The issue was solved by adding the default configuration on `config/general.php` using the `*` key. The stripe keys were added on each environment following our [docs](https://docs.enupal.com/stripe-payments/getting-started/saving-your-stripe-api-keys.html#saving-the-stripe-api-keys-via-config-file) but was ignored until the `*` was added to the `general.php` file

I have opened an issue on Craft CMS to follow up this issue 

https://github.com/craftcms/cms/issues/10255
