### ISSUE TITLE
Error when accessing enupal stripe settings or editing form

### ISSUE THREAD

**Issue by bliswebagency** [enupal/stripe#231]
### Description

When accessing enupal stripe settings or editing form the following error is thrown:

TypeError: Argument 1 passed to craft\web\twig\variables\Cp::field() must be of the type string, null given, called in /.../craft/vendor/twig/twig/src/Extension/CoreExtension.php on line 1511 and defined in /.../craft/vendor/craftcms/cms/src/web/twig/variables/Cp.php:811

The issue seems to be with the null parameter in the call to macro fields().. replacing the null with an empty string ("") in files "/vendor/enupal/stripe/src/templates/settings/general.twig" and "/vendor/enupal/stripe/src/templates/forms/_edit.twig" eliminates the error message, however an official fix would be ideal.

Also on occassion we find that a new payment form is added to the payment form list even though we have not created it.. could it be somehow related to the issue above?

### Steps to reproduce

1. Access enupal stripe settings or edit an existing form
2. An error is thrown

### Additional info

- Craft version: 3.7.24
- PHP version: 7.4.23
- Database driver & version: Mysql 5.7.35
- Plugin version: 3.3.9
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: y

**Comment by romainpoirier** [comment]
Same here using Craft 3.7.24, PHP 7.4.21 & MySQL 5.7.34.

**Comment by shornuk** [comment]
Here to, fresh install.

**Comment by edhebert** [comment]
Same issue, noticed after upgrading to most recent version of Stripe Payments. Previously had no issues.

**Comment by andrelopez** [comment]
Hi, this looks like an issue introduced on Craft 3.7.24 and addressed on the latest version, could you please update craft to the latest? currently `3.7.25.1` please let me know if that fixed the issue

**Comment by romainpoirier** [comment]
I can confirm that using the latest Craft CMS version (3.7.25.1) I can't replicate the error. Thank you.

**Comment by bliswebagency** [comment]
Can confirm it is fixed in Craft 3.7.26 also. Thank you.
