### ISSUE TITLE
Test Orders not appearing even though successful

### ISSUE THREAD

**Issue by a-rbsn** [enupal/stripe#236]
### Description

The payment form works absolutely fine and the order is successful, both on a local server and online, but the order doesn't show in the orders summary in Craft?

### Steps to reproduce

1. Created a simple one-time-only payment form that only accepts 'Card'.
2. Use the form on the website
3. Redirects to homepage
4. Check Craft, no orders showing

### Additional info

- Craft version: 3.7.26
- PHP version: 7.4.16
- Database driver & version: MySQL 5.5.5
- Plugin version: 3.3.10
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @a-rbsn could you please make sure you have properly setup the webhook for live and test? Please follow the instructions [here](https://docs.enupal.com/stripe-payments/stripe-payment-forms/webhook.html#events)

Also if you're working locally you may need to install the stripe CLI, instructions [here](https://docs.enupal.com/stripe-payments/stripe-payment-forms/webhook.html#test-webhooks-locally)

**Comment by andrelopez** [comment]
Also please make sure that the site that is online is `live` (can be accessed via the internet) you can test this going to the home URL in a incognito window on your browser

**Comment by a-rbsn** [comment]
Hi @andrelopez thank you so much for your quick reply, setting up the webhook for the test environment worked brilliantly. I apologise that I didn't see that in the documentation beforehand.

When I try this on the live website which is online and working, the order goes through to my local environment? Is that because I am running the plugin in trial mode?

Best,
Andy

**Comment by andrelopez** [comment]
@a-rbsn I would say:
- To test locally you don't need to add a webhook URL, you need to setup Stripe CLI and forward events to your local endpoint webhook URL, [docs here](https://docs.enupal.com/stripe-payments/stripe-payment-forms/webhook.html#test-webhooks-locally)
- To test on a live site you need to go to the Stripe Dashboard, and setup your Webhook URL (from your site) and add our recommended events, [docs here](https://docs.enupal.com/stripe-payments/stripe-payment-forms/webhook.html) make sure to enable or disable Test mode on your Stripe dashboard depending on the API keys you're using on the live site (staging, live, etc)

Please let me know if you have any questions

**Comment by andrelopez** [comment]
@a-rbsn The order is your local environment because maybe you have running the Stripe CLI?

**Comment by andrelopez** [comment]
Closing for now, feel free to re-open if any follow up questions
