### ISSUE TITLE
Subscription Grants Not Working

### ISSUE THREAD

**Issue by mentiondev** [enupal/stripe#239]
### Description
The Stripe Plugin is working with checkout enabled and it is pulling the data back in to the orders correctly, but it is not assigning the users to the user groups that have been setup in the Subscription Grants, which are Monthly, Quarterly and Annual. Nothing happens with those, so the user remains in the free usergroup, and doesn't get assigned to the group that they've paid for.

So need to know if it's a bug or an issue at my end please?

### Additional info

- Craft version: 3.7.28
- PHP version: 7.4.27
- Database driver & version: MySQL 5.5.5
- Plugin version: 3.3.11
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: yes

Webhooks used:
- source.chargeable
- charge.succeeded
- charge.captured
- checkout.session.completed
- customer.subscription.created
- customer.subscription.deleted

**Comment by mentiondev** [comment]
Hi Andre, this is now working locally for me. I think, but not certain, that it was to do with the webhooks, as I added all of the **payment_intent** webhooks in Stripe as well those above and is now working.

**Comment by andrelopez** [comment]
@mentiondev thanks for getting back to me, I'll test this scenario if so I'll update the [docs](https://docs.enupal.com/stripe-payments/stripe-payment-forms/webhook.html#events)

**Comment by mentiondev** [comment]
Hi again Andre, I've come across another issue to do with the Subscription Grants. So the initial subscription is being allocated correctly, but if you update the subscription via the Customer Portal from one subscription type to another (i.e. monthly to quarterly) it all goes through ok in Stripe, but the the Subscription level doesn't change in Craft. So it doesn't seem to be hooking into that?
