### ISSUE TITLE
Snaptcha, webhook issues and SCA

### ISSUE THREAD

**Issue by fantasticmachine** [enupal/stripe#241]
When using SCA and making a checkout payment it is processed by Stripe but the site returns a 400 error in response to Stripe posting to the Webhook URL. Additionally the redirect URL setting is ignored and the customer is redirected to the site homepage. This prevents the order being properly processed and stops any additional post-order processing that one may be doing.

This issue appears to be related to the use of Snaptcha.

Even though I've added the webhook url to Snaptcha's ignore list it was still being blocked by Snaptcha. I've discovered that it's necessary to add one of the aliased controller routes to Snaptcha's `excludeControllerActions` list in order for the webhook to work.

So far I have got the following in my list

```
'enupal-stripe/stripe/save-order',
'enupal-stripe/checkout/create-session',
'enupal/stripe-payments',
'enupal-stripe/webhook/stripe',
```

That last one is critical as it's the true controller that gets called by the webhook URL.

- Craft version: 3.7.20
- PHP version: 7.4.2 
- Database driver & version: MySQL 5.7.25
- Plugin version:
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @fantasticmachine this issue was solved by the Ben a time ago (https://github.com/putyourlightson/craft-snaptcha/blob/4a6594762838d1b5ab41ba3990eb786c0250aab2/src/services/SnaptchaService.php#L48)

Let me know if you see any other issues related
