### ISSUE TITLE
Archived taxes still show as selectable

### ISSUE THREAD

**Issue by bymayo** [enupal/stripe#243]
We had a client that created a tax in Stripe, then deleted it. In Stripe and in Enupal the tax shows as Archived. But the issue is that the tax is still selected in the payment form, with no way of choose "No Tax".

So when the payments were going through it was trying to apply the archived tax because it couldn't be deleted/removed.

One solution here would be to not show archived taxes in that select box. Or, have an option to select "No Tax"

I got around this temporarily by adding a 0% tax. But it will need patching.

![CleanShot 2022-02-02 at 11 56 06](https://user-images.githubusercontent.com/522877/152149151-ce3c8ec5-522f-449c-b9a3-390447d9b081.png)

**Comment by andrelopez** [comment]
Hi @bymayo  We just release Stripe Payments 4.0.1 with a fix to this issue thanks for reporting
