### ISSUE TITLE
Subscription plan start/end peiod date format not observing locale in CP

### ISSUE THREAD

**Issue by wallacio** [enupal/stripe#247]
### Description
When viewing an order for a Subscription, the plan Period Start and Period End dates are not formatted according to current locale.

**This date, for the UK locale, should be 03/02/2022 rather than 02/03/2022:**

![aada-plan-date](https://user-images.githubusercontent.com/7721989/152682807-901304a2-87aa-4db5-9efc-bd8b417cd834.png)

### Steps to reproduce

1. Create an order for a subscription
2. View the Period Start and Period End dates on order details in CP

### Additional info
- Craft version: 3.7.30.1
- PHP version: 7.4
- Database driver & version: MariaDB 10.5
- Plugin version: 3.3.11
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @wallacio We just released Stripe Payments v3.4.0 with a fix to this issue.
