### ISSUE TITLE
Stripe Tax

### ISSUE THREAD

**Issue by mentiondev** [enupal/stripe#249]
### Description
I'm attempting to implement the **Stripe Tax** feature to my subscriptions so that it **automatically** calculates the Tax rate based on the users location and where I'm registered. See [https://dashboard.stripe.com/test/settings/tax](https://dashboard.stripe.com/test/settings/tax)

The Stripe Docs say that all that is needed for this feature to function is to the add the following line of code in the checkout session:
```
automatic_tax: {
    enabled: true,
  }
```
Reference: [https://stripe.com/docs/payments/checkout/taxes#new-customers](https://stripe.com/docs/payments/checkout/taxes#new-customers)

But I can't see a way to turn this on in the plugin. As the tax section in the plugin only seems to be able to create manual taxes, unless I'm mistaken? 

If so, can a simple lightswitch option be added to turn it on please. As it is essential for the website build I'm working on.

### Additional info

- Craft version: Craft Pro 3.7.28
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.34
- Plugin version: 3.3.11
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
We just released Stripe Payments v3.4.0 with support for Automatic taxes (only on subscriptions). On your payment form, go to the Tax tab and enable "Automatic Taxes" please make sure that on your Plan product you add the tax_behavior.
