### ISSUE TITLE
Allow users update card info

### ISSUE THREAD

**Issue by andrelopez** [enupal/stripe#25]

**Comment by billymedia** [comment]
Hi - Is there any news on this feature?

**Comment by madebyspark** [comment]
Would also like to see this feature! Thx!

**Comment by andrelopez** [comment]
We starting to work on this feature. Stay tuned

**Comment by andrelopez** [comment]
We just released Stripe Payments v2.1.6 with support to update card details. [More Info](https://enupal.com/craft-plugins/stripe-payments/docs/templating/update-card-info)
