### ISSUE TITLE
No way to resubscribe. Payment buttons fail to open Stripe checkout for previous members with a historic account.

### ISSUE THREAD

**Issue by mentiondev** [enupal/stripe#255]
### Description
After a user has cancelled their subscription and left completely. Sometimes they want to resubscribe, but the payment buttons no longer work for them, as the Stripe checkout doesn't open when you click one of the payment buttons if they have a cancelled account. So there is no way for them to resubscribe, as if you use the manage billing button instead, the billing area in Stripe doesn't have an option to renew the expired account. So I'm assuming it has to be done via the payment button method and Stripe will recognise the email address.

### Steps to reproduce

1. Cancel a subscription immediately
2. Try to click on payment button

### Additional info

Craft version: Craft Pro 3.7.28
PHP version: 7.4.21
Database driver & version: MySQL 5.7.34
Plugin version: 3.3.11
Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @mentiondev I was able to recreate this issue if the automatic tax lightswitch was enabled on the payment form under the Tax tab. We just released Stripe Payments v4.0.1 with a fix to this issue.

About the customer portal, please take a look at this part of our [tutorial](https://youtu.be/Te1ojDiVaR8?t=2832) (Min 47:12) I you created the subscription plans via the Stripe dashboard you can choose the plans to show to the customer when they are in the customer portal.
