### ISSUE TITLE
Cache Stripe API requests

### ISSUE THREAD

**Issue by wallacio** [enupal/stripe#256]
### Description
Feature request, or at least a request for how-do-I-do-this.

Client has 4 subscription products, with between 1 and 10 price variations in that. Each product is represented by a paymentForm, with each price variation as an option.  Client would like all subscription forms on the same page, with some JS to show/hide a paymentForm for each product.

I'm able to cache up some stuff but looping round 4 paymentForm.paymentForm() is very slow, because of the 600-800ms round trip to Stripe to query each price (presumably). Wrapping in {% cache %} tags prevents the paymentForm() from rendering correctly (JS isn't loaded) so that's not currently an option.

Is there an 'approved' way of caching the HTML generated by paymentForm(), or can some kind of caching be an option in the plugin?

### Steps to reproduce

1. Add multiple subscription paymentForms to a page, each with a number of price options.
2. Collect tumbleweed.

### Additional info

- Craft version: 3.7.34
- PHP version: 7.4
- Database driver & version: MariaDB 10.5
- Plugin version: 3.4.1
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @wallacio please feel free to use the [Cart API](https://docs.enupal.com/stripe-payments/pro/cart-api.html) feature or the  [Checkout Twig Tag](https://docs.enupal.com/stripe-payments/pro/checkout.html) feature (this only generates a checkout URL) so it's faster.

Please let me know if you have any questions
