### ISSUE TITLE
Cannot override customer or admin email templates

### ISSUE THREAD

**Issue by wallacio** [enupal/stripe#258]
### Description
I cannot seem to override the email notification templates. I've copied and modified the twig templates from vendor and placed in templates/_emails directory. I have then selected the appropriate template in Settings -> Customer Notifications.

![template location](https://user-images.githubusercontent.com/7721989/157299736-5819916c-fc1d-434e-99d8-88f91db5b91d.png)

![stripe setting](https://user-images.githubusercontent.com/7721989/157299775-56e17262-2bb6-40e4-9bf5-0f362107f335.png)

Showing auto-complete, to prove that it's there:

![stripe auto](https://user-images.githubusercontent.com/7721989/157299785-6fda127c-9475-4eed-9c3e-ac54fcf458ba.png)

I've tried various things, such as setting an environment variable instead etc but nothing seems to work.  Every time, the template from the vendor directory is used.

Debugging is getting me nowhere but curiously, I cannot see anything in the logs from src/services/Emails::sendEmail, where it's supposed to be reporting success/fail. (Dev mode is on). Is this Service even used for notification emails?
https://github.com/enupal/stripe/blob/60b02e405f0f42da6cbc45ce10dc06d58e973b81/src/services/Emails.php#L125

### Additional info

- Craft version: 3.7.36
- PHP version: 7.4
- Database driver & version: MariaDB 10.5
- Plugin version: 3.4.1
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by wallacio** [comment]
Ok, so a ton of debugging and I see this happening in the logs:
```
2022-03-08 20:31:46 [-][-][-][error][AJWINFO] Template Override found
2022-03-08 20:31:46 [-][-][-][error][AJWINFO] Template Override found: _emails/customer.twig
2022-03-08 20:31:46 [-][-][-][error][AJWINFO] Template Override path: /home/vagrant/code/aada/templates/_emails/customer.twig
2022-03-08 20:31:46 [-][-][-][error][AJWINFO] No template found at /home/vagrant/code/aada/templates/_emails/customer.twig.html
2022-03-08 20:31:46 [-][-][-][error][AJWINFO] No template found at /home/vagrant/code/aada/templates/_emails/customer.twig.twig
2022-03-08 20:31:46 [-][-][-][error][AJWINFO] Template Override is null
```
**templates/_emails/customer.twig.twig**
Why is it trying to look for an extension of .twig or .html on a file which already has it??

**Comment by andrelopez** [comment]
Hi @wallacio do you try removing the .twig extension? Let me know if that works

**Comment by andrelopez** [comment]
Thanks for confirming and reporting and sorry about the troubles, I just marked this as a bug and will be addressed on next release.

**Comment by andrelopez** [comment]
We just release Stripe Payments 4.0.1 with a fix to this issue thanks for reporting

**Comment by mark-chief** [comment]
Hello @andrelopez.

I am experiencing this issue with plugin version 4.1.1 and craft 3.7.36.

I have tried with and without the .twig extension. (possibly only started when i installed Enrupal Snapshot too.)
