### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by GMConsultant** [enupal/stripe#26]
craft/vendor/enupal/stripe/src/templates/_frontend/multipleplans/radio.twig:9
craft/vendor/enupal/stripe/src/templates/_frontend/paymentForm.twig:32
craft/vendor/enupal/stripe/src/services/Orders.php:547
craft/vendor/enupal/stripe/src/templates/_frontend/multipleplans/dropdown.twig:12

### Additional info

- Craft version: 3.1.x
- PHP version: 7.2.x
- Plugin version: 1.7.1

**Comment by andrelopez** [comment]
Hi @GMConsultant 

We have fixed this deprecation errors on Stripe Payments v1.8.0

Also the `craft/vendor/enupal/stripe/src/services/Orders.php:547` warning is a false positive.

Best,
