### ISSUE TITLE
"View Customer" link on admin order detail when in live mode is linking to test mode customer

### ISSUE THREAD

**Issue by wallacio** [enupal/stripe#261]
### Description
When viewing details of an order in Live mode, the "View Customer" link is linking to a test mode URL:

Probably because of this:
https://github.com/enupal/stripe/blob/5f80bd7ad8725db8bdd861052d6525c61fe9160e/src/templates/orders/_orderInfo.twig#L88

![stripe-view-customer](https://user-images.githubusercontent.com/7721989/157909504-f7049101-816f-449d-b200-e0318ac01d09.png)

### Steps to reproduce

1. Create an order on a site with Stripe Live mode keys
2. View the order
3. Click the View Customer link

### Additional info

- Craft version: 3.7.36
- PHP version: 7.4
- Database driver & version: MariaDB 10.5
- Plugin version: 3.4.1
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @wallacio  We just released Stripe Payments v3.4.2 with a fix to this issue. Thanks for reporting.
