### ISSUE TITLE
Plans not shown when clicking "refresh" on payment form setup

### ISSUE THREAD

**Issue by fantasticmachine** [enupal/stripe#267]
I have had the plugin set up and working fine on local dev and a remote staging server hooked up to my own Stripe account using test keys.

Now I'm trying to get it working using the client's Stripe account. But when I set up a form and click "refresh" to get the plans, nothing is shown. This is despite a plan being set up in the Stripe account.

No errors are generated, and inspecting the response shows the expected JSON but with no plan data.

Going to Settings->Subscription Plans and hitting Refresh appears to work, a success message is shown.

The only thing I can see as being different is that the client API keys appear much longer than those for my account (which is older). I thought perhaps the problem was a difference in the API version being used, but changing the API version of my own account doesn't make a different to my local dev and it all still seems to work.

### Additional info

- Craft version:  3.7.33
- PHP version: 8.0
- Plugin version: 3.4.1
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by fantasticmachine** [comment]
Bingo! That was the problem. That switch was "ON". I've turned it off and now I see the plans.

Can I ask, what's the purpose of that? Surely one would just want to retrieve the plans?

**Comment by andrelopez** [comment]
@fantasticmachine Sorry about that, that setting is disabled by default however if you updated the plugin from older versions that setting could be enabled. The purpose is to retrieve only plans with nicknames (human-readable names), some companies have APIs that automatically create custom plans, so it could be a bit overwhelming to see too many plans when the refresh button is hit.
