### ISSUE TITLE
Support for Dynamic Tax for Subscriptions

### ISSUE THREAD

**Issue by Joobs** [enupal/stripe#268]
Do you have any plans for adding Dynamic Tax support for Subscription products?
Since Automatic Stripe Tax charges for each transaction it's expensive to use if you are offering a subscription service that is only being used mainly in 1 or 2 Countries.

### Additional info
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
This scenario can be supported via the [beforeCreateSession](https://docs.enupal.com/stripe-payments/plugin-development/events.html#beforecreatesession) event available on Stripe Payments v4.x:

```php
use enupal\stripe\services\Checkout;
use enupal\stripe\events\CheckoutEvent;
use enupal\stripe\Stripe;
use craft\base\Plugin;
use Craft; 

class YourPlugin extends Plugin
{
    public function init()
    {
        ....
        ....
     
         Event::on(Checkout::class, Checkout::EVENT_BEFORE_CREATE_SESSION, function(CheckoutEvent $e) {
              $isCart = $e->isCart;
              $sessionParams = $e->sessionParams;
              // ADD dynamic_tax_rates
              foreach ($sessionParams['line_items'] as $item) {
                  $item['dynamic_tax_rates'] = [
                      'txr_123zyx',
                      'txr_456qwe',
                      // additional tax rates
                  ]
              }
              $e->sessionParams = $sessionParams;
         });
        ...
        ...        
     }
}  
```
