### ISSUE TITLE
Hitting Stripe limits when performing guest subscriptions

### ISSUE THREAD

**Issue by intoeetive** [enupal/stripe#27]
On the website I'm working on, the plugin is used to process subscription payments in Stripe, however it is not required for customer to be logged in.

This is recurring donation, and no user account is created in Craft, just the Stripe subscription.

However soon after launch of this feature I started getting error: `Customer cus_EBUpBMEzFUKEwO already has the maximum 25 current subscriptions`

It appears that though email address is being captured, all guest purchases are being sent to Stripe as 'Guest' customer (whatever the email address is).

So in order to make things for for me, I'd need the plugin to create new Stripe customer for each different email address used.

Do you think this is something you could add?

**Comment by andrelopez** [comment]
Hi @intoeetive 

Thanks for reaching out. I was unable to recreate this issue. We create the customer always because the email address is required in all the scenarios (one-time, donations, subscriptions, etc), no matters if the Craft user is not logged in.

Could you please send us screenshots of your payment form to try to recreate this issue?

Feel free to send this info to our email: support@enupal.com

Best,
-Andre L

**Comment by theskyfloor** [comment]
I'm getting this same issue. Is it possible that the issue happens only in Test mode? Two different payments same customer id in Stripe:

<img width="1076" alt="Screen Shot 2019-03-21 at 1 35 53 PM" src="https://user-images.githubusercontent.com/8887839/54776511-4bea9b00-4bde-11e9-904b-480a056b1c72.png">

**Comment by andrelopez** [comment]
Hi @theskyfloor 

Did you use a different email on each payment?

**Comment by theskyfloor** [comment]
No, they were guest payments with no email attached? This isn't an issue for me anymore as I am assigning an email in the payment form but I thought perhaps it would help solve the other posters issue. I think he is experiencing the same thing... if it's a guest user and no email is provided then the customer number is the same.

**Comment by andrelopez** [comment]
The issue was a wrong namespace of the `stripeElementEmail` input when using the Template overrides functionality
