### ISSUE TITLE
Licensing Issue appeared

### ISSUE THREAD

**Issue by mentiondev** [enupal/stripe#276]
### Description
A message appeared in the Craft dashboard today saying the following:

There’s a licensing issue with the Stripe Payments plugin. Please fix on an environment where administrative changes are allowed.

I've been using the product for four months without any issues, and checked and my license is still valid, as has 9 months left to run.

But I've noticed that you released a new 4.0.0 version today, which I haven't upgraded to yet. So could this be a bug from that somehow?

### Additional info

- Craft version: Craft Pro 3.7.34
- PHP version: 7.4.29
- Database driver & version: MySQL 5.5.5
- Plugin version: 3.4.1
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @mentiondev Thanks for letting us know. Please ignore this warning for now, as you mentioned it could be triggered as there is a new Stripe Payments version that added a `pro` edition, however, your plugin should continue working as normal on the v3.x or if you decide to update to v4.x the plugin will automatically get the `lite` version that has all the functionalities on v3.x. @brandonkelly Could you please confirm any additional steps for this warning?

**Comment by brandonkelly** [comment]
Should be fixed now.

**Comment by mentiondev** [comment]
Confirmed. It's no longer showing.
