### ISSUE TITLE
Additional options for Checkout/Pro tag

### ISSUE THREAD

**Issue by Joobs** [enupal/stripe#277]
### Description
I have a membership site where we are creating custom subscriptions for certain users.
The new checkout tag is ideal for this, as we can create the subscription in Stripe, sync with metadata, then create a custom checkout tag via the templates, however there are several setting I want to set per checkout session.

Is it possible to add the following parameters?

Set different cancel/success urls:
`cancel_url`
`success_url`

Set trial periods
```
subscription_data: {
      trial_period_days: 14
}
```

Assign dynamic tax rates (these can be hard coded, no need to pull down the rates from Stripe):
```
dynamic_tax_rates: [
    'txr_123zyx',
    'txr_456qwe',
    // additional tax rates
  ],
```

It looks like it might be possible to set some of this via `beforeCreateSession`, but I don't understand how I would change the settings per checkout tag?

### Additional info

- Plugin version: 4.0
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @Joobs Thanks for reaching out. Yes! Please refer to this [stripe docs](https://stripe.com/docs/api/checkout/sessions/create) to see all the attributes available. (we'll add this link soon to our docs)

So you have two options:

## Via the twig tag
```twig
{% set items = [
    {
        "quantity": 1,
        "dynamic_tax_rates": [
             "txr_123zyx",
             "txr_456qwe",
         ],
        "price_data" : {
            "currency": "usd",
            "product_data": {
                "name": "Gold membership"
            },
            "unit_amount": 1000,
            "recurring": {
                "interval": "month",
                "interval_count": 1
            }
        }
    }
]

{% set checkoutSession = craft.enupalStripe.checkout(items) %}
<a href="{{ checkoutSession.url }}">Subscribe</a>
```
## Via the beforeCreateSession event
On the [beforeCreateSession](https://docs.enupal.com/stripe-payments/plugin-development/events.html#beforecreatesession) you will have access to the `session` array before creating it.

To know what Checkout tag are you using please pass a unique identifier to the `metadata` parameter if you need that to add the dynamic tax attribute. (Please check the Optional Fields example [here](https://docs.enupal.com/stripe-payments/pro/checkout.html) )

For example, if you want to add `dynamic_tax_rates` you need to go into each `line_items` and add that attribute:

```php
use enupal\stripe\services\Checkout;
use enupal\stripe\events\CheckoutEvent;
use enupal\stripe\Stripe;
use craft\base\Plugin;
use Craft; 

class YourPlugin extends Plugin
{
    public function init()
    {
        ....
        ....
     
         Event::on(Checkout::class, Checkout::EVENT_BEFORE_CREATE_SESSION, function(CheckoutEvent $e) {
              $isCart = $e->isCart;
              $sessionParams = $e->sessionParams;
              // Get a unique identifier from your metadata
              $checkoutId = $sessionParams['metadata']['my_unique_id'] ?? null;
              // ADD dynamic_tax_rates
              foreach ($sessionParams['line_items'] as $item) {
                  $item['dynamic_tax_rates'] = [
                      'txr_123zyx',
                      'txr_456qwe',
                      // additional tax rates
                  ]
              }
              $e->sessionParams = $sessionParams;
         });
        ...
        ...        
     }
}  
```

Please let me know if that works

**Comment by Joobs** [comment]
Thanks for your reply

The twig example for `Items` object is helpful. I got the structure wrong when I tried it initially, so I assumed it wasn't supported. 

I experimented with the `beforeCreateSession` event and came up with similar code, using the `$checkoutId` in an if statement to change different parameters.

**Comment by Joobs** [comment]
I am still having trouble with the Twig example.

Is it possible to set the `cancel_url` and `success_url` via twig?

**Comment by andrelopez** [comment]
@Joobs Sorry no the only way, for now, is via the [beforeCreateSession](https://docs.enupal.com/stripe-payments/plugin-development/events.html#beforecreatesession).

You could however pass the`cancel_url` and `success_url` via the `metadata` parameter on the `checkout` tag (Please check the Optional Fields example [here](https://docs.enupal.com/stripe-payments/pro/checkout.html) )

Then on the `beforeCreateSession` event:
```php
use enupal\stripe\services\Checkout;
use enupal\stripe\events\CheckoutEvent;
use enupal\stripe\Stripe;
use craft\base\Plugin;
use Craft;

class YourPlugin extends Plugin
{
    public function init()
    {
        ....
        ....
     
         Event::on(Checkout::class, Checkout::EVENT_BEFORE_CREATE_SESSION, function(CheckoutEvent $e) {
              $isCart = $e->isCart;
              $sessionParams = $e->sessionParams;
              //overwrite $sessionParams
              $cancelUrl = $sessionParams['metadata']['cancel_url'] ?? "/";
              $successUrl = $sessionParams['metadata']['success_url'] ?? "/";
              $sessionParams['cancel_url'] =  $cancelUrl;
              $sessionParams['success_url'] =  $successUrl;
              $e->sessionParams = $sessionParams;
         });
        ...
        ...        
     }
} 
```
