### ISSUE TITLE
Type Error when activating a member

### ISSUE THREAD

**Issue by Joobs** [enupal/stripe#278]
### Description
When creating a new member (either activating them via the control panel, or via the activation email link) I get the following error (on my Dev localhost):

```
TypeError
enupal\stripe\Stripe::enupal\stripe\{closure}(): Argument #1 ($e) must be of type yii\web\UserEvent, craft\events\UserEvent given
```

<img width="1027" alt="Screenshot 2022-05-04 at 14 24 32" src="https://user-images.githubusercontent.com/458935/166680853-8c284043-bb79-4323-93b1-45fd62201a9d.png">

### Steps to reproduce

1. Create a new user
2. Activate their account

### Additional info

- Craft version: 3.7.39
- PHP version: 8.1.3
- Database driver & version: MySQL 5.7.37
- Plugin version: 4.0
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @Joobs We just release Stripe Payments 4.0.1 with a fix to this issue thanks for reporting
