### ISSUE TITLE
Stripe Customer Portal feature without user being logged in?

### ISSUE THREAD

**Issue by outline4** [enupal/stripe#279]
Hi, I don't want my users to have to create a password or craft user. 
Is there any way of activating the **stripe customer portal** feature with either the order number or the stripe transaction id? 

thanks for clarifying

**Comment by outline4** [comment]
For instance the update card feature works without a user. I work with the number parameter: 

    {% set number = craft.app.request.param('number') %}
    {% set order = craft.enupalStripe.getOrderByNumber(number) %}
    {% set stripeCustomer = craft.enupalStripe.getStripeCustomer(order.email) %}
    {% set pbk = craft.enupalStripe.getPublishableKey() %}
    {% set session = craft.enupalStripe.getSetupSession(order.email, successUrl, cancelUrl) %}

    <form method="POST" id="update-card">
        {{ csrfInput() }}
        {{ actionInput('enupal-stripe/update-billing-info') }}
        <button>{{ 'Update Card Details'|t }}</button>
    </form>

    <script>
        $( document ).ready(function() {
            var stripe = Stripe('{{ pbk }}');
            $('#update-card').on('click', function(e) {
                e.preventDefault();
                stripe.redirectToCheckout({
                    sessionId: '{{ session.id }}'
                });
            });
         });
    </script>


So I thought that the Stripe Customer Portal feature could work in a similar way?

**Comment by andrelopez** [comment]
Hi @outline4 we just released Stripe Payments 4.0.1 with support for this feature, we updated the example on the [docs](https://docs.enupal.com/stripe-payments/templating/update-billing.html)

The guest user will need to enter the Order Number
```twig
<form method="POST">
    {{ csrfInput() }}
    {{ actionInput('enupal-stripe/stripe/create-customer-portal') }}
    <input type="hidden" name="returnUrl" value="{{ siteUrl('/account') }}">
    
    <label for="orderNumber">
        Order Number
    </label>
    <input name="orderNumber">
    
    <button type="submit">Manage billing</button>
    
    {% if customerPortalError is defined %}
        <div class="error">
            {{ customerPortalError }}
        </div>
    {% endif %}
</form>
```

**Comment by andrelopez** [comment]
Hi @outline4 could you please make sure you save your Customer Portal settings on the Stripe Dashboard? [test](https://dashboard.stripe.com/test/settings/billing/portal) or [live](https://dashboard.stripe.com/settings/billing/portal)

Let me know if that works

**Comment by outline4** [comment]
I have saved the customer portal in live and test mode.  
I also previewed it. 

P.s. I have cancelled the subscription, but it's still ongoing. Could this be the problem?

**Comment by andrelopez** [comment]
@outline4 let me check that scenario, could you please recreate the issue and send back to us a zip file of the following folder? storage/logs to support@enupal.com

**Comment by outline4** [comment]
email sent! 

Thanks for looking into it!

**Comment by outline4** [comment]
Update: the customer was deleted. That's why the customer portal could not be created.  

Thanks for helping out!
