### ISSUE TITLE
Is it possible to send emails for Trials ending, and Subscription renewals?

### ISSUE THREAD

**Issue by Joobs** [enupal/stripe#280]
I don't think Stripe sends webhooks for Trials expiring, or subscription renewals.

Is there anyway to send emails for Trial expirations and Subscription renewals?

**Comment by andrelopez** [comment]
Hi @Joobs Following this [Stripe docs](https://stripe.com/docs/billing/subscriptions/trials) yes, you can listen to `customer.subscription.trial_will_end` from a custom plugin, 

> Three days before the trial period is up, a customer.subscription.trial_will_end event is sent to your [webhook endpoint](https://stripe.com/docs/billing/subscriptions/webhooks). You can use that notification as a trigger to take any necessary actions, such as informing the customer that billing is about to begin.

Here is a quick example from the [afterProcessWebhook](https://docs.enupal.com/stripe-payments/plugin-development/events.html#afterprocesswebhook) event

```php
use enupal\stripe\services\Orders;
use enupal\stripe\events\WebhookEvent;
use enupal\stripe\Stripe;
use craft\base\Plugin;
use Craft;

class YourPlugin extends Plugin
{
    public function init()
    {
        ....
        ....
                    
        Event::on(Orders::class, Orders::EVENT_AFTER_PROCESS_WEBHOOK, function(WebhookEvent $e) {
            $data  = $e->stripeData;
            $order = $e->order;
        
            if ($order){
                $user = Craft::$app->getUsers()->getUserByUsernameOrEmail($order->email);
                // Or if the order have logged in users:
                // $user = Craft::$app->getUsers()->getUserById($order->userId);            
        
                if ($user) {
                    switch ($data['type']) {
                        //Occurs whenever a customer is signed up for a new plan. (If SCA is disabled)                   
                        case 'customer.subscription.trial_will_end':
                            // Add a user group id
                            $email = $order->email;
                            // send EMAIL here
                    }
                }
            }
        });
        ...
        ...        
     }
}    
```
