### ISSUE TITLE
Update Payment Form Subscriptions to use line_items, rather than deprecated subscription_data.items

### ISSUE THREAD

**Issue by Joobs** [enupal/stripe#283]
### Description
I'm trying to add dynamic tax rates (not a fixed rate, and not automatic tax rates) to a subscription payment form. I'm using `EVENT_BEFORE_CREATE_SESSION` event to overwrite the Checkout session.

It seems to be using a deprecated format of `subscription_data.items`, the Stripe docs suggest moving over the `line_items`:
https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-subscription_data-items

I don't think `dynamic_tax` is supported with the current parameter format. 

https://stripe.com/docs/billing/subscriptions/taxes has the following format which seems to be the newer syntax (and I think checkout/pro is using this):

```
'line_items' => [[
    'price' => '{{PRICE_ID}}',
    'quantity' => 1,
    'dynamic_tax_rates' => [
      '{{FIRST_TAX_RATE_ID}}',
      '{{SECOND_TAX_RATE_ID}}',
      // additional tax rates
    ],
  ]],
  'mode' => 'subscription',
```

### Additional info

- Plugin version: 4.0.1
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: yes

**Comment by andrelopez** [comment]
Hi @Joobs that example looks correct to me, similar to [this one](https://stripe.com/docs/payments/checkout/taxes?tax-calculation=tax-rates#dynamic-tax-rates) in order to use `dynamic_tax_rates` you need the `priceId`

Stripe Payments Pro only uses the `Automatic Tax` so please make sure to have that setting disabled under the Stripe Payments -> Settings -> Checkout

Are you getting an error your example?

**Comment by Joobs** [comment]
@andrelopez I am using a Payment Form as I need to be able to select the plan via a radio button and then checkout immediately.

This is the session array it creates.  From the Stripe docs my understanding is `[sessionParams][subscription_data][items]` is deprecated and doesn't allow for `dynamic_tax_rate`.

```
[sessionParams] => Array ( 
    [payment_method_types] => Array ( 
      [0] => card 
      [1] => sepa_debit 
    ) 
    [subscription_data] => Array ( 
      [items] => Array ( 
        [0] => Array ( 
          [plan] => price_xyz123 
          [quantity] => 1 
        ) 
      ) 
    ) 
    [success_url] => https://example.com/enupal/stripe-payments/finish-order?session_id={CHECKOUT_SESSION_ID} 
    [cancel_url] => https://example.com
  )
  ```
  
Based on the examples in the docs, they imply the above is deprecated and should be using something similar to below:
  
  ```
  [sessionParams] => Array ( 
    [payment_method_types] => Array ( 
      [0] => card 
      [1] => sepa_debit 
    ) 
    [locale] => de 
    [line_items] => Array ( 
      [0] => Array ( 
        [quantity] => 1 
        [price] => price_xyz123
        [dynamic_tax_rates] => Array (
           ...
          )
      ) 
    ) 
    [success_url] => https://example.com/enupal/stripe-payments/finish-order?session_id={CHECKOUT_SESSION_ID} 
    [cancel_url] => https://example.com/ 
    [mode] => subscription 
  )
  ```

**Comment by andrelopez** [comment]
@Joobs Yep, You need to use `line_items` when using `dynamic_tax_rates` so basically from the EVENT_BEFORE_CREATE_SESSION you need to transform that to the second example. Let me know if you get any errors.

You can pass a metadata key from your payment form options so you can validate the override only for that scenario.
