### ISSUE TITLE
Updating from v3 to v4 and craft is saying the licence is invalid

### ISSUE THREAD

**Issue by sunscreem** [enupal/stripe#284]
### Description

I ran the usual updates this month and this plug in upgraded from v3 to v4.

I've not got this warning. My project.yaml shows the version as Standard.

![image](https://user-images.githubusercontent.com/7523595/170116714-769ff9e9-0284-46bd-8c05-b3fe9b4dd7fe.png)

### Steps to reproduce

1. Install plug in, add licence
2. Update from v3 to v4.

### Additional info

- Craft version: Craft Pro 3.7.43
- PHP version: 8.0.19
- Database driver & version: MySQL 5.7.38
- Plugin version: 4.0.1
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: N

**Comment by andrelopez** [comment]
Hi @sunscreem thanks for reporting this issue, please don't worry about this warning, this is an issue related to the plugin store and there is nothing wrong with your license.

@brandonkelly Could you please help us here? I also received a few customer emails related to this issue. Thank you in advance

Related issue: https://github.com/enupal/stripe/issues/276

**Comment by sunscreem** [comment]
Hey @andrelopez - Is there a possibly a workaround I could use in the meantime?

**Comment by andrelopez** [comment]
@sunscreem Sorry nothing that we can do from our side, however, the plugin is working as normal right? 

Hi @brandonkelly could you please help us on this issue? I received a few more customer emails yesterday related to this issue. Any help will be appreciated.

**Comment by sunscreem** [comment]
Hey @andrelopez - Yeah - payments seem to be being processed normally. Just the nag screen in the control panel is an understandable worry for clients. Thanks for the update.

**Comment by sunscreem** [comment]
Hey @andrelopez Sorry to nag - any update on this? Can I maybe change the project.yaml manually? My client is nagging me :(

**Comment by andrelopez** [comment]
Hi @sunscreem Sorry about that. Yes, if your Stripe Payments plugin is currently on V4.x.x please feel free to update the `edition` key from `standard` to `lite` under the ` project.yaml `

```yaml
plugins:
  enupal-stripe:
    edition: lite
    enabled: true
```

**Comment by sunscreem** [comment]
Thanks @andrelopez - Will do later today and get back to you.

**Comment by sunscreem** [comment]
Hey @andrelopez - That's it all sorted now thanks. Not sure if you want to close the issue or leave it open for Brandon?
