### ISSUE TITLE
How do I get the details of a specific price by Stripe ID?

### ISSUE THREAD

**Issue by Joobs** [enupal/stripe#289]
I have pages where I am using the checkout tag with a hard-coded Stripe Price ID.

But it would be very useful if I could fetch information about a specific price. So I can display price information above the checkout button.

I was hoping this would work:

```
{% set price = craft.enupalStripe.prices().stripeId("price_ABC123").one() %}
```

Is there anyway I can fetch data about a specific price?

**Comment by andrelopez** [comment]
Hi @Joobs We just released a new version for Stripe Payments on Craft3 and Craft4 with support for `prices` and `app` (if you need access to the Stripe Payments services layer) variables, please check the next examples:

Option1: using the `PriceQuery`  under `craft.enupalStripe.prices`
```twig
 {% set price = craft.enupalStripe.prices.stripeId('price_1KbKZHLLWVlbcCFQ9MgfcTxT').one() %}
```

Option 2: using the service layer under `craft.enupalStripe.app`:
```twig
{% set price = craft.enupalStripe.app.prices.getPriceByStripeId('price_1KbKZHLLWVlbcCFQ9MgfcTxT') %}
```
