### ISSUE TITLE
Unable to create subscription using Stripe Elements

### ISSUE THREAD

**Issue by mokopan** [enupal/stripe#295]
### Description
Hi, 
We've been running into problems using Stripe Elements to create subscriptions, I've done a bit of digging and it looks like it is due to this line https://github.com/enupal/stripe/blob/master/src/services/Orders.php#L1187
 
Which I believe should be ` $subscription = Subscription::create($subscriptionSettings);` to use the Stripe subscription api instead, and `'customer' => $customer,` added to the `$subscriptionSettings` array.

I've tested it locally and it looks like subscriptions are now created properly, but I'm not sure if there's something else I'm missing

Let me know if there's any other details you need
Thanks!

### Steps to reproduce

1. Try to create a subscription using Stripe Elements and the `enupal-stripe/stripe/save-order` action
2. Get a `"Call to a member function create() on null"` error

### Additional info

- Craft version: 4.0.5.1
- PHP version: 8.1.7
- Database driver & version: MySQL 10.7.1
- Plugin version: 5.0.3
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: No

**Comment by andrelopez** [comment]
Hi @mokopan We just released Stripe Payments v5.0.4 with a fix to this issue. Thanks for reporting

**Comment by mokopan** [comment]
Thank you, very much appreciated!
