### ISSUE TITLE
Syncing orders from Stripe fails

### ISSUE THREAD

**Issue by mokopan** [enupal/stripe#296]
### Description
Hi

We've been encountering the following error when trying to sync one-time and subscription orders from Stripe 
```
[queue.ERROR] [craft\queue\QueueLogBehavior::afterError]  [16387] Syncing One-Time Orders (attempt: 1, pid: 196) - Error (time: 3.726s): Cannot assign string to property craft\base\Element::$dateCreated of type ?DateTime {"memory":27484856} 
[queue.ERROR] [TypeError] TypeError: Cannot assign string to property craft\base\Element::$dateCreated of type ?DateTime in /app/vendor/enupal/stripe/src/jobs/SyncOneTimePayments.php:128
```
Looks like it could just be due to the `format` function converting it to a string

Let me know if you need any more details

Thanks for all your work on the plugin!

### Steps to reproduce

1. Attempt to sync orders with Stripe from settings

### Additional info

- Craft version: 4.0.5.1
- PHP version: 8.1.7
- Database driver & version: MySQL 10.7.1
- Plugin version: 5.0.3
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: No

**Comment by andrelopez** [comment]
Hi @mokopan We just released Stripe Payments v5.0.4 with a fix to this issue. Thanks for reporting
