### ISSUE TITLE
Add ability to use custom HTML in payment form

### ISSUE THREAD

**Issue by intoeetive** [enupal/stripe#3]
I would like to customize payment form more than that it's possible with CSS. 

Please add a template variable to access unrendered form object, or add ability to override the form template with a custom one

**Comment by andrelopez** [comment]
Hi @intoeetive 

Thanks for reaching out. We're working on this feature. I have added you to the notify list for when this feature is released.

Best,

**Comment by andrelopez** [comment]
Hi @intoeetive 

Just wanted to let you know that the "template overrides" feature is available in v1.3.0.

- Please go to the edit page of you Stripe Payment form and Enable "Custom templates" 
- Create a folder override in your templates craft folder: _stripe/formHandle (Here you can copy all files from [here](https://github.com/enupal/stripe/tree/master/src/templates/_frontend) 
- Copy that path in the "Templates Folder" input
- Save your Stripe Form.

Tha's it! Official docs will be available soon.

Best,

**Comment by intoeetive** [comment]
Thanks a lot, @andrelopez !

**Comment by andrelopez** [comment]
New docs link [here](https://enupal.com/craft-plugins/stripe-payments/docs/plugin-development/template-overrides)

Best,
