### ISSUE TITLE
Date range filter for Sync is missing

### ISSUE THREAD

**Issue by Joobs** [enupal/stripe#300]
### Description
I am launching a project soon that has existing orders in Stripe. 
I went to look at the sync section and noticed the date range is missing. We need the date range as we are importing a large number of users.
Not sure why it's now missing.

<img width="1156" alt="Screenshot 2022-06-29 at 17 34 08" src="https://user-images.githubusercontent.com/458935/176477733-e6f550d0-9067-4f3c-b961-b0024432e973.png">

### Additional info

- Craft version:  3.7.45.2
- PHP version: 8.1
- Plugin version: 4.0.4
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: yes

**Comment by andrelopez** [comment]
Hi @Joobs I am unable to recreate this issue, could you please try saving the settings and check if the error is gone? Could you please try to open the browser developer tools and inspect for javascript errors?

**Comment by Joobs** [comment]
Issue was with me.

For some reason my Lightswitches are invisible when "off".

There is a lightswtich there, when it's "on", the date range appears
