### ISSUE TITLE
Tiered Plans

### ISSUE THREAD

**Issue by michielsarne** [enupal/stripe#304]
### Description
I get this error when I use tiered plans

![image](https://user-images.githubusercontent.com/71928563/178704807-092fcfb5-3779-459d-beea-4e9ea06f64da.png)

### Steps to reproduce

1. add subscriptions via stripe with volume pricing
2. add payment form with stripe checkout and customer chooses plan

### Additional info

- Craft version: Craft Pro 4.1.3
- PHP version: 8.1.5
- Database driver & version: MySQL 10.4.24
- Plugin version: 5.0.4
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: yes

**Comment by michielsarne** [comment]
@andrelopez will there be an update for this? Or should I look for an alternative?

**Comment by andrelopez** [comment]
Hi @michielsarne We just released Stripe Payments v5.0.5 with a fix to this issue. Thanks for reporting

**Comment by michielsarne** [comment]
> Hi @michielsarne We just released Stripe Payments v5.0.5 with a fix to this issue. Thanks for reporting

Thank you so much !
