### ISSUE TITLE
Custom email

### ISSUE THREAD

**Issue by michielsarne** [enupal/stripe#311]
### Description
How can you send an email on purchase of a subscription to the admin with the user's information (from craft user)?

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugin version:
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by andrelopez** [comment]
Hi @michielsarne You can use the Admin notification settings under `Stripe Payments -> Settings -> Admin Notifications` please find more info [here](https://docs.enupal.com/stripe-payments/notifications/admin.html) and let me know if you have any questions
