### ISSUE TITLE
Subscription grants not working at all

### ISSUE THREAD

**Issue by michielsarne** [enupal/stripe#312]
### Description
I have setup my site online, added al the stripe events and still the subscription grants are not working.

### Steps to reproduce

1. add subscriptions

2. add subscription grants

### Additional info

- Craft version: Craft Pro 4.2.0.2
- PHP version: 8.0.22
- Database driver & version:  MySQL 8.0.27
- Plugin version: 5.0.6
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by andrelopez** [comment]
Hi @michielsarne Are you testing locally (local development environment)?

**Comment by michielsarne** [comment]
@andrelopez I'm testing it on both, the user assignments only work for the admin. I'm switching some user permissions but nothing makes it change.

**Comment by andrelopez** [comment]
Thanks for following up. On your local environment could you please confirm that you're using the Stripe CLI ([docs here](https://docs.enupal.com/stripe-payments/stripe-payment-forms/webhook.html#test-webhooks-locally)), if so could you please recreate the issue and send back to us a zip file of the following folder to support@enupal.com?
`storage/logs`

**Comment by michielsarne** [comment]
Yes im using the CLI, I'm sending my logs right now.

**Comment by splendidrob** [comment]
Just to add to this I am also finding subscription grants dont work at all. Testing locally using the Stripe CLI - The CLI shows all the events firing and being forwarded to the webhook endpoint, nothing happens to the users - they are not added or moved to the specified user group.

**Comment by splendidrob** [comment]
Tracked this down - I was using the webhook signing secret from the stripe dashboard and hadn't realised i needed to copy the webhook signing secret from the CLI response when running listen! Now the user is being added to the correct user group.

**Comment by andrelopez** [comment]
Great thanks for the update. This issue is solved adding [webhooks](https://docs.enupal.com/stripe-payments/stripe-payment-forms/webhook.html) for live or staging sites or using [Stripe CLI ](https://docs.enupal.com/stripe-payments/stripe-payment-forms/webhook.html#test-webhooks-locally)for local dev
