### ISSUE TITLE
E-mail on subscription cancel?

### ISSUE THREAD

**Issue by michielsarne** [enupal/stripe#313]
### Description
Is there a possibility to send a mail to the admin whenever a user cancels his subscription?

### Steps to reproduce

1. question
2. question

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugin version:
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by andrelopez** [comment]
Hi @michielsarne you need to enable [webhooks](https://docs.enupal.com/stripe-payments/stripe-payment-forms/webhook.html) and create a custom plugin to listen for the [afterprocesswebhook event](https://docs.enupal.com/stripe-payments/plugin-development/events.html#afterprocesswebhook) and check the event type depending on the following scenarios:

Please check the next setting: `Stripe Payments → Settings → Defaults` and check the "Cancel subscription at period end" lightswitch

1)  if the lightswitch is enabled, check the  `customer.subscription.updated` event type, as the order will cancel at period end, it only updates the subscription. Then when the end date is reached it will trigger the `customer.subscription.deleted` event type
2)   if the lightswitch is disabled, check the `customer.subscription.deleted` event type, as this event will be triggered right away. 

You can use our [Emails](https://github.com/enupal/stripe/blob/master/src/services/Emails.php) service class to see some examples on how to send an email on Craft CMS
