### ISSUE TITLE
Checkout settings save

### ISSUE THREAD

**Issue by cole007** [enupal/stripe#321]
### Description

Odd one - when trying to save settings under Stripe Payments > Settings >  (Pro) Checkout the admin is redirected to `enupal-stripe/settings/cart` which doesn't exist so throws a 404 error. Can see this set in the template here:

```
https://github.com/enupal/stripe/blob/master/src/templates/settings/pro/checkout.twig#L15
```

### Additional info

- Craft version: 3.7.59
- PHP version: 7.4.21
- Database driver & version: MySQL
- Plugin version: 4.0.10
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yep

**Comment by andrelopez** [comment]
We just released Stripe Payments v5.0.9 with a fix for this issue. Thanks for reporting
