### ISSUE TITLE
Override CP Charge Description

### ISSUE THREAD

**Issue by mark-chief** [enupal/stripe#325]
### Description
Can I override the Charge Description from the payment form?

_Context: it appears in the Description column in the Stripe CP, and I would like to dynamically change it depending on the order type from the website_

<img width="1158" alt="Screenshot 2022-12-16 at 08 49 44" src="https://user-images.githubusercontent.com/18699249/208061357-52dae6d3-390a-4a48-aab7-ee550ef0d612.png">

### Additional info
- Craft version: 3.6.15
- Plugin version: 3.3.3

Thank you

**Comment by andrelopez** [comment]
Hi @mark-chief Yes. please follow the next steps:

```
{% do craft.enupalStripe.addVariables({ dynamicCharge: "this is dynamic" }) %}

{{ craft.enupalstripe.paymentForm('paymentForm') }}
```

On your Stripe Payments -> Settigns -> Defaults:

<img width="1571" alt="Screenshot 2022-12-26 at 2 23 52 pm" src="https://user-images.githubusercontent.com/875476/209558318-cf3c3156-753b-427c-823e-30b707b34233.png">

Please let me know how it goes

**Comment by mark-chief** [comment]
@andrelopez Hello, this didnt work for me, instead of "this is dynamic" it is pulling through a number/hash....

<img width="801" alt="Screenshot 2023-04-13 at 09 18 10" src="https://user-images.githubusercontent.com/18699249/231698316-8cc87117-f3d5-436b-8270-298ab07bcdc8.png">

<img width="477" alt="Screenshot 2023-04-13 at 09 18 32" src="https://user-images.githubusercontent.com/18699249/231698404-c154d80f-d489-45bc-af91-dc0c171c74fd.png">

<img width="489" alt="Screenshot 2023-04-13 at 09 19 49" src="https://user-images.githubusercontent.com/18699249/231698764-16332c71-1544-4a06-8d67-9a23595a675c.png">
