### ISSUE TITLE
The "customAmount" field minimum should be validated server side

### ISSUE THREAD

**Issue by tomfischerNL** [enupal/stripe#326]
### Description
When I create a payment form with a minimum "one time custom payment amount", and I insert an minimum price, it is possible to remove the min attr in the browser with the console. This needs to be validated server side, not the customAmount, but the minimum amount.

### Steps to reproduce

1) If I set a minimum of 100 USD (see attachment)
![Schermafbeelding 2022-12-23 om 17 23 21](https://user-images.githubusercontent.com/2330195/209367685-bcbff468-001f-49eb-84bb-3c0381f9ec0a.png)

2) I can remove the min attr in the browser, and put in 1 dollar as amount, and submit the form
![Schermafbeelding 2022-12-23 om 17 27 16](https://user-images.githubusercontent.com/2330195/209367971-98a4c86a-53ad-4bf0-bc66-967395c8ac6a.png)

### Additional info

- Craft version: 4.3.5
- PHP version: 8.1.11
- Database driver & version: MySQL 10.6.10
- Plugin version: 5.0.8
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by andrelopez** [comment]
Hi @tomfischerNL We just released Stripe Payments v5.0.9 with a fix for this issue. Thanks for reporting

**Comment by tomfischerNL** [comment]
Hi @andrelopez, thanks for fixing this bug so quickly!
