### ISSUE TITLE
When enabling "Dynamic tax rates (One-time payments)", the "options parameter to a form doen't work

### ISSUE THREAD

**Issue by tomfischerNL** [enupal/stripe#328]
### Description

When you add Tax to a form "Enable Dynamic tax rates (One-time payments)", the "options" parameter doesn't work anymore.
{{ craft.enupalStripe.paymentForm('paymentForm', options) }}

### Steps to reproduce

1.  Add options to a form
![options](https://user-images.githubusercontent.com/2330195/209653840-4eb35a2e-276a-400c-a211-2df523414f0a.png)

2. Check payment, with provided options (test name, test description, quantity etc)
![without tax](https://user-images.githubusercontent.com/2330195/209653931-4461aa79-e593-47ae-bf6c-5506e225fafe.png)

3. Add tax rule
![add cms tax](https://user-images.githubusercontent.com/2330195/209653992-8a48d169-601b-4e9a-bbba-f5a0860b944b.png)

4. Check payment
![with tax](https://user-images.githubusercontent.com/2330195/209654018-97192ec9-5f13-49f7-9f0e-1f8104e76803.png)

Here you see that the added options, "item name, description etc, doesn't get applied to the paymentForm.

### Additional info

- Craft version: 4.3.5
- PHP version: 8.1.11
- Database driver & version: MySQL 10.6.10
- Plugin version: 5.0.8
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by andrelopez** [comment]
Hi @tomfischerNL We just released Stripe Payments v5.0.9 with a fix for this issue. Thanks for reporting

**Comment by tomfischerNL** [comment]
Hi @andrelopez , thanks for fixing this bug so quickly!
