### ISSUE TITLE
.hidden class interference

### ISSUE THREAD

**Issue by chasegiunta** [enupal/stripe#33]
### Description
https://github.com/enupal/stripe/blob/787ba91b6d826feec872dc357ed96a1a4ba21824/src/resources/stripe/css/enupal-stripe-elements.css#L15

Enupal is setting a hidden class which gets loaded on the frontend. I think this should either be namespaced with `StripeElement` like all the other classes in this stylesheet, or at the very least, not using `!important`, making it difficult for users to override their own `.hidden` classes.

- Plugin version: 1.9.3

**Comment by chasegiunta** [comment]
@andrelopez This is really causing problems for us on our project, and I supposed would cause problems for anyone using a utility framework, or utility classes - any idea if this will be fixed? Sorry to pester.

**Comment by andrelopez** [comment]
@chasegiunta I'm on it

**Comment by chasegiunta** [comment]
@andrelopez Thank you! Looking forward to it.

**Comment by andrelopez** [comment]
Hi @chasegiunta 
We just released Stripe Payments v1.9.5 with support to prevent load the default css file. Could you please update your plugin and go to: `Stripe Payments -> Settings -> Defaults` disabled the `Load CSS` lightswitch and Save your settings?

You may need to add your own Css file manually please use our [default file](https://github.com/enupal/stripe/blob/787ba91b6d826feec872dc357ed96a1a4ba21824/src/resources/stripe/css/enupal-stripe-elements.css) as a base and remove/add what you need.

Please let me know if that could work

**Comment by chasegiunta** [comment]
@andrelopez That looks like it works for me! Though I was anticipating your fix would be to rename the class - as your javascript files are referencing `hidden` and disabling css altogether probably breaks functionality.
