### ISSUE TITLE
Add success url for a checkout tag

### ISSUE THREAD

**Issue by tomfischerNL** [enupal/stripe#334]
### Description

Please add a checkoutSuccessUrl option for a checkout tag with the "Checkout twig tag (pro)"
Now it only possible to add options to a payment form but not to the checkout tag.

So now all the checkout tags are using the same successUrl, but they need to have different urls.

Thanks!

**Comment by andrelopez** [comment]
Hi @tomfischerNL As this feature is shared with the REST API feature, the most secure way to add/update any attribute to the [checkout session](https://stripe.com/docs/api/checkout/sessions/create) before is created is using the [beforeCreateSession](https://docs.enupal.com/stripe-payments/plugin-development/events.html#beforeprocesstransfer) event. 

If you need to get access to a dynamic variable from your templates you have two options:
- Add a string value to `metadata` on your checkout tag, it will be available on the `$sessionParams` Event property
- Add custom variables in twig:
```twig
{% do craft.enupalStripe.addVariables({ entry: entry }) %}
```
Then you can access the twig variables on the `beforeCreateSession` event

```php
use enupal\stripe\services\Checkout;
use enupal\stripe\events\CheckoutEvent;
use enupal\stripe\Stripe;
use craft\base\Plugin;
use Craft;

class YourPlugin extends Plugin
{
    public function init()
    {
        ....
        ....
     
         Event::on(Checkout::class, Checkout::EVENT_BEFORE_CREATE_SESSION, function(CheckoutEvent $e) {
              $isCart = $e->isCart;
              $sessionParams = $e->sessionParams;
              //overwrite $sessionParams
              $sessionParams['cancel_url'] = 'https://yoursite.com/cancel';
              // Get the TWIG variables here 
              $variables = Stripe::$app->paymentForms->getFieldVariables();
              $entry = $variables['entry'];
              $sessionParams['success_url'] = $entry->successUrl;
               
              $e->sessionParams = $sessionParams;
         });
        ...
        ...        
     }
}  


```

Please let me know if you have any questions!

**Comment by tomfischerNL** [comment]
Thanks! That will help for sure :)
