### ISSUE TITLE
Address object not available with a "checkout" order. Only with a paymentForm order

### ISSUE THREAD

**Issue by tomfischerNL** [enupal/stripe#336]
### Description
When trying to get the address of an Order in twig we can use this

```
{% set number = "MFsC3955Mz3O" %}
{% set order = craft.enupalStripe.getOrderByNumber(number) %}

<h1>Order: {{number}}</h1>

<h3>{{ 'Shipping Address'|t }}</h3>

{{ order.getShippingAddress()|raw }}
```

But if the order is a "checkout" order instead of a "paymentForm" order, there are no address details available in twig. In the backend in Craft, the address is visible, so the address is linked.

When I check the order in twig there is a "billingAddressId", so there should be a possibility to access the address object.

**Comment by andrelopez** [comment]
Hi @tomfischerNL  I was unable to recreate this issue. Could you please go to `Stripe Payments -> Settings -> Checkout` and make sure the "Shipping Address" lightswitch is enabled?

You're trying to display the shipping address, however, you mentioned that the billingAddressId is present, could be possible that you're only collecting the billing address?

Please make sure both settings are enabled:
<img width="591" alt="Screenshot 2023-02-09 at 7 47 35 am" src="https://user-images.githubusercontent.com/875476/217749531-4fd45f76-aa01-44fd-9156-648fa9daa2f8.png">

**Comment by tomfischerNL** [comment]
Thanks for your comment! Will check it out
