### ISSUE TITLE
Craft 4 update: Exception 'yii\base\UnknownPropertyException' with message 'Invalid general config setting: stripePayments

### ISSUE THREAD

**Issue by romainpoirier** [enupal/stripe#349]
### Description
I'm upgrading from Craft `3.7.45.2` to `^4.0.0` following the [doc](https://craftcms.com/docs/4.x/upgrade.html#performing-the-upgrade). At the step `9` (Run `php craft migrate/all`) I'm facing an error that seems related to the `enupal/stripe` plugin:

```
% php8 craft migrate/all
Exception 'yii\base\UnknownPropertyException' with message 'Invalid general config setting: stripePayments. You can set custom config settings from config/custom.php.'
```

### Steps to reproduce

1. Update `craftcms/cms` from `3.7.45.2` to `^4.0.0`
2. Update `enupal/stripe` from `4.0.4` to `5.1.1`
3. Run `php craft migrate/all`

### Additional info

- Craft version: ^4.0.0
- PHP version: 8.1
- Database driver & version: MySQL 5.7.39
- Plugin version: 5.1.1

**Comment by romainpoirier** [comment]
After reading [this](https://docs.enupal.com/stripe-payments/getting-started/saving-your-stripe-api-keys.html#saving-the-stripe-api-keys-via-config-file) from the plugin doc, I've created the `config/custom.php` file but I'm still getting the same error.

I've tried to rename the `custom.php` file to match the plugin name (`stripe.php`), but without any change. How to fix this?

**Comment by andrelopez** [comment]
Hi @romainpoirier yes this is documented [here](https://docs.enupal.com/stripe-payments/getting-started/saving-your-stripe-api-keys.html#saving-the-stripe-api-keys-via-config-file). Thank you
