### ISSUE TITLE
Error "Base table or view not found: 1146 Table 'x.matrixcontent_enupalmultipleplans' doesn't exist" while adding new payment forms after project config change/update.

### ISSUE THREAD

**Issue by DarrenLumber** [enupal/stripe#356]
### Description
After installing plugin and setting up forms, new changes to the project config file seems to remove the `matrixcontent_enupalmultipleplans` table from the database. This is results with an errors while viewing a template containing the form or adding new forms via the control panel. This only appears to be an issue in environments that have `allowAdminChanges` set to false.

In our case, after installing and configuring in a dev environment with  `allowAdminChanges` set to true and then deploying to a staging environment where `allowAdminChanges` are set to false, subsequent deployments to that environment where by the project files involve an update results in the issue occurring. Reviewing the merged commits bare no evidence that the plugin should have been altered in any way.

### Steps to reproduce

1. Install plugin and configure (where `allowAdminChanges` is allowed)
2. Deploy changes to an environment that has `allowAdminChanges` set to false.
3. Add payment form in the new environment
4. Make a change that updates the project file (where `allowAdminChanges` is allowed)
5. Merge and deploy change to the environment that has `allowAdminChanges` set to false
6. Attempt to add a new payment form (results in "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'x.matrixcontent_enupalmultipleplans' doesn't exist" error)

### Additional info

- Craft version: 4.3.4
- PHP version: 8.1.20
- Database driver & version: MySQL 10.6.14
- Plugin version: 5.1.2
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @DarrenLumber 

I was unable to recreate this issue. After some deep research, I think the issue is related on how you deploy the changes to the new env. Following this [guide](https://craftcms.com/knowledge-base/deployment-best-practices), could you please make sure you're running the following commands:

```sh
php craft update/composer-install --interactive=0
php craft migrate/all --no-content --interactive=0
php craft project-config/apply
php craft migrate --track=content --interactive=0
```

The most important command is `php craft project-config/apply` could you please make sure this is executed as part of your CI/CD process?

**Comment by andrelopez** [comment]
Hi @DarrenLumber I was able to recreate this issue. Please update your plugin to v5.2.0 now your changes will be propagated to your prod envs. Please let me know if you still have issues

**Comment by pimago** [comment]
I have the same or at least similar issue. I cannot add or edit forms unless I change to production.
I have v5.2.0 installed

**Comment by andrelopez** [comment]
Hi @pimago this may be an issue from prev version, we can help to fix to issue. Could you please send me a copy of the db to support@enupal.com from the env where the plugin is working?

**Comment by pimago** [comment]
Did you have time to look into it?
