### ISSUE TITLE
Multiple issues with subscriptions

### ISSUE THREAD

**Issue by aelvan** [enupal/stripe#36]
### Description

We just went live with a subscription website using Checkout and I'm seeing a bunch of very weird issues, not sure if they're related or not, but kinda feels like it: 

1) We have set up 25% tax, but only about half of the subscriptions haven't had tax added to them.

2) A lot of the incoming invoices are being marked as "Scheduled", while others are paid immediately. Some have tax, som don't. 

3) Not all orders are showing up in stripe payments in the control panel. None of the scheduled ones, but also some of the ones that are paid.

Somehow, this feels kinda related, like a lot of requests are just being partly completed? Any idea what the issue could be? 

### Additional info

- Craft version: 3.1.33
- PHP version: 7.2.19
- Database driver & version: MySQL 8.0.16
- Plugin version: 1.9.5

**Comment by andrelopez** [comment]
Hi @aelvan 

Stripe Payments will only register the first Order info (when the user is subscribed). In the plugin, you can't see the invoices. However, you can get the [subscription status](https://stripe.com/docs/billing/lifecycle#subscription-states) and there is also [webhooks](https://enupal.com/craft-plugins/stripe-payments/docs/plugin-development/events#afterprocesswebhook) to get notified for when a subscription is canceled.

Could you please send us a screenshot of the `Stripe Reference` link from one of the orders that are missing the tax in the upcoming invoices? Please send the screenshot to: support@enupal.com

**Comment by andrelopez** [comment]
The confusion was due to older subscriptions.
