### ISSUE TITLE
Unable to change the quantity of a product in twig

### ISSUE THREAD

**Issue by tomfischerNL** [enupal/stripe#361]
### Description

Hi @andrelopez,

My client has the option to add multiple persons to a payment (i.e. "For how many persons do you want to pay"). So I need the paymentForm quantity to be adjustable. But I cant change the quantity after initializing the form. Even not when I'm adding the adjustable quantity.

Can you let me know how I can do this?

```
{% set paymentOptions = {
    checkoutSuccessUrl: currentUrl ~ '/thanks?o={number}',
    checkoutCancelUrl: currentUrl ~ '?a=canceled',
        removeDefaultItem: true,
            lineItems : [
                {
                    "price": entry.stripePriceId,
                    "quantity": 1,
                    "adjustable_quantity": {
                        "enabled": true,
                        "minimum": 1,
                        "maximum": 10
                    }
                }
            ]
    } 
%}
{{ craft.enupalStripe.paymentForm('form', paymentOptions) }}
```

Thanks! :)

### Additional info

- Craft version: 4.4.10.1
- PHP version: 8.1.18
- Plugin version: 5.0.9
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: yes

**Comment by andrelopez** [comment]
Hi @tomfischerNL 

I was unable to recreate your issue. Are you able to see the `qty` dropdown? 

<img width="512" alt="Screenshot 2023-08-02 at 7 24 32 pm" src="https://github.com/enupal/stripe/assets/875476/feb2c2be-a885-4930-8872-8730c7da7060">

**Comment by andrelopez** [comment]
closing for now, feel free to re-open
