### ISSUE TITLE
Add multiple subscriptions to cart

### ISSUE THREAD

**Issue by hassanmah** [enupal/stripe#366]
Hi,

Is it possible to add multiple subscriptions to the cart using the Cart API? See example below

I want to add two subscriptions - Parking Spot 1 and Parking Spot 2 and pay for them in one go

Thanks

**Comment by andrelopez** [comment]
Hi @hassanmah Yes, the Cart API accepts One-Time items and Recurring (subscription) items at the same cart session, however, if you're adding more than one recurring item, all the intervals (daily, monthly, yearly, etc), and currencies should be the same

Please find full docs here: https://docs.enupal.com/stripe-payments/pro/cart-api.html
