### ISSUE TITLE
Stripe Commerce Clash

### ISSUE THREAD

**Issue by malcolmhmaclean** [enupal/stripe#367]
### Description

I am just upgrading my clients site and have upgraded all plugins including Commerce-Stripe up to v3.1.1. I want to upgrade to v4.0.0 for commerce-stripe but the stripe-php versions seem to clash-  is there any plans to upgrade to v10 at all?

$ composer update
You made a reference to a non-existent script @pre-craft-update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires craftcms/commerce-stripe 4.0.0 -> satisfiable by craftcms/commerce-stripe[4.0.0].
    - You can only install one version of a package, so only one of these can be installed: stripe/stripe-php[v7.0.0, ..., v7.128.0, v8.0.0, ..., v8.12.0, v9.0.0, ..., v9.9.0, v10.0.0, ..., v10.21.0].
    - enupal/stripe[5.1.1, ..., 5.3.1] require stripe/stripe-php ^7.0 -> satisfiable by stripe/stripe-php[v7.0.0, ..., v7.128.0].
    - craftcms/commerce-stripe 4.0.0 requires stripe/stripe-php ^10.0 -> satisfiable by stripe/stripe-php[v10.0.0, ..., v10.21.0].
    - Root composer.json requires enupal/stripe ^5.1.1 -> satisfiable by enupal/stripe[5.1.1, ..., 5.3.1].

**Comment by andrelopez** [comment]
Hi @malcolmhmaclean we just released Stripe Payments v5.4.0 with support to `stripe-php` v10. Thanks for reporting
