### ISSUE TITLE
Upgraded to 3.2 and getting an error "At least one block type is required."

### ISSUE THREAD

**Issue by sunscreem** [enupal/stripe#37]
### Description

Just upgrade a site to 3.2.6 & the latest version of this plug in (1.9.8). All seemed fine (testing on the front end and test payments going through no problem).

Only issue is when I access any payment form either and existing one or a new one I get:

![image](https://user-images.githubusercontent.com/7523595/62057385-7943f700-b217-11e9-9f38-886dba0b4823.png)

(My local url when this error comes up is http://clientdomain.test/admin/enupal-stripe/forms/edit/3607)

### Steps to reproduce

1. In the dashboard, create or edit a payment form.

### Additional info

- Craft version: 3.2.7
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7.27
- Plugin version: 1.9.8

**Comment by andrelopez** [comment]
Hi @sunscreem 

Could you please tell us from what version you upgraded Craft CMS? Are you able to share the database before the upgrade? If so please send the db to support@enupal.com

**Comment by sunscreem** [comment]
Hi @andrelopez I uninstalled the plug in, re installed and everything seems okay now.

Looks like there are migrations that needed to be ran but it could be more of an issue at our end due to the way in which we did the 3.2 upgrade, so I'll close this as its probably not worth investigating further. Thanks anyway.

**Comment by mijewe** [comment]
I am also having this issue.

I installed the plugin locally (on Craft 3.3.18.1).
Then when running a project-config/sync on the staging environment, it failed to complete the migration. The message was:
"
The following config paths could not be processed successfully:
matrixBlockTypes.bb46e506-aed5-47ba-b8b4-94084cc0d63a
matrixBlockTypes.57e19050-8d5c-432f-b9c3-907a9f58b810
matrixBlockTypes.2093387a-da39-431d-8d95-69bbd47488f9
matrixBlockTypes.da481973-0b12-4a1a-9384-be9b8a664867
"

(This is also the case having upgraded to Craft 3.4.1)

As a result of the failed migration (I assume), I now can't add or edit a Payment Form. On /admin/enupal-stripe/forms/new I get the message "At least one block type is required." as per @sunscreem 's screenshot.

Enabling the plugin manually on the staging site works, but then syncing the project config back into my local environment fails with the same migration issue.

Any ideas, or any more useful information I can share?

**Comment by andrelopez** [comment]
I have reported a bug on Craft CMS here craftcms/cms#6161

**Comment by andrelopez** [comment]
Hi, we just release Stripe Payments v2.7.0 with a fix to this issue. Please let us know if that works.

Please follow the next instructions:
* From your primary environment, update Stripe Payments to v2.7.0
* remove the `config/project.yaml` (we'll rebuild it on next steps)
* Uninstall the plugin
* Install the plugin
* run `php craft project-config/rebuild`

The project config file should be fixed. Please let us know if it works.

**Comment by Coysh** [comment]
Hi @andrelopez - I've set `allowAdminChanges` to false on my primary environment. But uninstalling the plugin is failing, as `afterUninstall()` is calling `Craft::$app->projectConfig->rebuild();`

Stack trace:
```
yii\base\ErrorException: Undefined index:  in .../vendor/craftcms/cms/src/services/ProjectConfig.php:2161
Stack trace:
#0 .../vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '.../', 2161)
#1 .../vendor/craftcms/cms/src/services/ProjectConfig.php(2161): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '.../', 2161, Array)
#2 .../vendor/craftcms/cms/src/services/ProjectConfig.php(1793): craft\services\ProjectConfig->_getMatrixBlockTypeData()
#3 .../vendor/craftcms/cms/src/services/ProjectConfig.php(1142): craft\services\ProjectConfig->_getCurrentStateData()
#4 .../vendor/enupal/stripe/src/Stripe.php(121): craft\services\ProjectConfig->rebuild()
#5 .../vendor/craftcms/cms/src/base/Plugin.php(175): enupal\stripe\Stripe->afterUninstall()
#6 .../vendor/craftcms/cms/src/services/Plugins.php(597): craft\base\Plugin->uninstall()
#7 .../vendor/craftcms/cms/src/controllers/PluginsController.php(90): craft\services\Plugins->uninstallPlugin('enupal-stripe')
#8 [internal function]: craft\controllers\PluginsController->actionUninstallPlugin()
#9 .../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 .../vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 .../vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('uninstall-plugi...', Array)
#12 .../vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('uninstall-plugi...', Array)
#13 .../vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('plugins/uninsta...', Array)
#14 .../vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('plugins/uninsta...', Array)
#15 .../vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 .../vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 .../public/index.php(17): yii\base\Application->run()
#18 {main}
```

**Comment by shornuk** [comment]
@Coysh - did you fix this? I'm getting the exact same issue. Matrix block errors from production env, and cannot uninstall locally with Undefined index: error.

@andrelopez - any ideas?
