### ISSUE TITLE
Error: You must provide at least one recurring price in `subscription` mode when using prices.

### ISSUE THREAD

**Issue by tomfischerNL** [enupal/stripe#370]
### Description
When using the checkout tag, we get an error:

"You must provide at least one recurring price in `subscription` mode when using prices." 

### Steps to reproduce

1. Make a new one-time payment in Stripe (see attachment)
2. Use the checkout tag.

<img width="665" alt="Scherm­afbeelding 2023-10-30 om 15 22 04" src="https://github.com/enupal/stripe/assets/2330195/feb3d823-5fc4-41c3-8fd9-5c3a95e0d144">
<img width="658" alt="Scherm­afbeelding 2023-10-30 om 15 22 38" src="https://github.com/enupal/stripe/assets/2330195/7102fda9-c2a6-466b-9b8c-8ddaef471878">
<img width="1535" alt="Scherm­afbeelding 2023-10-30 om 15 21 22" src="https://github.com/enupal/stripe/assets/2330195/b4f1135f-99f5-4826-bd4e-59fc0b340df3">

### Additional info

- Craft version: 4.5.2
- Plugin version: 5.3.1

**Comment by andrelopez** [comment]
Hi @tomfischerNL could you please make sure the product associated with this product has the `enupal-sync` = `1` metadata on the Stripe dashboard?

Also, please make sure that the products are synced under `Stripe Payments -> Settings -> Products Sync `
and are correctly displayed under `Stripe Payments -> Products `

**Comment by tomfischerNL** [comment]
Hi @andrelopez,

I already synced the products, and added the enupal-sync. Still the same error.
The product is visible at:  `Stripe Payments -> Products`

<img width="1205" alt="Scherm­afbeelding 2023-10-30 om 17 18 57" src="https://github.com/enupal/stripe/assets/2330195/23453191-811a-4ae0-8012-d827d8a30f6a">

**Comment by tomfischerNL** [comment]
When adding a "recurring" price in Stripe, the page works. But not with a "default" one-time payment.
<img width="829" alt="Scherm­afbeelding 2023-10-30 om 17 38 46" src="https://github.com/enupal/stripe/assets/2330195/223b9691-edbe-4379-a429-ac0c6afa7a25">

**Comment by tomfischerNL** [comment]
I just updated to the newest version 5.5.0 version and now the bugs seems to be fixed. I think we had something changed before:

```
 'mode' => 'subscription' // set manually to subscription for licenses in stripe
 'mode' => $mode

```

I will close this error
