### ISSUE TITLE
Apply percentage discount to options

### ISSUE THREAD

**Issue by mark-chief** [enupal/stripe#373]
### Description
How can I apply a flat 20% discount to the cart? I have tried to add it as a negative line item but stripe doesn't allow negatives.

I have also tried adjusting the total in the options but it still calculates the total base don the lineitems.

```
{% if loop.first and discountPercentage > 0 %}

{% set lineItems = lineItems|merge([{
name : 'Volume Discount -'~ discountPercentage ~'%',
amount :  discountAmount|number(decimals=2)|replace('.',''),
currency : 'gbp',
quantity : 1,
}]) %}

{% set lineItems = lineItems|merge([{
name : entry.title,
description : 'Price Inc. VAT',
amount : lineItemPrice|number(decimals=2)|replace('.',''),
currency : 'gbp',
quantity : 1,
}]) %}

{% else %}

{% set lineItems = lineItems|merge([{
name : entry.title,
description : 'Price Inc. VAT',
amount : lineItemPrice|number(decimals=2)|replace('.',''),
currency : 'gbp',
quantity : 1,
}]) %}

{% endif %}

{% endfor %}								 

{% set options = {
amount: discountedPriceIncVat, 
quantity: completedEntriesCounter, 
itemName : currentUser.firstName ~ ' ' ~ currentUser.lastName,
itemDescription : 'Test Description',
checkoutSuccessUrl: '/account/manage-entries?msg=order-success',
checkoutCancelUrl: '/account/manage-entries',
removeDefaultItem: true,   
allowPromotionCodes : true, 
lineItems: lineItems, 
calculateFinalAmount: false,
} %}
```
`calculateFinalAmount: false,` doesnt appear to work, if I think I know what its supposed to do.. but no info in docs on that

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugin version:
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by andrelopez** [comment]
Hi @mark-chief you can use the [beforeCreateSession](https://docs.enupal.com/stripe-payments/plugin-development/events.html#beforeprocesstransfer) Event If you want to create a session with an applied discount ([docs](https://stripe.com/docs/payments/checkout/discounts#coupons)), if your custom module/plugin you may need something like:

```php
use enupal\stripe\services\Checkout;
use enupal\stripe\events\CheckoutEvent;
use enupal\stripe\Stripe;
use craft\base\Plugin;
use Craft;

class YourPlugin extends Plugin
{
    public function init()
    {
        ....
        ....
     
         Event::on(Checkout::class, Checkout::EVENT_BEFORE_CREATE_SESSION, function(CheckoutEvent $e) {
              $isCart = $e->isCart;
              $sessionParams = $e->sessionParams;
              //overwrite $sessionParams
              $sessionParams['discounts'] = [['coupon' => 'COUPON_ID']];
              $e->sessionParams = $sessionParams;
         });
        ...
        ...        
     }
}   
```

You have full control here about your checkout session, here the [stripe docs](https://stripe.com/docs/api/checkout/sessions/create) with all the properties you can overwrite
