### ISSUE TITLE
Support for Strong Customer Authentication

### ISSUE THREAD

**Issue by domstubbs** [enupal/stripe#38]
Am I right in thinking this plugin doesn’t yet support [SCA](https://stripe.com/docs/strong-customer-authentication) via the [payment intents API](https://stripe.com/docs/payments/payment-intents/quickstart)? If not, is that likely to be added before SCA kicks in in mid-September?

I’m not actually using the plugin yet. I have a Craft 2 + Charge project and I need to figure out which migration route will be the least painful. Since this plugin offers syncing for old orders that sounds promising.

Thanks.

**Comment by andrelopez** [comment]
Hi @domstubbs 

We're currently working on adding support for SCA, I have added you to the notify list for when is released.

Duplicated of https://github.com/enupal/stripe/issues/32

**Comment by domstubbs** [comment]
Thanks - sorry for missing the existing issue.
