### ISSUE TITLE
Checkout link - JS

### ISSUE THREAD

**Issue by malcolmhmaclean** [enupal/stripe#381]
Hi 

I am just using the checkout link (https://docs.enupal.com/stripe-payments/pro/checkout.html)  - i am using it for quick checkout for a list of products. is there any way NOT to render the checkout JS tag with every product? (its slowing the page)

Malcolm

**Comment by andrelopez** [comment]
Hi @malcolmhmaclean you may want to do a 2 steps checkout process: on the first page you only list all the products and when the user selects the product you can redirect to the final checkout page where you can display the payment checkout link, so only load once the checkout session (call the Stripe API) only once and will be faster. Hope that helps!
