### ISSUE TITLE
Google chrome refresh with the same link instead of stripe gateway

### ISSUE THREAD

**Issue by allion-randika** [enupal/stripe#383]
### Description

I am using Stripe with CraftCms 4 with a twig template. And also, I am in the test environment and using a Stripe payment one-code line handle. The issue is with Google Chrome. It's working fine in Mozilla Firefox. Once I click that payment button, the page refreshes with a POST request.

### Additional info

- Craft version: 4
- Plugin version: 5.5

**Comment by andrelopez** [comment]
Hi @allion-randika could you please recreate the issue and send back to us a zipfile of storage/logs to support@enupal.com?

**Comment by allion-randika** [comment]
Sure I will send, thanks for the reply

**Comment by allion-randika** [comment]
> Hi @allion-randika could you please recreate the issue and send back to us a zipfile of storage/logs to [support@enupal.com](mailto:support@enupal.com)?

I have sent a mail, Do you have any idea about this?
