### ISSUE TITLE
Craft CMS 5 compatibility

### ISSUE THREAD

**Issue by vonscriptor** [enupal/stripe#385]
Hello! Are there plans and a timeline for upgrading the plugin for Craft CMS 5 compatibility?

Reference: https://craftcms.com/docs/5.x/extend/updating-plugins.html

**Comment by andrelopez** [comment]
Hi @vonscriptor Support for Craft 5 is coming soon!

**Comment by vonscriptor** [comment]
Great to hear! Thanks!

**Comment by andrelopez** [comment]
Hi @vonscriptor we just released Stripe Payments v6.0.0 with support for Craft5 please let me know if you get any issues on the upgrade!
