### ISSUE TITLE
Using multiple Stripe accounts with a multisite craft setup

### ISSUE THREAD

**Issue by josdigital** [enupal/stripe#395]
Hello, do you know if the current version of the plugin supports using multiple Stripe accounts? I have a client that has a multisite craft installation and would like to have each site work with a different Stripe account (so orders and subscriptions should go to different Stripe accounts for each site).

I tried setting the stripePayments array in the custom.php file to use different keys for each site (each site corresponding to a different Stripe acccount).  It actually worked (had to set the right webhook url for each site on Stripe using the Stripe test environment) and the orders are saved correctly using their respective payment form handle.

The custom.php file looks like this:

```
 'stripePayments' => [
        'testPublishableKey' => Craft::$app->sites->getCurrentSite()->handle == 'SITE_A' ? getenv('STRIPE_TEST_PUBLISHABLE_KEY_SITE_A') : getenv('STRIPE_TEST_PUBLISHABLE_KEY_SITE_B'),
        'testSecretKey' => Craft::$app->sites->getCurrentSite()->handle == 'SITE_A' ? getenv('STRIPE_TEST_SECRET_KEY_SITE_A') : getenv('STRIPE_TEST_SECRET_KEY_SITE_B'),
        'testMode' => $isDev,
    ],
```

Do you think that this could work or you see any weak point and it will result in issues in the long term? 

Thank you.

**Comment by andrelopez** [comment]
Hi @josdigital this looks good to me! let me know if you get any issues

**Comment by iamtompickering** [comment]
@andrelopez @josdigital did this set up end up working out okay for you? 

I am trying something a quite similar to this, but targeting a Craft session which I'm dynamically updating e.g. 

```
<?php

    use craft\helpers\App;

    $currency = Craft::$app->session->get('currency');

    $currencyKeys = [
        'GBP' => [
            'testPublishableKey' => App::env('STRIPE_PUBLISHABLE_KEY'),
            'testSecretKey' => App::env('STRIPE_SECRET_KEY'),
            'livePublishableKey' => App::env('STRIPE_PUBLISHABLE_KEY'),
            'liveSecretKey' => App::env('STRIPE_SECRET_KEY'),
        ],
        'USD' => [
            'testPublishableKey' => App::env('STRIPE_US_PUBLISHABLE_KEY'),
            'testSecretKey' => App::env('STRIPE_US_SECRET_KEY'),
            'livePublishableKey' => App::env('STRIPE_US_PUBLISHABLE_KEY'),
            'liveSecretKey' => App::env('STRIPE_US_SECRET_KEY'),
        ],
    ];

    return [
        '*' => [
            'env' => App::env('ENVIRONMENT'),
            'stripePayments' => [
                'testPublishableKey' => $currencyKeys[$currency]['testPublishableKey'],
                'testSecretKey' => $currencyKeys[$currency]['testSecretKey'],
                'livePublishableKey' => $currencyKeys[$currency]['livePublishableKey'],
                'liveSecretKey' => $currencyKeys[$currency]['liveSecretKey'],
            ]
        ],
        ]
    ];
```

It seems to be working to some extent, but there appears to be a few issues. 

I can see that the correct Stripe API keys are being used at checkout, and testing both UK + US, test payments are going through successfully. 

However, when checking out with the US API keys, I am not returned to the checkout success URL, and the order is also not creating in the CMS admin. I can see the payment is successful in my Stripe account, but it looks like there are a few pending Webhooks. 

Can you think of any reason why this would be, and any workaround for it?
