### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by DavidKabelitz** [enupal/stripe#399]
### Description
Website is down, js files can't be loaded. Is the Company shut down?

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugin version:
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by vonscriptor** [comment]
Hoping not! 😅 The site's SSL certificate recently expired and why it might appear as though it's not available.

**Comment by andrelopez** [comment]
Thanks for reporting, the issue will be solved soon🙌🏽

**Comment by andrelopez** [comment]
The issue is now fixed in the website and docs. Thank you for reporting
