### ISSUE TITLE
Two different forms on same template won't work.

### ISSUE THREAD

**Issue by maddyBoy** [enupal/stripe#40]
### Description
I am trying to show two different subscription forms on the same page, i.e one with card option and another with checkout.
But it shows error.

![Screenshot from 2019-09-03 17-25-53](https://user-images.githubusercontent.com/26545067/64171292-ef1f2c00-ce6f-11e9-8b5c-1b42217d7cd3.png)

### Steps to reproduce

1.create two form one with card option another with checkout process
2. Call the forms on a single template and try to use them both.

### Additional info

- Craft version:3.3
- PHP version:7.0
- Plugin version:2.0.1

**Comment by codeartaus** [comment]
I'm getting the same error, though its happening for me when two forms are in the system – regardless of if they're being used on the same page or not.

I can make a form work by:

1. Opening a form in Plugin Backend
2. Saving form (without making changes)

This then breaks all other forms site-wide, except for the one that was re–saved

Craft version: Craft Pro 3.3.15
PHP version: 7.0.33
Plugin version: 2.1.2

**Comment by andrelopez** [comment]
Hi @codeartaus your issue looks different, could you please review your templates and make sure that your `{{ craft.enupalstripe.paymentForm('paymentForm') }}` it's outside of any `{% cache %}` tag?

**Comment by andrelopez** [comment]
We just released v2.1.3 with a fix to this issue.
