### ISSUE TITLE
Can plugin work with a card reader?

### ISSUE THREAD

**Issue by dbrown199747** [enupal/stripe#400]
### Description
My client would like to go to events and sell their product with a card reader. Is there anyway to integrate the card reader with the stripe checkout that the plugin uses? Or anyway the plugin will work with a card reader instead of entering your card details into the strip checkout page that the plugin takes you to make a payment?

I'm pretty new to this so any advise would be welcome! Thanks.

### Additional info

- Craft version: Craft Pro 4.8.8
- PHP version: 8.2.0
- Database driver & version: MySQL 5.7.39
- Plugin version: 5.5.2
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @dbrown199747 I think this will be a better question for [Stripe Support](https://stripe.com/gb/contact) let me know what you hear from them
