### ISSUE TITLE
Wrong language code for Norwegian

### ISSUE THREAD

**Issue by aelvan** [enupal/stripe#41]
### Description

When selecting "Norwegian" in the language selector, Stripe throws an error during the `enupal/stripe/create-checkout-session` controller action:

"Invalid locale: must be one of auto, da, de, en, es, fi, fr, it, ja, nb, nl, pl, pt, sv, or zh"

The language selector sets the locale to `no` (which is the ISO country code), while the language code for Norwegian is `nb`.

### Steps to reproduce

1. Create a new payment form using Stripe Checkout.
2. Select Norwegian as language.
3. Output form in template and click to pay.

Error is shown in the JS console.

### Additional info

- Craft version: 3.3.1.1
- PHP version: 7.3.8
- Database driver & version: Mysql 5.7.26
- Plugin version: 2.0.3

**Comment by andrelopez** [comment]
Hi @aelvan we just released Stripe Payments v2.0.4 with a fix to this issue.

Thanks for reporting.
