### ISSUE TITLE
Order not available in customer.subscription.created webhook

### ISSUE THREAD

**Issue by aelvan** [enupal/stripe#44]
### Description

Not sure if this is a bug or not, but when listening for webhook events, `$event->order` is not set for `customer.subscription.created`/`customer.subscription.update` (and most other events). I've resorted to listening for `checkout.session.completed`, and checking that it's a subscription I'm receiving the event for. Which may be the correct way, but I got a bit thrown off-track by the example here:

https://enupal.com/craft-plugins/stripe-payments/docs/plugin-development/events#afterprocesswebhook

Since the check for `customer.subscription.created` is inside `if ($order)`, it will never be run. If this is not a bug, I think the example should be updated. 

### Steps to reproduce

(same use-case and setup as my other issues today)

### Additional info

- Craft version: 3.3.1.1
- PHP version: 7.3.8
- Database driver & version: Mysql 5.7.26
- Plugin version: 2.0.3

**Comment by andrelopez** [comment]
Hi @aelvan 

Good catch, Stripe sends the `customer.subscription.created` webhook before `checkout.session.completed` (where we create the order). I have updated the docs explaining this scenario. 
Thank you!
