### ISSUE TITLE
[SCA] Can we use SCA with Stripe Elements?

### ISSUE THREAD

**Issue by wiegerjelsma** [enupal/stripe#47]
Hi Andre,

Is it possible to use SCA with Stripe Elements? 
I need the iDeal payment method activated as well.

Hop you can help. 
Thanks in advance,

Wieger

**Comment by andrelopez** [comment]
Hi @wiegerjelsma 

That feature is currently in development, you can track the progress [here](https://github.com/enupal/stripe/issues/32)

What do you think if we add the new Stripe Checkout option in the Payment Method dropdown?

Fyi, Stripe is working to add support to choose the payment method (iDEAL, SOFORT) in the new Stripe Checkout, but there is no ETA

**Comment by andrelopez** [comment]
Hi @wiegerjelsma the new Stripe Checkout now accepts iDEAL (only one-time payments) and Cards please feel free to update to the latest version to use this feature.

Best,
