### ISSUE TITLE
Form not working at all

### ISSUE THREAD

**Issue by Coysh** [enupal/stripe#48]
### Description
I'm migrating across from `lukeyouell/craft-stripecheckout` as the plugin is dead, and we need support for SCA.
No matter what I do, I can't get this plugin to work.
I've set up a payment and am displaying it on the frontend as follows:

`{% set options = {amount: payment_amount, quantity: 1, calculateFinalAmount: true} %}
{{ craft.enupalstripe.paymentForm('buySent', options) }}`

The "Pay by card" button shows, but if I click it - I get a **Unable to process the Payment** error.

I've noticed that in the amount/token fields arn't being populated, as you can see - but can't work out why.
![image](https://user-images.githubusercontent.com/5764356/64791891-5162e580-d570-11e9-9b25-b1fd7ed56aab.png)

I've got SCA enabled, and trying to use Stripe checkout

### Additional info

- Craft version: 3.3.1.2
- PHP version: 7.2
- Database driver & version: mySQL 5.7.20
- Plugin version: 2.0.6

**Comment by andrelopez** [comment]
The issue was due to a wrong display of the `{{ craft.enupalstripe.paymentForm('handle', options) }}` tag was inside of a `<form>` tag
