### ISSUE TITLE
Cannot get plug in working on windows. Works fine on mac.

### ISSUE THREAD

**Issue by sunscreem** [enupal/stripe#49]
### Description

I've spent the entire day trying to understand why, when a colleague installs this plug in, the migrations all run correctly but do not for me.

The only difference (same codebase, same database) is I'm on windows (Laravel Homestead) and he's on Mac (using Laravel Valet).

We are both on the same versions of mysql & php.

The problem seems to be that the plug in just refuses to create the field_subscriptionPlan_ * fields.

![image](https://user-images.githubusercontent.com/7523595/64798826-8de80e80-d57b-11e9-8f10-96866c62d80a.png)

That screen grab is from my friends matrixcontent_enupalmultipleplans table.

This screen grab is from mine. 

![image](https://user-images.githubusercontent.com/7523595/64798617-3a75c080-d57b-11e9-8b71-029c32931ff5.png)

I can't work out in the source code why this isn't working.

I've checked the error logs, I've scrutinized the mysql queries, I've dived into the source as much as I can and I can't work it out.

### Additional info

- Craft version: 3.2.9
- PHP version: PHP 7.3.8-1+ubuntu18.04.1+deb.sury.org+1 (cli
- Database driver & version: 8.0.17 - MySQL Community Server - GPL
- Plugin version: 2.0.6

This is related to #37 - which gives you an idea of how long and how frustrating I've found this problem. ANY help appreciated.

**Comment by andrelopez** [comment]
Hi @sunscreem Could you please confirm if you have enabled the `useProjectConfigFile` in the config/general.php file? I believe that it could be a possible bug related to that setting.

**Comment by sunscreem** [comment]
Hey. Yeah - thats enabled.

**Comment by andrelopez** [comment]
I have reported a bug on Craft CMS here craftcms/cms#6161

**Comment by andrelopez** [comment]
Hi, we just release Stripe Payments v2.7.0 with a fix to this issue. Please let us know if that works.

Please follow the next instructions:
* From your primary environment, update Stripe Payments to v2.7.0
* remove the `config/project.yaml` (we'll rebuild it on next steps)
* Uninstall the plugin
* Install the plugin
* run `php craft project-config/rebuild`

The project config file should be fixed. Please let us know if it works.
