### ISSUE TITLE
Payments going through successfully in Stripe, but order not created

### ISSUE THREAD

**Issue by iamtompickering** [enupal/stripe#51]
### Description
I have setup a payment form and when checking out via Stripe Checkout, the order for the payment is not being created. I am running the site on a staging URL, have setup the webhook in my Stripe account, updated to the latest Stripe API version and have SCA turned on.

The test payments are actually going into my Stripe account as successful payments and the order details are all correct. I noticed in the logs the following error: 

`2019-09-20 11:35:02 [-][-][-][error][enupal\stripe\controllers\StripeController::actionFinishOrder] Unable to find the order by stripe id: Stripe\Charge JSON: {`

I have SCA option turned on in the general settings. So I'm guessing the issue is something to do with the fact it is calling `Stripe\Charge` rather than Payment Intents...

### Additional info

- Craft version: 3.3.4.1
- PHP version: 7.0
- Database driver & version: mySQL 5.7.20
- Plugin version: 2.1.1

**Comment by andrelopez** [comment]
Hi @iamtompickering Could you please recreate the issue and send back to us a zip file of the following folder?
`storage/logs`

Please send the file to suppor@enupal.com

**Comment by iamtompickering** [comment]
@andrelopez just emailed you now.

**Comment by andrelopez** [comment]
The issue was related to the missing `checkout.session.completed` event type in the Webhook URL of the Stripe dashboard.
