### ISSUE TITLE
Stripe Elements: How do I handle errors?

### ISSUE THREAD

**Issue by adrienne** [enupal/stripe#52]
### Description

Any errors in payment info (card declined, etc) cause a thrown exception. I need to be able to actually handle these errors for the user -- is that possible?

![image](https://user-images.githubusercontent.com/89705/67337978-f90ef400-f4dc-11e9-96e1-3c659e19376e.png)

### Steps to reproduce

1. Set up a Payment form in Elements mode (with Stripe Checkout deselected)
2. Set Stripe to Test Mode
3. Use the following test card to trigger a "card declined" error: 4000 0000 0000 0002

### Additional info

- Craft version: 3.3.11
- PHP version: 7.2.21
- Database driver & version: MySQL 5.7.27
- Plugin version: 2.1.1

**Comment by meinhard-meintjes** [comment]
Any updates on this request? Thanks.

**Comment by andrelopez** [comment]
We added support to display payment errors in v2.1.3. [More info](https://enupal.com/craft-plugins/stripe-payments/docs/templating/display-errors)

Thanks for reporting

**Comment by meinhard-meintjes** [comment]
Thank you, perfect timing

**Comment by adrienne** [comment]
@andrelopez - I cannot get this to work with 2.1.3 of Payments. I have tried following the directions here. https://enupal.com/craft-plugins/stripe-payments/docs/templating/display-errors

**Comment by andrelopez** [comment]
Hi @adrienne Could you please send back to us your templates to support@enupal.com ?
