### ISSUE TITLE
Doesn't work on IE11 - looks to be loading JS from 'cpresources'

### ISSUE THREAD

**Issue by sunscreem** [enupal/stripe#53]
### Description

Bugsnag was telling that IE11 users were unable to make payments. The console shows the following error:

```
SCRIPT1003: Expected ':'
enupal-stripe.min.js (7,1583)
```

Hard to work out where the problem is as IE is horrible at expanding minified script.

I have noticed that the script in question is loading from:

/cpresources/7841fd1e/stripe/js/enupal-stripe.min.js?v=1568785052

Which seems odd that cp resource script load in the front end? Maybe that's how craft works?

Either way - I think the script needs transpiled for IE11?

### Steps to reproduce

1. Visit this page in IE11: https://icota-mena.com/join-icota
2. Open console.

### Additional info

- Craft version: 3.2.9
- PHP version: 7.3.10
- Database driver & version: MYSQL 8.0.17
- Plugin version: 2.1.1

**Comment by madebyspark** [comment]
This happens in IE11 for me as well.

**Comment by andrelopez** [comment]
We just released Stripe Payments v2.1.3 with a fix to this issue. 

Thanks for reporting
