### ISSUE TITLE
Docs aren't working on enupal website

### ISSUE THREAD

**Issue by sunscreem** [enupal/stripe#54]
![image](https://user-images.githubusercontent.com/7523595/68790846-03d22a00-0640-11ea-9546-13b21668f706.png)

The website needs some TLC. I can't access the menu :(

**Comment by benface** [comment]
I'm also seeing this on all pages where the menu is taller than the page's content. Very annoying!

**Comment by andrelopez** [comment]
Hi, we just migrated our docs to use vuepress with a new subdomain https://docs.enupal.com/stripe-payments/

Please feel free to report any 404 error from old links here

Thanks!

**Comment by benface** [comment]
The new docs are so much better!
