### ISSUE TITLE
Unable to set variables

### ISSUE THREAD

**Issue by madebyspark** [enupal/stripe#55]
### Description
Trying to set variables based upon a user's order history so that we can lock down site content based upon a user's subscription status... 

```
{% for order in craft.enupalStripe.getSubscriptionsByUser(currentUser.id) %}
  {% set subscription = order.getSubscription() %}
  {% if subscription.status == 'active' %}
	{% set subscriptionCheck = "Y" %}
	{% set subscriptionNumber = order.number %}
  {% endif %}
{% endfor %}
```

If I later check for the `subscriptionCheck` variable, I get an error saying that it doesn't exist, even when the user has an active subscription. 

### Additional info

- Craft version: 3.3.11
- PHP version: 7.2.21
- Database driver & version: Mysql 5.7
- Plugin version:  2.1.1

**Comment by andrelopez** [comment]
Hi @madebyspark please try to initialize the variable before the for loop.

```
{% set subscriptionCheck = "N" %}
{% for order in craft.enupalStripe.getSubscriptionsByUser(currentUser.id) %}
  {% set subscription = order.getSubscription() %}
  {% if subscription.status == 'active' %}
	{% set subscriptionCheck = "Y" %}
	{% set subscriptionNumber = order.number %}
  {% endif %}
{% endfor %}
```

**Comment by madebyspark** [comment]
Tried that as well and it always returns N even if an active subscription exists for that user. i also get an error when I try to show the order.number: `Variable "subscriptionNumber" does not exist.`

**Comment by andrelopez** [comment]
Hi @madebyspark I have tested the code and is working on my local environment. Could you please make sure that you're getting the subscription from the right env (If TEST MODE is enabled) and checking that sub in Stripe with the same env mode?

Also, are you sure that the subscription is active? There are different statuses like `trial`

**Comment by madebyspark** [comment]
Yes, I have active subscriptions, but that code fails for me still.

Does it matter if you are in test mode?

**Comment by andrelopez** [comment]
@madebyspark What is the output of the following code?
```
<ul>
{% for order in craft.enupalStripe.getSubscriptionsByUser(currentUser.id) %}
  {% set subscription = order.getSubscription() %}
  <li>
      {{ subscription.status }}
  </li>
{% endfor %}
</ul>
```

**Comment by andrelopez** [comment]
I'm closing this ticket due to inactivity, please feel free to reopen if you still have this issue.
