### ISSUE TITLE
Possible to find out if user has any ACTIVE subscriptions?

### ISSUE THREAD

**Issue by iamkeir** [enupal/stripe#56]
Not a bug but wanted to check if there was a quick/easy way to find out if a user has **any** active subscriptions?

Currently, I have to loop through to check which is a bit ardous:
```
{% set _subscriptionOrders = craft.enupalStripe.getSubscriptionsByUser(currentUser.id) %}
{% set _hasActiveSubscriptions = false %}

{% for _order in _subscriptionOrders %}
  {% set _orderSubscription = _order.getSubscription() %}
  {% if _orderSubscription.status == 'active' %}
    {% set _hasActiveSubscriptions = true %}
  {% endif %}
{% endfor %}

{% if _hasActiveSubscriptions %}
  User has one or more active subscriptions...
{% endif %}
```
I had hoped there might either be a function or filter, e.g. `getSubscriptionsByUser(currentUser.id).status('active')`

I considered `craft.enupalStripe.orders({status: 'active'}).all()` but the `order.status` field always seems to be `null` which does not match the order subscription status.

Any help greatly appreciated. Brilliant plugin by the way!

**Comment by iamkeir** [comment]
Just to extend this - would be useful to be able to bring back a list of users with subscriptions (active or otherwise). 

We have a page where we show a list of users but only if they have one or more active subscriptions. We can check as we loop through users but this messes up Craft pagination.

Instead, would be good to be able to return an array of users -  something like `{% set _usersWithActiveSubscriptions = craft.enupalStripe.getUsersWithSubscriptions.status('active') %}` or something along those lines.

**Comment by iamkeir** [comment]
Temporary workaround:
```
{# Get all users #}
{% set users = craft.users() %}

{# Check for active subscriptions and build another array of users #}
{% set usersWithActiveSubscriptions = [] %}
{% for user in users %}
  {% set userSubscriptionOrders = craft.enupalStripe.getSubscriptionsByUser(user.id) %}
  {% set userHasActiveSubscriptions = false %}
  {% for order in userSubscriptionOrders %}
    {% set orderSubscription = order.getSubscription() %}
    {% if orderSubscription.status == 'active' %}{% set userHasActiveSubscriptions = true %}{% endif %}
  {% endfor %}
  {% if userHasActiveSubscriptions %}
    {% set usersWithActiveSubscriptions = usersWithActiveSubscriptions | merge([user]) %}
  {% endif %}
{% endfor %}

{# Output users #}
{% if usersWithActiveSubscriptions|length %}
  {% for user in usersWithActiveSubscriptions %}
    {# Output user stuff #}
  {% endfor %}
{% endif %}
```

**Comment by iamkeir** [comment]
Unfortunately our temporary workaround slows our page load speed significantly - would recommend avoiding if within a large dataset.

**Comment by bymayo** [comment]
@iamkeir Is it not possible to just do:

`{% if craft.enupalStripe.getSubscriptionsByUser(currentUser.id)|length %}{% endif %}`

**Comment by andrelopez** [comment]
Related to https://github.com/enupal/stripe/issues/67#issuecomment-573265006

As we don't store the subscription info in the database, the only solution that I see is contact the Stripe support and check if there is a way to List subscriptions passing an array of the specific IDs.
