### ISSUE TITLE
Subscription status for card billing issues?

### ISSUE THREAD

**Issue by iamkeir** [enupal/stripe#57]
Is there any documentation/guidance on handling billing issues when a subscription auto-renews? E.g. a customer's card on file has expired/cannot be billed. Perhaps a subscription/order status other than `active` or `canceled`?

I would like to be able to show an error message explaining to the user there is a billing issue and the steps to fix the problem.

Ideally they would also be able to provide amended/new card details to fix the problem - which I think may be covered by this planned feature? https://github.com/enupal/stripe/issues/25

Thanks :)

**Comment by iamkeir** [comment]
From @andrelopez:

> Yes - please make sure you have up and running your webhook URL that will notify to your site the payment error.
> Please follow our example to handle a subscription ends event https://enupal.com/craft-plugins/stripe-payments/docs/plugin-development/events#afterprocesswebhook
> There you can remove user permissions or any business logic

I also found a Stripe test card that creates a billing issue so will experiment and report back.

**Comment by andrelopez** [comment]
Hi @iamkeir extracted from [Billing Lifecycle](https://stripe.com/docs/billing/lifecycle)

> When an automatic payment on a subscription fails, a charge.failed event and an invoice.payment_failed event are sent, and the subscription state becomes past_due. Stripe attempts to recover payment according to your configured retry rules.

You can listen to the `invoice.payment_failed` event and send a notification email to the customer to update their card before Stripe makes a new attempt.

**Comment by iamkeir** [comment]
Thanks - I'll close for now and re-open if I get stuck :)

**Comment by iamkeir** [comment]
For reference, when calling `order.getSubscription()` a subscription can have the following status:

-`active`: active and all good
-`canceled`: cancelled subscription (american spelling)
-`past_due`: unpaid invoice and likely a billing issue (expired card/failed card/no card)

Are there any others? Might be worth adding to your documentation.

**Comment by iamkeir** [comment]
Possibly `unpaid`?

**Comment by iamkeir** [comment]
For future reference, these are the subscription statuses from Stripe:
https://stripe.com/docs/billing/lifecycle#subscription-states
