### ISSUE TITLE
If order refunded, it equals a string of '0'

### ISSUE THREAD

**Issue by iamkeir** [enupal/stripe#60]
### Description
Weirdly, when using `order.getSubscription()`, the `refunded` value is equal to a string value of `'0'` if the order has been refunded. Feels like it should equal `true` or `1` instead. Is this controlled by Stripe Payments or is this data provided directly by Stripe? If the latter, it may be a bug to report with Stripe directly.

### Steps to reproduce

1. Output `{{ dump(order.getSubscription().refunded) }}` for a refunded order
2. Notice the value is a string of `'0'`

### Additional info

- Craft version: Craft Pro 3.3.16.3
- PHP version: 7.3.12
- Database driver & version: MySQL 5.7.28
- Plugin version: 2.1.3

**Comment by andrelopez** [comment]
Hi @iamkeir The best way to check if the subscription is refunded is:

`{{ order.refunded }}`

**Comment by iamkeir** [comment]
My mistake, I was actually using `{{ order.refunded }}` but, as I said, if you do `{% if order.refunded %}` it evaluates to false because it is a string of `0`. You have to do `{% if _order.refunded == '0' %}` to make it evaluate to `true`.

See here: https://jmp.sh/z4iKoR0
