### ISSUE TITLE
An invalid form control with name='stripeElementEmail' is not focusable.

### ISSUE THREAD

**Issue by maddyBoy** [enupal/stripe#62]
### Description
Getting the js error in console.log.

### Steps to reproduce

1.create a form with these settings

![card-settings](https://user-images.githubusercontent.com/26545067/70120458-98093d00-1692-11ea-8f1a-396e2df5512c.png)

2. Fill the form with detils and see the console.log

### Additional info

- Craft version: Craft CMS 3.3.15
- PHP version: PHP 7.0.33
- Plugin version: 2.1.2

**Comment by andrelopez** [comment]
Hi @maddyBoy Please update to the latest version (v2.1.4) this issue should be fixed. Please reopen this ticket if not.
