### ISSUE TITLE
Possible to run 'Sync Orders' via CRON?

### ISSUE THREAD

**Issue by iamkeir** [enupal/stripe#63]
Is it possible to run the Stripe Payments 'Sync Orders' task via a command, e.g. `stripe-payments/sync-orders` or similar, so that it could be run by a daily CRON task? Apologies if I have missed this in the docs.

**Comment by andrelopez** [comment]
Hi @iamkeir Sorry, this feature is not available, but you can create a Console Controller within a custom plugin and run the following code to add the job to the queue: 

https://github.com/enupal/stripe/blob/master/src/controllers/SettingsController.php#L117

Here is a console controller example: https://github.com/craftcms/cms/blob/develop/src/console/controllers/ClearCachesController.php
