### ISSUE TITLE
Possible to switch subscription?

### ISSUE THREAD

**Issue by iamkeir** [enupal/stripe#64]
Is it possible to switch from one subscription/plan to another using a Stripe Payments form?

Or, if not, perhaps something that needs to be custom coded using `EVENT_AFTER_ORDER_COMPLETE`?

Thanks :)

**Comment by andrelopez** [comment]
Planning add this feature based on the next docs: https://stripe.com/docs/billing/subscriptions/upgrading-downgrading

Adding a form example to be submitted from the front-end

**Comment by andrelopez** [comment]
Hi @iamkeir We just released Stripe Payments v2.1.7 with support to upgrading or downgrading plans. [More info](https://enupal.com/craft-plugins/stripe-payments/docs/templating/update-subscription-plan)

Enjoy!
