### ISSUE TITLE
Changing user email does not update Stripe - possible feature request

### ISSUE THREAD

**Issue by iamkeir** [enupal/stripe#65]
### Description
If a user updates their email address in Craft, it does not update in Stripe, so payment/invoice email notifications still go to the old email address.

Is this a bug, or a feature request?

### Steps to reproduce

1. Create a subscription for a user
2. Change email address of user
3. Notice subscription customer in Stripe is still old email address

**Comment by andrelopez** [comment]
Hi @iamkeir We just released Stripe Payments v2.2.0 with support to this feature. After update your plugin, go to Stripe Payments -> Settings -> Defaults and enable the "Update customer email on Stripe" lightswitch

Best,
