### ISSUE TITLE
getSubscription in order loop very slow

### ISSUE THREAD

**Issue by iamkeir** [enupal/stripe#67]
### Description
I am outputting a subscription order history, paginated by 12 but I am finding that `order.getSubscription()` is really slowing down the page load when it is called on each order.

This is obviously not surprising due to the fact it is querying Stripe for each order - but I wondered if there is any way to speed up this query? 

I would usually use Craft's Eager Loading `with` functionality but that does not apply in this case.

Another option would be to wrap the order history in `{% cache %}{% endcache %}` but does Stripe have cache-busting built in if the order table updates?

I have also tweeted Stripe to see if they are having API issues as this was not a problem for us until the last day or so.

### Steps to reproduce

1. Output some orders on a page
2. Loop through each order
3. Call `order.getSubscription()` on each `order` in the loop
4. Notice how the page load is negatively affected

### Additional info

- Craft version: Craft Pro 3.3.18.1
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Plugin version: 2.1.7

**Comment by iamkeir** [comment]
I tried using `{% cache %}` but it does not flush/update when orders change.

**Comment by iamkeir** [comment]
I think this gets slower as the number of orders increases, linked to the number of `order.getSubscription()` calls being made.

**Comment by andrelopez** [comment]
Hi @iamkeir, unfortunately, Stripe does not support in their [API](https://stripe.com/docs/api/subscriptions/list) list subscriptions passing the ids (something like an array) to make only one call instead of call one by one.
