### ISSUE TITLE
$e->order always empty in afterProcessWebhook

### ISSUE THREAD

**Issue by iamkeir** [enupal/stripe#69]
### Description
As per the [webhook event docs](https://enupal.com/craft-plugins/stripe-payments/docs/plugin-development/events), I have been trying to use `$e->order` to get information pertaining to the order, such as customer email (`$order->email`) and subscription info (`$subscription = $order->getSubscription()->status`).

However, no matter what event type it is, `$e->order` is always empty. Has Stripe Payments or Stripe API changed regarding this? It was working recently...

Code in use:
```
Event::on(
          Orders::class,
          Orders::EVENT_AFTER_PROCESS_WEBHOOK,
          function(WebhookEvent $e) {
                    $data = $e->stripeData;
                    LogToFile::log($data['type'] . ': ' .print_r($e->order, true), 'business-logic');
          }
);
```

In logs:
```
2019-12-14 17:33:33 [][][info] customer.discount.created:
2019-12-14 17:33:33 [][][info] customer.subscription.created:
2019-12-14 17:33:33 [][][info] invoice.created:
2019-12-14 17:34:34 [][][info] customer.discount.created:
2019-12-14 17:34:34 [][][info] customer.subscription.updated:
2019-12-14 17:34:41 [][][info] customer.subscription.deleted:
2019-12-14 17:34:43 [][][info] invoice.updated:
```

### Additional info
- Craft version: Craft Pro 3.3.18.1
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Plugin version: 2.1.7

**Comment by andrelopez** [comment]
Hi @iamkeir the order could be empty due that that event does not have the Stripe ID that we store in the db, something like sub_xxx or ch_xxxx if you can get that info from the stripeData variable you can then get the order using the following service:

```php
use enupal\stripe\Stripe;


$order = Stripe::$app->orders->getOrderByStripeId($stripeId);
```

**Comment by iamkeir** [comment]
That didn't work for me either - `$order = Stripe::$app->orders->getOrderByStripeId($data['data']['object']['id']);` returns null.

The weird thing is, if I resend the webhook from Stripe, it succeeds. So it is almost as if the webhook is firing before the order has been created in Stripe Payments. Is that possible?

**Comment by iamkeir** [comment]
As a short-term fix, is there a function in Stripe Payments to get Stripe customer email from Stripe customer ID? E.g. `Stripe::$app->orders->getCustomerById`

Webhooks return the customer ID but I need an email address to correctly pair this up with a Craft user and perform the logic I need.

**Comment by andrelopez** [comment]
That's correct @iamkeir, if you've enabled SCA in some events the order still does not exists, you may need an if statement to listen to the next event: `checkout.session.completed` we add the following comment in our [docs](https://enupal.com/craft-plugins/stripe-payments/docs/plugin-development/events#afterprocesswebhook)
```
// Occurs whenever a customer is signed up for a new plan. (If SCA is enabled) 
 // Stripe sends the checkout.session.completed (where the order is created) after customer.subscription.created, 
// so we need to validate new subscriptions here
```

**Comment by iamkeir** [comment]
@andrelopez we're not using SCA so I did not think this applied to us.

It is really strange - when using my local environment, the order variable is present in the `customer.subscription.created` event. However, in the live environment, it is not. The codebase and database are identical. Is there anything we may have missed?

**Comment by andrelopez** [comment]
Does the live environment have the same Stripe keys and testMode? Are you loading the your settings from the db or using the config file?

**Comment by iamkeir** [comment]
All keys and modes are correct as far as I can see.

Further development - _sometimes_ `customer.subscription.created` event has an order, other times it does not. This is in This is from our logs:
```
2020-01-11 00:08:27 [][][info] webhook:customer.subscription.updated,order:true
2020-01-12 00:00:24 [][][info] webhook:customer.subscription.updated,order:true
2020-01-13 10:25:05 [][][info] webhook:customer.subscription.created,order:false
2020-01-13 10:59:07 [][][info] webhook:customer.subscription.created,order:false
2020-01-13 11:39:55 [][][info] webhook:customer.subscription.created,order:true
2020-01-13 14:29:43 [][][info] webhook:customer.subscription.created,order:true
```
This is same codebase across all those days. Inconsistent bugs are the worst :(

Is there anyway to get the customer email address within the webhook without using the order? This would give us a workaround.

**Comment by iamkeir** [comment]
Feel free to close this as we have moved to a different solution for our subscriptions.
