### ISSUE TITLE
Swift_RfcComplianceException

### ISSUE THREAD

**Issue by lindseydiloreto** [enupal/stripe#7]
**Plugin version: 1.5.2**
**Craft version: 3.0.25**

Looks like the "Reply To" email address needs to be required...

<img width="411" alt="fields" src="https://user-images.githubusercontent.com/5309692/45774287-6e850280-bc01-11e8-882c-509c5791660c.png">

Otherwise you'll trigger this error when making a purchase...

<img width="673" alt="error" src="https://user-images.githubusercontent.com/5309692/45774362-93797580-bc01-11e8-8773-ad90da3277b7.png">

Which traces back to this code...

<img width="990" alt="stack trace" src="https://user-images.githubusercontent.com/5309692/45774460-db000180-bc01-11e8-9a74-0f82cd9c0e40.png">

**Comment by lindseydiloreto** [comment]
Hmm... On further testing, I seem to be getting this error even _with_ that field filled out.

Can I email you a complete stack trace? I'm happy to share the DB as well.

Feel free to also ping me on Craft Slack. :)

**Comment by andrelopez** [comment]
This error was caused due to empty values in required fields when sending the email. This is fixed adding validations when the notification is enabled. 

Thank you @lindseydiloreto for reporting this bug.

**Comment by lindseydiloreto** [comment]
Awesome, thanks @andrelopez! 🍺
