### ISSUE TITLE
craft.enupalStripe.getStripeCustomer(currentUser.email) returns deleted customer instead of current active one

### ISSUE THREAD

**Issue by iamkeir** [enupal/stripe#70]
### Description
If you have a customer in Stripe, then delete them, then add them again (with same email address), `craft.enupalStripe.getStripeCustomer(currentUser.email)` retrieves a deleted customer, not the currently active one.

I guess perhaps `craft.enupalStripe.getStripeCustomer` needs to check the customer is active?

### Additional info
- Craft version: Craft Pro 3.3.18.1
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Plugin version: 2.1.7

**Comment by andrelopez** [comment]
Sorry for the late update but we fixed this issue since v2.2.0 please check the "Update customer email on Stripe" setting
