### ISSUE TITLE
Order syncing problems

### ISSUE THREAD

**Issue by iamkeir** [enupal/stripe#71]
### Description
We have encountered a couple of problems with keeping orders in sync between Stripe and Craft.

1. When I refunded an order in Stripe and cancelled the subscription, the order in Stripe Payments has not updated to `refunded`. I then ran a manual order sync to see if that would fix the problem but it did not.

2. When a customer paid an outstanding subscription invoice via Stripe-hosted checkout, no order was created in Stripe Payments. Again, I ran a manual order sync to see if that would fix the problem but it did not.

### Additional info

- Craft version: Craft Pro 3.3.18.1
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Plugin version: 2.1.7

**Comment by andrelopez** [comment]
Hi @iamkeir 

1.- is an enhancement (you can create your own business logic via webhooks in the meantime)

2.- Do you think it could be a date issue? Have you synced the orders by date?

**Comment by andrelopez** [comment]
Sorry for the late update but we fixed this issue since v2.2.0 please check the "Update customer email on Stripe" setting

**Comment by andrelopez** [comment]
We had an issue on the Sync dates and is fixed on Stripe Payments v2.6.0 Please let me know if that solves this issue. Feel free to reopen if you still have that issue.
