### ISSUE TITLE
craft.enupalStripe.getStripeCustomer returning null despite customer existing in Stripe

### ISSUE THREAD

**Issue by iamkeir** [enupal/stripe#72]
### Description
I am using `craft.enupalStripe.getStripeCustomer` to get the Stripe customer object for use with things like customer card details but it is returning `null` despite the customer existing in both Stripe and Stripe Payments' orders.

### Additional info
https://jmp.sh/RjaJVwx

- Craft version: Pro 3.3.18.3
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.28
- Plugin version: 2.1.7

**Comment by andrelopez** [comment]
Hi @iamkeir I'm unable to recreate this issue. Could you please check that Stripe Payments and the records in Stripe has the same testMode?

**Comment by iamkeir** [comment]
They are both matching. 

I should mention that this happened when I used a Payments Form to sign up to a subscription and provide card details - rather than adding card details via the new functionality Stripe modal window. Could you try that to see if you can replicate if you do it that way?

**Comment by andrelopez** [comment]
Hi @iamkeir I'm still unable to recreate this issue. Could you please send us your templates to review your code? please use the following email: support@enupal.com

**Comment by andrelopez** [comment]
I will close this ticket for now. Please feel free to follow up via our email support

**Comment by iamkeir** [comment]
Unfortunately we had to move to a different solution for our subscriptions but thank you anyway.

**Comment by siebird** [comment]
I'm getting the same results returning `null`. Code I'm using: 

```
{% set number = craft.request.getQuery('number') %}
    {% set order = craft.enupalStripe.getOrderByNumber(number) %}
    {% set stripeCustomer = craft.enupalStripe.getStripeCustomer(order.email) %}
    {{ order.email }}
    <pre>
        {{ dump(stripeCustomer) }}
    </pre>
    <pre>
        {{ dump(order) }}
    </pre>
```

and `craft.enupalStripe.getStripeCustomerByEmail` is an unknown method.
