### ISSUE TITLE
Payment Form not show Card Detail Form

### ISSUE THREAD

**Issue by saxenapritesh** [enupal/stripe#73]
### Description

As, when I enable payment form using card method it doesn't show us card detail form.

### Steps to reproduce

1. Install Plugin and add stripe Details.
2. Create a Payment form and set Payment Method to `Card`.
3. But in frontend it only show email field.

`Frontend Form`

![enupal22](https://user-images.githubusercontent.com/26432256/71572197-fe537500-2b03-11ea-9ed3-e65bec7310fc.png)

`Backend Settings`

![enupal22333](https://user-images.githubusercontent.com/26432256/71572218-16c38f80-2b04-11ea-833f-e50ff3bbd3f5.png)

`Error `

![enupal-3](https://user-images.githubusercontent.com/26432256/71572302-5db18500-2b04-11ea-97c4-a3f8ce65c293.png)

### Additional info

- Craft version: 3.3
- PHP version: 7.1
- Plugin version: 2.1.7

**Comment by andrelopez** [comment]
Hi @saxenapritesh the issue could be due to the following scenarios:
- Make sure that the `paymentForm` tag is outside the `cache` tag in your templates.

- Are you using template overrides? If so please make sure to update it to the latest changes. (https://github.com/enupal/stripe/tree/master/src/templates/_frontend)

**Comment by saxenapritesh** [comment]
Hi @andrelopez,
- For testing, I just put the `paymentForm` code in an empty template in fresh craft installation.
- No cache tag is used.
- No template override. 
Still same issue

**Comment by saxenapritesh** [comment]
Hi @andrelopez,

[web.log](https://github.com/enupal/stripe/files/4016106/web.log)

I have attached my web log file please have a look into this.

**Comment by saxenapritesh** [comment]
Hi @andrelopez,

Can you please tell me what's the status of this as i have waiting for this issue for some days.

**Comment by andrelopez** [comment]
It looks like a JS conflict, could you please make sure that Jquery is loaded in the html page? Also, could you please open de debug toolbar (F12) in Chrome, click the console tab and send us a screenshot?

**Comment by andrelopez** [comment]
I'm going to close this ticket but feel free to re-open if you have any update.
