### ISSUE TITLE
Clicking multiple times on Stripe Payments form submit results in multiple customers/subscriptions

### ISSUE THREAD

**Issue by iamkeir** [enupal/stripe#74]
### Description
If you click multiple times on the Stripe Payments form submit button, despite it being disabled, it still seems to send multiple submissions resulting in multiple customers and subscriptions.

### Video
https://jmp.sh/T6BRBXU

### Steps to reproduce

1. Use a Stripe Payments form to sign up to a subscription
2. Click the submit button multiple times
3. See that multiple customers and subscriptions are created

### Additional info

- Craft version: Craft Pro 3.3.19
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Plugin version: 2.1.7

**Comment by andrelopez** [comment]
Hi @iamkeir We just released Stripe Payments v2.2.0 with a fix to this issue.
