### ISSUE TITLE
Checkout Success URL using wrong order number

### ISSUE THREAD

**Issue by mark-adigital** [enupal/stripe#75]
Hi - I have a payment form set up using the Stripe Checkout and a Checkout Success URL of /thanks?number={number}, but the value of {number} is defaulting to the oldest order rather than the newly created one. I haven't entered a Global Return URL to the default settings and the Return URL under the 'advanced' form settings is also empty. Any advice much appreciated. Thanks.

**Comment by mark-adigital** [comment]
Just wondered if there was any update to this?

**Comment by andrelopez** [comment]
Hi Mark,

Do you have SCA enabled? Could you please send me a screenshot of your payment form settings?

**Comment by mark-adigital** [comment]
Hi Andre - thanks for picking this up.

Yes - there's four payment forms and they are all using SCA. Please find screenshot of form settings below, however I've noticed that regardless of which one I submit it's still the same oldest order that is returned so I'm not sure the issue is at the form settings level. I have also written a module which listens for successful and refunded transactions and for two of the forms will add or remove entries as a result, but I don't believe this is resetting the active order anywhere.

<img width="1029" alt="Screenshot 2020-01-24 at 09 15 15" src="https://user-images.githubusercontent.com/30312669/73057862-63438600-3e8a-11ea-8ffb-b025915745b2.png">

**Comment by mark-adigital** [comment]
Hi @andrelopez  - have you had a chance to look into this issue any further? Thanks.

**Comment by andrelopez** [comment]
Hi @mark-adigital 
Sorry for the late reply. I'm unable to recreate this issue, I'll let you know if I find something.

**Comment by andrelopez** [comment]
What is your Craft CMS version?

**Comment by mark-adigital** [comment]
Thanks for looking @andrelopez . Craft version is currently 3.4.5 - it's a dev site so I've seen it happen through multiple latest versions of Craft over the month or so since I opened this issue.

**Comment by andrelopez** [comment]
Hi @mark-adigital I think this issue is related #76 we need to add support to Craft 3.4 I'll update this ticket once we fixed it.

**Comment by mark-adigital** [comment]
Thanks for the update @andrelopez , I _may_ have seen the issue pre-3.4 but am honestly not entirely sure right now, so worth trying for sure.

**Comment by andrelopez** [comment]
Hi @mark-adigital We just released Stripe Payments v2.3.0 with support to Craft 3.4, if you update the plugin and still having the issue, could you please disable your custom plugins and try again? If the error persists please let me know.

**Comment by mark-adigital** [comment]
Thanks @andrelopez , unfortunately the issue does persist - including when I disable the custom module I wrote to listen for Stripe Payment events. Do you want me to provide a list of other plugins used on the install?

**Comment by andrelopez** [comment]
@mark-adigital  could you please confirm that your Webhook Url it's available across the internet (hit the URL from an incognito window) also please make sure the next webhook event is enabled on your Stripe Dashboard checkout.session.completed

**Comment by mark-adigital** [comment]
Checked both of those, @andrelopez , and the webhook URL is accessible (I get a `{"success":true}` return) and the `checkout.session.completed` event is enabled on the webhook.

**Comment by andrelopez** [comment]
@mark-adigital But the new order is created on the Stripe Payments plugin? Could you please recreate the issue and send back to us a zip file of the following folder `storage/logs` to support@enupal.com ?

**Comment by benface** [comment]
Hey @andrelopez I am experiencing te same issue. I don't have webhooks set up right now because I'm still at the local dev stage, but it seems the `{number}` in the "Checkout Success URL" field always evaluates to the first order's number rather than the latest one.

**Comment by andrelopez** [comment]
Sorry for taking too long to recreate this issue it was a little bit tricky. This issue is fixed on Stripe Payments v2.6.1
