### ISSUE TITLE
Custom Form Fields not saving - Add support to Craft CMS 3.4.x

### ISSUE THREAD

**Issue by mijewe** [enupal/stripe#76]
### Description
I try to add custom fields to a form (Stripe Payments > Payment Forms > New Payment Form > Form Fields).
I hit save (or cmd+s).
When the page refreshes, it has not saved my new fields.
There is no error message. I instead get the positive "Payment form saved." message.
There's nothing in the logs I can see.

This is following on from my comment on #37 - running a config sync threw an error, reporting that
"
The following config paths could not be processed successfully:
matrixBlockTypes.bb46e506-aed5-47ba-b8b4-94084cc0d63a
matrixBlockTypes.57e19050-8d5c-432f-b9c3-907a9f58b810
matrixBlockTypes.2093387a-da39-431d-8d95-69bbd47488f9
matrixBlockTypes.da481973-0b12-4a1a-9384-be9b8a664867
"

I have tried uninstalling and reinstalling the plugin, running a config sync with --force, but no luck. The plugin reports everything is fine, but the fields don't save.

Assuming all was lost I added a custom meta field directly into the template, but this doesn't seem to be being picked up and sent through to Stripe.

Potentially related:
My successful payments are not being reported on (Stripe Payemnts > Orders).

### Additional info

- Craft version: 3.4.2
- PHP version: 7.3
- Database driver & version: MySQL 5.5.5
- Plugin version: 2.2.0

**Comment by andrelopez** [comment]
We need to add support to Craft CMS 3.4.x, please stay tuned

**Comment by andrelopez** [comment]
Hi @mijewe We just released Stripe Payments 2.3.0 with support to Craft 3.4, Could you please check if that fixes your issues?

**Comment by mijewe** [comment]
Yep excellent - this has fixed my issues with fields!

Thanks!
