### ISSUE TITLE
Not being taken to Checkout Success URL after payment

### ISSUE THREAD

**Issue by mijewe** [enupal/stripe#78]
### Description
I've set a Checkout Success URL on my Payment Form.
When I go through a payment however, it returns me to the homepage, not my specified Checkout Success URL.

(The Checkout Cancel URL works fine.)

### Steps to reproduce

1. Set a Checkout Success URL on a new or existing Payment Form
2. Complete a payment
3. You'll be redirected to the homepage

### Additional info

- Craft version: Pro 3.4.9
- PHP version: 7.3.6
- Database driver & version: MySQL 5.5.5
- Plugin version: 2.3.1

**Comment by andrelopez** [comment]
Could you please confirm the following questions?
- Do you have SCA enabled?
- If so, are you testing from a live (or staging) URL?
- The order is created on the Stripe Payments plugin?

**Comment by bearfjellstad** [comment]
I have the same issue. Cancel URL works fine.

In my case:
- SCA is enabled
- Testing from a staging URL
- The order shows up on stripe.com, but is not created on the Stripe Payments plugin

### Additional info
- Craft version: SOLO 3.4.9
- PHP version: 7.3.5
- Database driver & version: MySQL 5.7.26
- Plugin version: 2.3.1

**Comment by mijewe** [comment]
Yep - same answers for me.

- SCA yes,
- staging and live URLs both affected (ie testing and live Stripe modes)
- order in Stripe, but not in Craft.

I guess if the order isn't created, the "redirect to this page after an order is created" isn't triggered, so maybe this is a bigger issue of orders not being created in Craft.

**Comment by andrelopez** [comment]
@mijewe @bearfjellstad Hey guys, could you please confirm that your [Webhook Url](https://enupal.com/craft-plugins/stripe-payments/docs/stripe-payment-forms/webhook) it's available across the internet (hit the URL from an incognito window) also please make sure the next webhook event is enabled on your [Stripe Dashboard}(https://dashboard.stripe.com/account/webhooks) `checkout.session.completed`

**Comment by bearfjellstad** [comment]
It does indeed work for me when the Webhook Url is publicly exposed. Thanks!

**Comment by mijewe** [comment]
Yep that also did it for me - thanks!

Do you have any guidance on what events we need to fire from Stripe? I was going to go for all the Payment Intents and Checkout ones.

**Comment by andrelopez** [comment]
Hi @mijewe Besides that we just added a recommended list [here](https://enupal.com/craft-plugins/stripe-payments/docs/stripe-payment-forms/webhook#events) glad that this issue is solved.
