### ISSUE TITLE
Store keys in `.env` file

### ISSUE THREAD

**Issue by lindseydiloreto** [enupal/stripe#8]
It would be ideal if we could store our Stripe keys (both Publishable & Secret) in our local `.env` file. Additionally, it would be nice to store the current Mode as well. Basically, all values in this screenshot should be storable in the `.env` file...

<img width="590" alt="stripe keys" src="https://user-images.githubusercontent.com/5309692/46237617-75ff8680-c33a-11e8-8ab9-a8913a2e1183.png">

There are two excellent reasons for this:

1. **Security.** Keeping those keys in the database is technically a security risk. Database exports can get passed around with little regard to the data stored inside.

2. **Safety.** I'd like to guarantee that the production server _only_ knows and cares about the Live keys, and the staging and local sites _only_ care about the Test keys. If either of those got mixed up, it would be bad news.

Making sure that we switch from Live to Test (and switch the keys appropriately) every time we pull down a copy of the database is really not sustainable.

Fortunately, this is really easy to do in Craft 3! Here's how I've done it...

https://github.com/doublesecretagency/craft-cpcss/blob/v2/src/CpCss.php#L81
https://github.com/doublesecretagency/craft-cpcss/blob/v2/src/templates/settings.twig#L19-L20

Feel free to ping me with questions! Thanks!  🙂

**Comment by andrelopez** [comment]
Since v1.5.9 Stripe API keys can be stored via the config file:

```
'stripePayments' => [
            'testPublishableKey' => getenv('YOUR_TEST_PUBLISHABLE_KEY'),
            'testSecretKey' => getenv('YOUR_TEST_SECRET_KEY'),
            
            'livePublishableKey' => getenv('YOUR_LIVE_PUBLISHABLE_KEY'),
            'liveSecretKey' => getenv('YOUR_LIVE_SECRET_KEY'),

            'testMode' => 1 // or 0
]
```

Thanks @lindseydiloreto

**Comment by lindseydiloreto** [comment]
Amazing, thanks @andrelopez! 🍺 🎉
