### ISSUE TITLE
[Feature Request] Add the ability to pass line items to Checkout via the `options` param

### ISSUE THREAD

**Issue by benface** [enupal/stripe#81]
This would be particularly useful for things like shipping fees that should be listed separately from the main item/product the user is purchasing.

**Comment by andrelopez** [comment]
Hi @benface Stripe Payments v2.5.0 has added support to this feature please let me know if you have any questions. 

https://enupal.com/craft-plugins/stripe-payments/docs/templating/paymentform#custom-line-items

**Comment by benface** [comment]
Wow, that was fast! Thank you!
