### ISSUE TITLE
Passing custom lineItems to paymentForm() still includes the form's "main item"

### ISSUE THREAD

**Issue by benface** [enupal/stripe#84]
I am not sure if this is expected. If it is, please consider what follows a feature request, and if it's not, please consider it a bug.

I want to be able to specify ALL the line items of a Checkout charge right from the template. I am following the example from the documentation:

```twig
{% set options = {
        lineItems : [
            {
                name : 'T-shirt',
                description : 'Comfortable cotton t-shirt',
                amount : 1500,
                currency : 'usd',
                quantity : 2,
            },
            {
                name : 'Hidden fee :)',
                description : 'There is always a fee',
                amount : 100,
                currency : 'usd',
                quantity : 1,
            }   
        ] 
    } 
%}
{{ craft.enupalStripe.paymentForm('paymentForm', options) }}
```

Right away, when clicking the Pay button with that code, I am getting an error (500 response from `/enupal/stripe/create-checkout-session`, with the error message "This value must be greater than or equal to 1"). I figured out that this was caused by the `paymentForm` form having an amount of `0`. I thought this shouldn't matter, because I'm explicitly passing line items with their own amounts, but ok, so I add an amount of 0.01 to the form, and this time it works but here's what I see in the Checkout UI:

![stripe](https://user-images.githubusercontent.com/1059139/78465402-33530300-76c3-11ea-9459-4f0007056c4b.jpg)

I don't want the "Company Name" line item at all. Is there no way to remove it?

Thank you!

**Comment by andrelopez** [comment]
I'll look into this one, probably we'll need to pass an extra option to disable the main one

**Comment by andrelopez** [comment]
Hi @benface We added support to `removeDefaultItem` please follow the instructions in our [docs](https://enupal.com/craft-plugins/stripe-payments/docs/templating/paymentform#custom-line-items)

**Comment by benface** [comment]
Nice, thank you very much!
