### ISSUE TITLE
What is the difference between "Checkout Success URL" and "Return URL"?

### ISSUE THREAD

**Issue by benface** [enupal/stripe#85]
Both these fields in the Payment Form settings have the exact same description:

> Redirect buyers' to this URL after they complete their payments

**Comment by andrelopez** [comment]
Sorry about the confusion.

- Checkout Success URL: Will be used when SCA is enabled in the general settings and Stripe Checkout is enabled in the payment form.

- Return URL will be used when SCA is disabled in the general settings.
