### ISSUE TITLE
"Payment Button Processing Text" is ignored when "Payment Button Text" is set

### ISSUE THREAD

**Issue by benface** [enupal/stripe#86]
### Steps to reproduce

1. Create a new payment form.
2. Set "Payment Button Text" to "Pay" and "Payment Button Processing Text" to "One moment please..."
3. In a template, `{{ craft.enupalStripe.paymentForm('paymentForm') }}`
4. Go to the page that renders that template and click on "Pay".

**Expected result:** The button's text changes to "One moment please..."
**Actual result:** The button's text doesn't change (stays "Pay")

### Additional info

- Craft version: Craft Pro 3.4.13
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26
- Plugin version: 2.5.1

**Comment by andrelopez** [comment]
Hi @benface This issue is solved on Stripe Payments v2.6.0
