### ISSUE TITLE
Update the sync workflow to support the new Stripe Checkout

### ISSUE THREAD

**Issue by benface** [enupal/stripe#87]
Right now when you try to sync orders created with the new Stripe Checkout, a lot of information isn't properly synced:

- Billing details (including customer name)
- Shipping details
- Order items (order than the first one)
- Maybe more that I don't know about

**Comment by andrelopez** [comment]
Hi @benface We just released Stripe Payments v2.6.0 with a fix to the addresses issue. We can't add the info from the line items to the Order you may need to query Stripe directly, sorry about that.

**Comment by benface** [comment]
Thank you!
