### ISSUE TITLE
Override item description on Stripe form

### ISSUE THREAD

**Issue by siebird** [enupal/stripe#88]
It would be nice to override the item description with a Stripe Form. 

An [example here](https://d.pr/i/tNsbdH)

```
{% set options = {
	amount: entry.price,
	quantity: 1,
	itemDescription: entry.title
} %}
{{ craft.enupalstripe.paymentForm(paymentForm.handle, options) }}
```

**Comment by andrelopez** [comment]
Hi, we just release Stripe Payments v2.7.0 with a fix to this issue. Please let us know if that works.

More info here: https://docs.enupal.com/stripe-payments/templating/paymentform.html#options
