### ISSUE TITLE
[Feature Request] Add ability to customize a charge's `description`

### ISSUE THREAD

**Issue by benface** [enupal/stripe#89]
When using the new `lineItems` option (along with `removeDefaultItem: true`) with the new Checkout, there is currently no way to get which item(s) was/were purchased. That information is saved to Stripe, but it looks like it's not passed back to Craft in the webhook event or when syncing orders. However, I see that the good old `description` field is passed back, so if there was a way to customize it, we would have a way to get back what the transaction was for without querying Stripe manually. I'm thinking something like this:

```twig
{{ craft.enupalStripe.paymentForm('genericPaymentForm', {
  removeDefaultItem: true,
  lineItems: [
    {
      name: specificItem.title,
      amount: (specificItem.price * 100)|round,
      currency: 'cad',
      quantity: 1,
    },
  ],
  description: specificItem.title,
}) }}
```

Would something like this be reasonable?

Thank you very much in advance!

**Comment by andrelopez** [comment]
Hi @benface what about adding your items info to [hidden fields](https://enupal.com/craft-plugins/stripe-payments/docs/stripe-payment-forms/form-builder-metadata-fields#hidden-field)? Maybe you can add a comma-separated data
```twig
{# on your twig template add the variable that you need to use #}
{% do craft.enupalStripe.addVariables({ lineItems: lineItems }) %}
```
and then in your hidden field value, you can have something like
```twig
{lineItems[0].name}-{lineItems[0].amount},{lineItems[1].name}-{lineItems[1].amount}
```
Please let me know your thoughts

**Comment by benface** [comment]
Ohhh that looks like it would work @andrelopez. I see the hidden field's value in the `metadata` that comes back from Stripe in the "Order Synced" message's details, but I can't see it in the CP as shown in this screenshot: https://enupal.com/assets/docs/_lightboxdocs/24-stripe-payments.png. Would that be a bug with the Sync Orders feature or the new Stripe Checkout perhaps?

**Comment by andrelopez** [comment]
@benface That's right it looks like we're not storing metadata on sync, I have created a new issue to fix that https://github.com/enupal/stripe/issues/91

However, in the normal workflow, the metadata should be saved. If you're testing locally you could copy the `checkout.session.completed` json payload from your Stripe Dashboard -> Developers -> Events and send by POST using the POSTMAN tool the following URL `YOUR_WEBSITE_URL/enupal/stripe-payments`
Please let me know if you have any questions

**Comment by Coysh** [comment]
@andrelopez  I have an issue in which Stripe payout reports only allow you to export the **description** of the payment, rather than any metadata.

If possible, I'd like to set the Default Charge description to `{title}` or `{paymentFormName}` rather than `Order from {email}` but can't figure out the correct field, or if the field is available.

**Comment by sarianth** [comment]
@Coysh The default Charge description can be updated under Stripe Payments - Settings - Defaults and update the  `Charge Description` field

**Comment by Coysh** [comment]
My fix was using `{object.getPaymentForm().name}` to bring in the form name to the Description. Thanks @andrelopez @sarianth
