### ISSUE TITLE
Internal Server Error when clicking new Payment Form

### ISSUE THREAD

**Issue by bartrylant** [enupal/stripe#9]
When I click "+ new Payment Form" I get:

Internal Server Error
Server Error

EDIT: It only happens when the keys are not entered yet.

**Comment by andrelopez** [comment]
Hi @bartrylant 

I'm unable to recreate this error. Could you please recreate the error and send us an email to support@enupal.com with a zip file of `storage\logs\web.log` ?

Also, please specify:
PHP version:
Craft CMS version:
DB driver (mysql/postgres): 

Best,
