### ISSUE TITLE
Add support for taxes with the new Stripe Checkout

### ISSUE THREAD

**Issue by benface** [enupal/stripe#90]
It seems that enabling taxes has no effect on the new Stripe Checkout. Is this a bug or I'm misunderstanding the feature?

**Comment by andrelopez** [comment]
Hi @benface Taxes for subscriptions were introduced a couple on months ago, we'll add support for this on the next version, stay tuned :)

**Comment by kerrig** [comment]
@andrelopez is there a release date planned for this? I have a client wanting to add taxes to their subscription offerings and as far as I can tell this isn't currently possible. I'm using SCA checkout. Can you confirm that my client currently can not apply taxes to their subscriptions? Or if there is a way, could you tell me how I can do this?

If you need more information, please let me know!

**Comment by andrelopez** [comment]
We just released Stripe Payments v3.2.1 with support for taxes on the new Stripe Checkout.

More info: https://docs.enupal.com/stripe-payments/stripe-payment-forms/taxes.html#collect-taxes-in-checkout
