### ISSUE TITLE
Syncing Subscription Orders Failing

### ISSUE THREAD

**Issue by bboy-splendid** [enupal/stripe#92]
### Description
Syncing has stopped working for an unknown reason. Has been fine until now. Error shown:

Argument 1 passed to enupal\stripe\services\Countries::getCountryByIso() must be of the type string, null given, called in /home/ben/craft/vendor/enupal/stripe/src/services/Addresses.php on line 254

### Additional info

- Craft version: Craft Pro 3.4.16
- PHP version: 7.3.17
- Database driver & version: MySQL 5.7.29
- Plugin version: 2.6.0

**Comment by andrelopez** [comment]
What is your Stripe API version?

**Comment by bboy-splendid** [comment]
We have three api versions listed in our stripe dashboard:

Version: 2020-03-02 Latest
Last Used: May 12	
Usage: < 1%

Version: 2019-10-17 Default
Last Used: May 12	
Usage: < 1%

Version: 2019-09-09
Last Used: May 16	
Usage: 99%

**Comment by andrelopez** [comment]
Hi @bboy-splendid we just released Stripe Payments v2.6.2 with a fix to this issue, please let me know if that works.
