### ISSUE TITLE
Name of Payment Form with the Charge description

### ISSUE THREAD

**Issue by aaronbest4** [enupal/stripe#93]
### Description

Is it possible to send the name of the payment form with the Charge description?

Default charge description: Order from {email}

I would like to be able to customise it to "{paymentForm.Name} from {email}" when it arrives in Stripe.

I have tried a number of variations and have not been able to achieve that.

**Comment by andrelopez** [comment]
Hi @aaronbest4 please try the following description:

`Order from {object.getPaymentForm().name}`

**Comment by siebird** [comment]
@andrelopez how do we access form fields for the charge description? Trying to get the following `Order from {email} - {object.variants.courseTitle}` with no luck.

**Comment by andrelopez** [comment]
@siebird if you have a form field added to your payment form please use:

{object.getFormFields().courseTitle}

**Comment by siebird** [comment]
Perfect. Thanks @andrelopez

**Comment by beneberle** [comment]
> `{object.getPaymentForm().name}`

Thank you for posting, exactly what I needed. 

I'd like to encourage adding a brief mention of this to the documentation. Maybe it's really more of a standard twig templating thing, but I sure could have used the extra guidance. Thanks!
