### ISSUE TITLE
No order processed using SCA

### ISSUE THREAD

**Issue by alexr8** [enupal/stripe#97]
Hi all, i'd originally been testing using the non-sca form with no issues (order completes, order shows up in enupal dashboard, notification emails sent out). I switched to SCA, added my webhooks with the events in stripe as per the instructions, and now when i complete an order, it just redirects me to the root of my website (not the redirect url provided in the form), and no order is logged in craft, no event is fired (no emails sent etc.).

The logs in stripe show the transaction with a 200 ok message.

What might I be missing?

### Steps to reproduce

1. Turn on SCA, using test mode, set up webhooks with required events
2. Complete a test order

### Additional info

- Craft version: 3.4.16
- PHP version: 7.2
- Database driver & version:
- Plugin version: 2.6.1

**Comment by andrelopez** [comment]
@alexr8 could you please confirm that your [Webhook Url](https://docs.enupal.com/stripe-payments/docs/stripe-payment-forms/webhook) it's available across the internet (hit the URL from an incognito window) also please make sure the next webhook event is enabled on your [Stripe Dashboard](https://dashboard.stripe.com/account/webhooks) `checkout.session.completed`

**Comment by alexr8** [comment]
Hi @andrelopez thanks for the swift response - everything is working as expected now. I realised i'd added my webhook as a live webhook, but was running the plugin in test mode (first time with stripe - i'd wrongly assumed the webhook was sort of universal across test/live). Thanks for a great plugin!

**Comment by andrelopez** [comment]
@alexr8 Onward!
