### ISSUE TITLE
Amount field increments by .01

### ISSUE THREAD

**Issue by shantamg** [enupal/stripe#99]
### Description
The amount field that is generated (when a payment form is set to "custom amount") includes the html: `step=".01"` which causes the arrows in the field to change the amount by 1 cent. I imagine it would be more useful if the increment were 1, or perhaps even customizable.

**Comment by andrelopez** [comment]
Hi, we just release Stripe Payments v2.7.0 with a fix to this issue. Please let us know if that works.

Thanks for reporting.

**Comment by shantamg** [comment]
The field increments by whole numbers now. That's better, thanks!
